### ISSUE TITLE
[Bug report] In Busy.org's wallet, my transaction history loading will not end forever.

### ISSUE THREAD

**Issue by inoue-a** [busyorg/busy#1000]
Hello
I'm contributing as translator to Busy.org, and it is one of my favorite steem tools.
But I'm in trouble with an issue on Busy's wallet.
My transaction history loading will not end forever!

![](https://s20.postimg.org/mcdwm6dj1/gif.gif)

Of course, I checked other account's wallet, but it works correctly.
![](https://s20.postimg.org/hdqe7nwvh/image1.png)

It does not related that there are a lot of transactions.
This account has huge number of transactions, but its history is loaded.
![](https://s20.postimg.org/jdks44val/image3.png)

I thought that the login state is related, but it was not. 
Then I looked for other accounts that have similar problems.

It was found immediately.
My second account has same problem lol

Umm,,, I want to see it on another person's account.

I thought what is something in common between these accounts (except their owners).

In these days, I've been trying various things with those accounts for some translation work.
So I thought that the unusual history is that cause.
Then I search some words with Steemit's search box.

![](https://s20.postimg.org/p95j0ao71/image2.png)

I found!
Some users who have "Cancel transfer from savings" in their **recent** history have same issue in their wallet.

These are my environment:

PC1:
OS: Windows 7 64bit
Web Browser: Google Chrome (62.0.3202.75) and Firefox (56.0.2)
(My Internet Exploere 11 dose not work in Busy.org. )

PC2:
OS: Windows 10 64bit
Web Browser: Google Chrome (62.0.3202.75), Microsoft Edge 40.15063.674.0 and Firefox (56.0.2)

I hope this issue will be fixed soon.
Thank you for reading!<br /><hr/><em>Open Source Contribution posted via <a href="https://utopian.io/utopian-io/@inoue/bug-report-my-transaction-history-loading-will-not-end-forever">Utopian.io</a></em><hr/>

**Comment by jm90m** [comment]
Thanks for reporting this issue, I'll be taking a look into it
