### ISSUE TITLE
Change editor URL from `/write` to `/editor`

### ISSUE THREAD

**Issue by Sekhmet** [busyorg/busy#1011]
Currently post editor is under `/write`. We want to move it to `/editor` instead.

**Comment by eastmaels** [comment]
Will work on this.

**Comment by eastmaels** [comment]
I checked this and is this a simple change in URL when I click on the pencil 
![image](https://user-images.githubusercontent.com/29425738/32431238-a8814392-c30d-11e7-97fa-4e896707fcb3.png) icon?

Which directs to `https://busy.org/write`?
