### ISSUE TITLE
Clicking on "And {number} more" should open ReactionsModal

### ISSUE THREAD

**Issue by Sekhmet** [busyorg/busy#1013]
#### Expected behaviour

Clicking on text `And {number} more` on the bottom of the tooltip should open `ReactionsModal`. 
![image](https://user-images.githubusercontent.com/1968722/32409173-0be5d5f0-c1a7-11e7-95e7-9b6caba37724.png)

#### Actual behavior

It does not.

**Comment by eastmaels** [comment]
working on this.
