### ISSUE TITLE
User can select other files than image for upload

### ISSUE THREAD

**Issue by espoem** [busyorg/busy#1014]
#### Expected behavior

Only image files should be able to upload in editor.

#### Actual behavior

User can select other files to upload if they select them with the open dialog.

https://streamable.com/tftjg

https://streamable.com/9kgzd

#### How to reproduce

1. Open editor
2. Select image to upload
3. Select all files
4. Upload any file but image

* Browser: Chrome
* Operating system: Windows 10

**Comment by Sekhmet** [comment]
We should check if selected file is actually an image before uploading. Checking if it has reasonable size might be a good idea as well.
