### ISSUE TITLE
I see posts in my Feed from users I stopped following

### ISSUE THREAD

**Issue by espoem** [busyorg/busy#1022]
#### Expected behavior

User should see posts from users they follow or the posts that were reblogged.

#### Actual behavior

Posts from recently unfollowed users still show in the feed.

![post-follow](https://user-images.githubusercontent.com/16621517/32418219-e58cc214-c265-11e7-94c8-d4ef91f2121d.gif)

https://streamable.com/2rf7c

#### How to reproduce

1. Go to the Feed
2. Pick any user that you follow, and unfollow them. Choose someone from the top so it easy to check that it is in the Feed.
3. Go to feed and reload the page

* Browser: Chrome
* Operating system: Windows 10

**Comment by bonustrack** [comment]
It's the behavior of steemd API. I expect that when we will switch to "hive" solution this problem will be solved.
