### ISSUE TITLE
Profile image doesn't update after clicking a "Recommended Post"

### ISSUE THREAD

**Issue by mktcode** [busyorg/busy#1028]
![busy-profile-image](https://user-images.githubusercontent.com/6792578/32634825-de6efbdc-c5ad-11e7-8017-78152108c960.gif)

* Browser: Firefox 56, Chromium 62
* Operating system: Linux Mint 18

But I suppose this applies to all setups.

**Comment by jm90m** [comment]
This should have been fixed in #1045

**Comment by jm90m** [comment]
Closing this, please re-open if this issue still persists
