### ISSUE TITLE
There are different decimal separators in wallet

### ISSUE THREAD

**Issue by espoem** [busyorg/busy#1033]
#### Expected behavior

All numbers should use the same decimal separators.

#### Actual behavior

Values in the Market sidebar have fixed decimal separators. Separator changes for other numbers according to the set language.

![image](https://user-images.githubusercontent.com/16621517/32466282-b2348f00-c346-11e7-84e1-a8db7299068c.png)

#### How to reproduce

1. Set language to Czech
2. Go to the wallet
3. See estimated account value and values in the Market sidebar

* Browser: Chrome
* Operating system: Windows 10

**Comment by jm90m** [comment]
Thanks again for reporting this issue @espoem.

Fixed in https://github.com/busyorg/busy/pull/1043

Please re-open this issue, if you still see that it exists.
