### ISSUE TITLE
Claim rewards doesn't update current balance in the wallet info

### ISSUE THREAD

**Issue by espoem** [busyorg/busy#1034]
Busy has added a "Claim rewards" function. After you claim your rewards, you will see that the transaction was successful because it shows up in the transaction history. You can also check it on another site that tracks the history of the blockchain.

The problem is that the current balances are not visibly updated. The value stays the same after the transaction has been proceeded. I have claimed the rewards three times during the day and the balances were not updated in all cases.

![wallet-balance.gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1510000417/ovt1tolv6omjniebcgg1.gif)

### Expected behaviour

All balances should be updated according to the amount of the rewards wich were claimed.

### Steps to reproduce

1. Have a reward to claim
2. Go to https://busy.org/wallet
3. Claim rewards

- Browser: Chrome
- OS: Windows 10

<br /><hr/><em>Open Source Contribution posted via <a href="https://utopian.io/utopian-io/@espoem/claim-rewards-doesn-t-update-current-balance-in-the-wallet-info">Utopian.io</a></em><hr/>

**Comment by jm90m** [comment]
Thanks again for reporting this issue @espoem.

Fixed in https://github.com/busyorg/busy/pull/1043

Please re-open this issue, if you still see that it exists.

**Comment by jm90m** [comment]
Reopening this, for some users it still doesn't update.

**Comment by bonustrack** [comment]
This issue has been fixed in #1031
