### ISSUE TITLE
Comment sort options are not fully visible in Czech on mobile

### ISSUE THREAD

**Issue by espoem** [busyorg/busy#1037]
#### Expected behavior

All words for comment sorting should be fully visible.

![screenshot_20171016-213906](https://user-images.githubusercontent.com/16621517/32480561-af13f1aa-c38f-11e7-9198-c311bed9d1e8.png)

#### Actual behavior

Czech words are longer than the English ones. The option for "oldest" is partly cut off.

![screenshot_20171107-073952](https://user-images.githubusercontent.com/16621517/32480604-e6bd635c-c38f-11e7-9279-4ac6cf8265ae.png)

#### How to reproduce

1. Set language to Czech
2. Open a post and go to the comment section

* Browser: Brave
* Operating system: Android 7.1.2

**Comment by jm90m** [comment]
![image](https://user-images.githubusercontent.com/5067716/32612165-92ec6b86-c535-11e7-8553-a32a4264a07f.png)

Fixed in #1055, should wrap like in the image above
