### ISSUE TITLE
Comments number strings in Recommended posts sidebar should be same as in posts

### ISSUE THREAD

**Issue by espoem** [busyorg/busy#1040]
#### Expected behavior

StoryFull and PostRecommendation should use the same strings for comments count. That is `comments_count`.

StoryFull uses 

```javascript
<FormattedMessage
  id="comments_count"
  values={{ count: intl.formatNumber(commentCount) }}
  defaultMessage="{count} comments"
/>
```

PostRecommendation should use:

```javascript
<FormattedMessage
  id="comments_count"
  values={{ count: intl.formatNumber(post.children) }}
  defaultMessage="{count} comments"
/>
```

#### Actual behavior

The strings are different so it shows different words and capitalization. This happens in other languages too.

```javascript
const commentsText = post.children === 1
        ? intl.formatMessage({ id: 'comment', defaultMessage: 'Comment' })
        : intl.formatMessage({ id: 'comments', defaultMessage: 'Comments' });

<Link
  to={`/${post.category}/@${post.author}/${post.permlink}#comments`}
  onClick={() => this.navigateToPostComments()}
  className="PostRecommendation__comment-link"
>
  {post.children}
  {' '}
  {commentsText}
</Link>}
```

![image](https://user-images.githubusercontent.com/16621517/32485822-f6637d0e-c3a4-11e7-879f-c1ca74cf4260.png)

#### How to reproduce

1. Open any post

* Browser: Chrome
* Operating system: Windows 10

**Comment by jm90m** [comment]
Thanks again for reporting this issue @espoem.

Fixed in https://github.com/busyorg/busy/pull/1048

Please re-open this issue, if you still see that it exists.
