### ISSUE TITLE
Bug Hunting : Problems with user profile images

### ISSUE THREAD

**Issue by nhj7** [busyorg/busy#1041]
<center>![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1510050501/szgq7hu42y2vfhwpviuv.png)</center>

**Problems with user profile images**

<hr />
<br />

When you switch to posting for another account.
I have found a problem that my profile image does not change.
This may seem like nothing, but it can lead to misunderstandings.

**This is the profile image of @clayop**
![캡처_2017_11_06_14_31_16_784.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1510049890/sr0poqntnz8e1b7vkitw.png)

**But when I switch posts, I get a wrong profile image.**
![녹화_2017_11_06_14_30_49_649.gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1510049969/seb2zrqps1uwqj3hhqcp.gif)

I think it should be fixed as soon as possible.
Thank you for reading.
<br /><hr/><em>Open Source Contribution posted via <a href="https://utopian.io/utopian-io/@nhj12311/problems-with-user-profile-images">Utopian.io</a></em><hr/>

**Comment by jm90m** [comment]
Fixed in https://github.com/busyorg/busy/pull/1045
