### ISSUE TITLE
Time Joined is Blank (Use Indonesian Language)

### ISSUE THREAD

**Issue by isaideureka** [busyorg/busy#1049]
#### Actual behavior

![bug](https://user-images.githubusercontent.com/32774053/32545803-6b03d522-c4af-11e7-8fb1-20464e97a865.jpg)
![contribution8](https://user-images.githubusercontent.com/32774053/32545871-97e2d5c0-c4af-11e7-850c-8cf6886c7a0c.jpg)

#### How to reproduce

* Browser: Vivaldi Browser
* Operating system: Windows 7 x64 bit

**Comment by Sekhmet** [comment]
This has been fixed by translations update.
