### ISSUE TITLE
Discover more people link is not pointing to the right place

### ISSUE THREAD

**Issue by karencarrens** [busyorg/busy#1050]
#### Expected behavior
Discover more people link should refresh the list with more people to discover.

#### Actual behavior

Discover more people link is not pointing to the right place. Instead, it's pointing to URL busy.org/latest-comments

#### How to reproduce

* Browser: chrome 
* Operating system: win 10

**Comment by jm90m** [comment]
Related issues: https://github.com/busyorg/busy/issues/1026, https://github.com/busyorg/busy/issues/812
