### ISSUE TITLE
The amount of the worth of a vote is not right

### ISSUE THREAD

**Issue by gregory-latinier** [busyorg/busy#1057]
The amount in $ of the voting slider is not the same once voted

![image](https://user-images.githubusercontent.com/13222767/32595572-aee978b0-c530-11e7-9864-5af23d6ad802.png)

Once I've voted

![image](https://user-images.githubusercontent.com/13222767/32595586-bc6fdd62-c530-11e7-914e-011de7e03e25.png)

There is a 2 cents difference

#### Expected behavior

The voting amount calculated should be exact or change the text if we can only have an approximation

#### Actual behavior

The voting amount calculated is slightly less

#### How to reproduce

Vote for a post

**Comment by bonustrack** [comment]
I have a huge difference now when doing an upvote i see `$1.37` for the estimated vote value while after doing the vote i see in tooltip the value of `$2.78`:
![image](https://user-images.githubusercontent.com/16245250/33795882-46a564d6-dd1c-11e7-88a7-37ef89366897.png)
![image](https://user-images.githubusercontent.com/16245250/33795880-3ebfd2c4-dd1c-11e7-98c6-af3d0c63efaf.png)
