### ISSUE TITLE
Will release 2 hours ago? Busy.org's payout schedules are not correct

### ISSUE THREAD

**Issue by inoue-a** [busyorg/busy#1062]
A bug about Busy.org's payout schedules occured.
For example, look this screen shot.
![](https://s20.postimg.org/8tv792cjx/image1.png)
Busy says my payout will release 2 hours ago.
From this message, I can't know whether it is already paid or not paid yet.
Actually, it is not paid yet. It will be paid in 7 hours.
![](https://s20.postimg.org/7228e5lh9/image2.png)

The cause is obvious.
It occurred by PC's time zone.
This is my time zone.
![](https://s20.postimg.org/84cewnma5/image3.png)
(Sorry, my Windows' language setting is Japanese. But you can know the time zone is UTC+9)
It matches the difference in payment schedule between Busy and Steemit.

If I change the time zone to UTC, it will be correct.
![](https://s20.postimg.org/ayfka390t/image4.png)
![](https://s20.postimg.org/7228e6gcd/image5.png)

If I bring my PC to USA, it will be late.
![](https://s20.postimg.org/qwoa08ayl/image6.png)
![](https://s20.postimg.org/qwoa0anu5/image7.png)

These are my environment.
PC1:
OS: Windows 7 64bit
Web Browser: Google Chrome (62.0.3202.75) and Firefox (56.0.2)

PC2:
OS: Windows 10 64bit
Web Browser: Google Chrome (62.0.3202.75), Microsoft Edge 40.15063.674.0 and Firefox (56.0.2)

<br /><hr/><em>Open Source Contribution posted via <a href="https://utopian.io/utopian-io/@inoue/will-release-2-hours-ago-busy-org-s-payout-schedules-are-not-correct">Utopian.io</a></em><hr/>

**Comment by eastmaels** [comment]
I'll look into this.

**Comment by eastmaels** [comment]
This seems to be caused by the default call to `intl.formatRelative()` without explicitly providing value for the `now` option.

**Comment by jedau** [comment]
Hey guys. I just noticed that this issue persists.

![busy](https://user-images.githubusercontent.com/4092668/33764994-c3deb5cc-dc51-11e7-9759-549a9d6a4010.png)

![steemit](https://user-images.githubusercontent.com/4092668/33765000-c8750e56-dc51-11e7-81e1-c998383d6291.png)

You guys might want to revisit the fix for this. I opted to comment here instead of creating a new issue on Utopian, but let me know if you want to open a new issue for this instead.

cc: @eastmaels @Sekhmet

**Comment by espoem** [comment]
Did you see it on busy.org and/or staging.busy.org?

**Comment by jedau** [comment]
@espoem I saw it on busy.org

**Comment by Sekhmet** [comment]
It hasn't been published yet.

**Comment by jedau** [comment]
@Sekhmet oh alright. Thanks for the clarification.
