### ISSUE TITLE
[Busy.org] Improper Code Formatting Display

### ISSUE THREAD

**Issue by netuoso** [busyorg/busy#1067]
# [Busy.org] Improper Code Formatting Display

![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1510376908/uahnwbyen7twxmogukej.png)

---

## Issue
On Busy.org, there is an improper display of code formatted with the markdown code formatter. If a user inserts a code block in the body of their post, the preview of the post will never close the code block. However, when the post is actually submitted, the text is proper submitted and thus will display correctly.

## Solution
Ensure that there is a proper line break in the code preview of the editor when users insert code blocks in the body of their post.

## Screenshots
![Screen Shot 2017-11-10 at 11.05.12 PM.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1510376855/jtuhjjjelmssstokglcf.png)
![Screen Shot 2017-11-10 at 11.05.17 PM.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1510376855/xhvu6thhik3irvsxa8c5.png)
![Screen Shot 2017-11-10 at 11.04.58 PM.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1510376855/hidziuvcnx5djsjq0nfi.png)

<br /><hr/><em>Open Source Contribution posted via <a href="https://utopian.io/utopian-io/@netuoso/busy-org-improper-code-formatting-display">Utopian.io</a></em><hr/>

**Comment by Sekhmet** [comment]
This is not a bug, but problem with the way message is formatted.
