### ISSUE TITLE
Power down activity not translated

### ISSUE THREAD

**Issue by gregory-latinier** [busyorg/busy#1095]
An activity title and some other keys are not translated

#### Expected behavior

Well seeing translated content :)

#### Actual behavior
Some keys are not translated

![image](https://user-images.githubusercontent.com/13222767/33060449-8cdfeb34-ce98-11e7-9f5d-0ce17a8ca119.png)

#### How to reproduce

You can go to my profile to see a power down activity
https://busy.org/@gregory.latinier/activity

* Browser: 
* Operating system:

**Comment by jm90m** [comment]
There's lots of activities not yet parsed :), the table there is the default display for actions that are not parsed.

**Comment by jm90m** [comment]
For `fill_vesting_withdraw` it looks like steemd parses it out like this:
![screen shot 2017-11-22 at 12 03 37 pm](https://user-images.githubusercontent.com/5067716/33140142-1e438010-cf7d-11e7-955b-df021af13f44.png)

How should we parse it out and what text goes along with it @bonustrack  ?

**Comment by bonustrack** [comment]
@jm90m We can show `Start power down of 3,759.947 STEEM` similar than what steemit is doing:
![image](https://user-images.githubusercontent.com/16245250/33140293-1e8f69fc-cfe2-11e7-8b87-604b00170203.png)
