### ISSUE TITLE
Market sidebar block compact

### ISSUE THREAD

**Issue by bonustrack** [busyorg/busy#1102]
Can we have a more compact design for the market sidebar block, something like this would be enought:
![image](https://user-images.githubusercontent.com/16245250/33138771-e66e1a72-cfdd-11e7-8dc3-ccf1ccfd6ba7.png)
Now i feel it take too much space.

**Comment by jm90m** [comment]
the graph looks way too small, maybe @pareshUD can think of a better design

**Comment by jm90m** [comment]
@bonustrack we should get feedback on the community about this design imo, personally I like the big charts

**Comment by pareshUD** [comment]
For this I guess we are going with bigger charts.. We might change it later on not a priority I guess

**Comment by jm90m** [comment]
Did we finalize design on this?

**Comment by jm90m** [comment]
Design:

<img width="311" alt="screen shot 2017-12-18 at 2 34 10 pm" src="https://user-images.githubusercontent.com/5067716/34124349-93ebad82-e400-11e7-8dde-a85b6dbf692c.png">

![busy-market_sidebar](https://user-images.githubusercontent.com/5067716/34124355-9772b2d4-e400-11e7-909d-701109dcc027.png)

**Comment by bonustrack** [comment]
Please keep title `Market`, its not an analysis
