### ISSUE TITLE
Error in 'activity' tab on Busy.org

### ISSUE THREAD

**Issue by nolyoly** [busyorg/busy#1108]
On the 'activity' tab of profiles on busy.org there is an error with calculating Steem Power rewards. I think something might be off with where the decimal is placed?

Here's a screenshot of the error. (image 1) (image 1) 
![busy.PNG](https://res.cloudinary.com/hpiynhbhq/image/upload/v1511340486/xt6dlrzcoqe1sow8awxu.png)

Here;s the actual post reward: (image 2) (image 2)
![pic3.PNG](https://res.cloudinary.com/hpiynhbhq/image/upload/v1511445186/xfdd9lytyh2br1t8tnup.png)

Image 2 is the actual monetary value of the payout taken directly from the post in image one. As you can see it is only 10 cents. But, in image one it says I am rewarded 119 SP for that post which is highly highly inaccurate. That would mean the post would have had to have earn $90+ for a SP reward that large.

This error is duplicated by navigating to your profile and clicking the 'Activity' tab. Upon clicking the tab you can scroll down to any of the rewards or filter them out with the filter on the right sidebar. There you can see the incorrect payout figure for Steem Power. If you compare this to what is shown in your 'Wallet' tab for the exact same reward, the amount of Steem Power is completely incorrect and far, far higher than what the actual Steem Power payout actually was.

I spent like 10 minutes trying to figure out how I was receiving so much SP, then I looked at my wallet and realized it was a bug. :P

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@noly/error-in-activity-tab-on-busy-org">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by jm90m** [comment]
Hey, thanks for the reporting this issue. This was recently fixed in: https://github.com/busyorg/busy/pull/1103

When busy.org rebuilds from master the fix should be there :)

**Comment by jm90m** [comment]
Closing this, please let me know discord or comment on here if this issue still persists
