### ISSUE TITLE
Suggestion: Better arrangement of comments on mobile

### ISSUE THREAD

**Issue by espoem** [busyorg/busy#1113]
_Copied from Utopian._

<div>
<p>Today i will be writing on what i noticed about comments and replies under posts in busy.org on mobile.</p>
<p>I have been using busy.org for a while but i am not happy with the way comments are just jam packed with no indication to which comment a user is replying to.  This is making it untidy</p>
<h1>Lets Take A Look</h1>
<h2>Busy.org</h2>
<p><img src="https://steemitimages.com/0x0/https://res.cloudinary.com/hpiynhbhq/image/upload/v1511618362/sf6aurxgabbrhaen5wn8.jpg" alt="bug.jpeg"></p>
<p>Taking a look at the screenshot below, we will noticed that all the replies were on a straight line without a clear indication which each replies is meant for. The red demarcations are for replies under a direct comment to the post while the black demarcation shows responses to the replies under the direct comment to the post.</p>
<p>Compared to the screenshot below, we will notice that the whole thing was just jam packed. The image below shows spaces in the replies and better arrangement which will enable a user to know which comment a reply is for.</p>
<h1>Steemit.com</h1>
<p><img src="https://steemitimages.com/0x0/https://res.cloudinary.com/hpiynhbhq/image/upload/v1511618513/xyjee7gxm3xto8hrbqwi.jpg" alt="steemit 1.jpeg"></p>
<h1>Busy.org</h1>
<p><img src="https://steemitimages.com/0x0/https://res.cloudinary.com/hpiynhbhq/image/upload/v1511619001/lzbns0difeyiigilfyho.jpg" alt="steemit. 22.jpeg"></p>
<h1>Steemit.com</h1>
<p><img src="https://steemitimages.com/0x0/https://res.cloudinary.com/hpiynhbhq/image/upload/v1511619053/r3xi8gxl9tagt4ezjt4m.jpg" alt="bug 11.jpeg"></p>
<p>My suggestion is that the programmers should leave spaces in between the replies like that of steemit.com or they can have a phrase like "replying to" on each replies.</p>
<p>That is my suggestion. Thanks for reading.</p>
<p>All screenshots were taking with my infinix hot 4.</p>
<p>I accessed the site using my dell laptop which runs on windows</p>
<p><br></p><hr><em>Posted on <a href="https://utopian.io/utopian-io/@ewuoso/a-call-for-better-arrangement-of-comments-and-replies-under-posts-on-busy-org-mobile" target="_blank" rel="nofollow noopener">Utopian.io -  Rewarding Open Source Contributors</a></em><hr><p></p></div>

**Comment by Sekhmet** [comment]
We can't just shift nested comments more and more. At some point we have to stop, or the replies will have 10% of the width of the screen.
