### ISSUE TITLE
Can't edit any posts in Chrome

### ISSUE THREAD

**Issue by nolyoly** [busyorg/busy#1117]
I've come across a bug when trying to edit posts. When clicking the edit post button, I get the loading/spinning circle icon. It then it stops and returns to the normal edit icon and nothing happens. The edit post box does not appear anywhere. This is happening on any post or comment I try to edit.

I'm using the Google Chrome 62 on Windows 7. I seem to be having the same problem in Firefox as well.
![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1511647370/qcui8aryttezn7l2b3te.png)

Here is a screenshot of the spinning wheel. After it stops nothing happens. The edit boxes do not appear no matter how many times the edit button is clicked. Hopefully this gets fixed soon as it's quite an annoyance having to bounce over to Steemit just to edit a post. Other than that, I love everything Busy is doing (would like to see new follower notifications added to the activity tab though! ;)).

![busy3.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1511647228/aily4uuc7njpcloo7nfi.png)

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@noly/can-t-edit-any-posts-in-chrome">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by Sekhmet** [comment]
Does it still happen?
