### ISSUE TITLE
Page Breaks in Edge Browser within Post View when Scrolling to Comments on Busy.org

### ISSUE THREAD

**Issue by therealFlauwy** [busyorg/busy#1119]
![busy-bug-cover.jpg](https://steemitimages.com/DQmbQRZGZ4yrGMx3H4LB2mNfEvQADsvsQyUJ2D3d3hQVwUN/busy-bug-cover.jpg)

When using the Microsoft Edge browser for Busy.org 2.0 the comment section doesn't load. As soon as the user scrolls down to it the page breaks and turns white. Only a refresh brings the page back.

It happened in all my attempts. For better clarity I have made a video to demonstrate the bug:

<hr>
https://youtu.be/6gHfZD-apDY
<hr>

<br>

Browser: Microsoft Edge
Browser Plugins: Last Pass
OS: Windows 10
Device: MSI GT62VR 7RE Dominator Pro

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@flauwy/page-breaks-in-edge-browser-within-post-view-when-scrolling-to-comments-on-busy-org">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by Sekhmet** [comment]
FF52 also affected.
