### ISSUE TITLE
Allow user to write a quick post directly from feed

### ISSUE THREAD

**Issue by bonustrack** [busyorg/busy#1129]
There should be a way for user to write a quick post directly from the feed. In a similar way than what Facebook or Twitter is doing. See the mockup:
https://projects.invisionapp.com/d/main#/console/12110024/265356888/preview
https://projects.invisionapp.com/d/main#/console/12110024/265356887/preview
https://projects.invisionapp.com/d/main#/console/12110024/265356886/preview

**Comment by bonustrack** [comment]
The input have 2 state, when we open the page it's compact like this:
![image](https://user-images.githubusercontent.com/16245250/33392883-eaa78cee-d56f-11e7-9b30-a4451b5dfe1e.png)
When the input is on focus we should show a bigger form like this:
![image](https://user-images.githubusercontent.com/16245250/33392910-03020ce2-d570-11e7-80c4-98a832537609.png)

If user stay in `/trending/photography` page the tag by default should be `photography`. If the user stay in trending page we can use the tag busy. The post dont need title.

**Comment by jm90m** [comment]
@bonustrack those links are not visible to public, I am hit with a login page

**Comment by jm90m** [comment]
![screen shot 2017-11-30 at 10 44 12 am](https://user-images.githubusercontent.com/5067716/33439451-73b6c9a0-d5bb-11e7-8efd-a080a0dfdd1d.png)
