### ISSUE TITLE
Default avatar doesn't show when there is a problem with the avatar loading on the staging version

### ISSUE THREAD

**Issue by espoem** [busyorg/busy#1136]
#### Expected behavior

If there is an issue with loading the users' avatars, the default avatar should be used.

#### Actual behavior

On staging version (staging.busy.org) the default avatar may not load and then the user sees a duplicity in the username.

![image](https://user-images.githubusercontent.com/16621517/33433704-e9da7962-d5dc-11e7-9386-eadaa1685dee.png)

Two posts were loaded "at the same time" but in one of them the avatar loaded and in the other, it did not.

![image](https://user-images.githubusercontent.com/16621517/33433680-d407e412-d5dc-11e7-8ee0-e8415accd0cb.png)

#### How to reproduce

1. not really sure. wait for the avatar load failure

* Browser: Chrome
* Operating system: Windows 10

**Comment by bonustrack** [comment]
It might be related to recent changes with server side rendering. @Sekhmet may want to look into this.

**Comment by jm90m** [comment]
Weird, for me its working fine when avatar is down... 

![screen shot 2017-11-30 at 2 54 30 pm](https://user-images.githubusercontent.com/5067716/33451904-6c12daea-d5de-11e7-8e46-4135fab6e808.png)
