### ISSUE TITLE
Follow button error on profile 'most reblogged' sidebar.

### ISSUE THREAD

**Issue by nolyoly** [busyorg/busy#1145]
Today I noticed an error with the sidebar when viewing your own profile. The sidebar that says 'Most Reblogged' is displaying the 'Follow' button on users I am already following.

Below is an attached screenshot. All of these should say 'Following' instead of 'Follow'
![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1512103920/tdszxmk5tbf4zmmt97ar.png)

The browser I'm using is Chromium 62 on Windows 7. I have not been able to test if this is happening in any other browsers.

I love Busy and will continue to report any bugs I find, major or not, as they all will help improve the platform!

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@noly/follow-button-error-on-profile-most-reblogged-sidebar">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by espoem** [comment]
I can confirm it.

**Comment by jm90m** [comment]
hmm.... not too sure what happened with this but I'll take a look at it next week probably, thanks for reporting it.

**Comment by jm90m** [comment]
Looks like this issue is happening throughout the entire app where the `Follow` button is used....

**Comment by Sekhmet** [comment]
Fixed in #1168.
It should work properly on busy.org.
