### ISSUE TITLE
Implement AMP

### ISSUE THREAD

**Issue by bonustrack** [busyorg/busy#1146]
Can we implement AMP? https://www.ampproject.org/ That should improve our Google ranking

**Comment by Sekhmet** [comment]
@bonustrack do we have idea how should AMP page should look like? I guess we only want AMP for single posts, right?

**Comment by bonustrack** [comment]
@Sekhmet we want it for single post yes, and i'm not sure how it should look like. Do we have that much choice about how it look like? Isn't just information to fill similar than `og:` metadata?

**Comment by Sekhmet** [comment]
I't pretty flexible. You have to build new website in AMP-flavoured HTML. I would keep it as simple as possible though, I don't think we should build another Busy version just for AMP.

**Comment by bonustrack** [comment]
Ok yes i see, agree we need something simple just to get post better indexed.
