### ISSUE TITLE
Drafts page lifting: add last update time, remove "this draft" from "Delete this draft button, align button to right

### ISSUE THREAD

**Issue by jm90m** [busyorg/busy#1150]
Update Draft Page UI based on Paresh's design

**Comment by pareshUD** [comment]
@jm90m please check the draft design

![drafts](https://user-images.githubusercontent.com/8911074/33708789-6df0ad5a-db61-11e7-89e7-6ae4fe6ae3ae.png)

**Comment by jm90m** [comment]
@pareshUD there's a PR open with draft design - you can review it there and give feedback -
 https://github.com/busyorg/busy/commit/d9943c980b56ac872a71437dc3352305c472f02f
