### ISSUE TITLE
Add Quick Create Post Error

### ISSUE THREAD

**Issue by Kennybll** [busyorg/busy#1153]
#### Expected behavior
Post without photos.

#### Actual behavior
When I try to post with no photos using the add-quick-create-post it says "124 on_message" on an error notification.

#### How to reproduce
Don't provide a photo.

Notes: While debugging I found out it is be if there is no photo, then it won't post, because there is no post body. Steem doesn't allow the body to be empty apparently. You might want to duplicate the title to the body then the photos. Or add a separate input for the title.

* Browser: Chrome x64
* Operating system: Windows 10 Latest.

**Comment by jm90m** [comment]
thanks for reporting this issue, will get it to it asap 👍
