### ISSUE TITLE
Follow buttons on profile not working.

### ISSUE THREAD

**Issue by nolyoly** [busyorg/busy#1167]
I've come across an error when trying to follow users through Busy. After clicking follow, the button changes to 'Following' as if the action worked.
![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1512688401/jk28hnjee1bjkb6v775t.png)
However, after reloading the page, the 'Follow' button comes back and the number of users following hasnt increased or decreased either. Here is a screenshot immediately after refreshing.
![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1512688473/zrg2see0xozkx5fskb0n.png)

This also seems to be happening with all other follow buttons throughout the website such as in the 'Top Reblogged Users' section.

Not sure what is causing this but it seems like a pretty major bug as following users is a pretty essential feature.

Also, I am experiencing this error in Chromium 62 browser. I have not had the opportunity to test this bug in any other browsers.

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@noly/follow-buttons-on-profile-not-working">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by Sekhmet** [comment]
Fixed in #1168.
