### ISSUE TITLE
Migration to new image provider

### ISSUE THREAD

**Issue by Sekhmet** [busyorg/busy#1169]
As we are changing the way we handle avatars/cover images we need make few changes on front-end to make it a seamless transition.

### `busy-img` changes:
- We no longer have capabilities to transform images. We should crop and scale images client-side.
- We only have two different sizes of images (128x128 and 64x64). `width` and `height` is still respected, but its capabilities are very limited - if one of them is below or equal to 64 it has the same effect as setting `small` flag.
- We no longer provide cover image through image provider.

### Changes we have to make on client:
- [x] Make `Avatar` use div with background image instead of `img` tag.
- [x] Use `cover_image` link directly from jsonMetadata.

### Decisions:
- How do we handle avatar lightbox? We have 128x128 avatars at most. Lightbox might not be very useful with them. Do we remove lightbox? Use `profile_image` from JSON metadata? (this is dead link ~30% of the time).
- More?

**Comment by jm90m** [comment]
I kinda like the avatar lightbox, I think we should keep it, if its at most 128 x 128 avatar then that should be fine, at least they get a bigger picture
