### ISSUE TITLE
[discussion] Replace Post Modals with Post Pages

### ISSUE THREAD

**Issue by yamadapc** [busyorg/busy#117]
Currently clicking a link on the feed brings up a component that looks exactly like a page but is rendered in a different manner. It also shares the URL with a page, though it has a different view.

I think it'd be better to have a post page, instead of a post modal that covers the screen and a post page that looks the same but is different.

**Comment by p0o** [comment]
I would like to mention that both of the pages (the one with modal and the one with direct link) which as @yamadapc correctly said are rendered with different manners, however they share the same container to handle the data and use the same component to render the content. So there is no actual code duplication for this.

We can have post pages like before and after user's getting back restore the scroll to the previous location which is very similar to Medium.com. But IMHO if you check the Medium it creates a delay while navigating to posts and getting back to timeline which we don't have it in Busy right now.

**Comment by adcpm** [comment]
Can we use browserHistory.goBack instead of Modal? I've tried and its work fine, keeping content and scrollbar state, this way we dont have to deal with Link and css issues.
