### ISSUE TITLE
Wallet history is not updated after a transfer

### ISSUE THREAD

**Issue by espoem** [busyorg/busy#1174]
I am using staging.busy.org as there is the most recent version of the Busy platform. Users can transfer their funds and they are redirected to steemconnect to do so. After the transfer was successfully done, the wallet history remains the same as it was before the transfer. It may seem that the money was not sent. The user will see the difference when they reload the page.

![wallet-transfer.gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1512758320/gf6ahhvqhymshibt4exs.gif)

## Expected behaviour

The history in wallet should be updated with the latest transfer without the need of page reloading. We can see the same action when we claim rewards.

## Steps to reproduce

1. Send money with busy (staging.busy.org)
2. After the transfer is successful, see the wallet
3. Reload the page and you will see the transfer in the history

- Browser: Chrome
- Operating system: Windows 10

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@espoem/wallet-history-is-not-updated-after-a-transfer">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by jm90m** [comment]
looks like even Coinbase.com has this issue and they are a way bigger company than us lols :), I don't see my transfer history automatically update, need to refresh on their site hahaha, but i guess we can fix it on here sometime

**Comment by Sekhmet** [comment]
Activity API is refreshed every 2-3 minute, so we can't do this as of now.
