### ISSUE TITLE
"min read" on write post page

### ISSUE THREAD

**Issue by sweever** [busyorg/busy#1175]
### Actual behavior

min read on write page .
![2017-12-09_180028](https://user-images.githubusercontent.com/18384831/33798237-d7f03cdc-dd0c-11e7-8a5d-7543e7e20684.png)

### How to reproduce

it should be not apear there.
it would be better to keep only word counter .

* Browser: chrome
* Operating system: win7

**Comment by Sekhmet** [comment]
Why it shouldn't be there?

**Comment by sweever** [comment]
useless ...

**Comment by Sekhmet** [comment]
You can't say something is useless because you don't need it.
It was requested by users: #862

**Comment by sweever** [comment]
sry , but by what it can help you in writing page ?
