### ISSUE TITLE
No Chinese displayed even have the language set

### ISSUE THREAD

**Issue by jia-dai** [busyorg/busy#1181]
Some days ago I could not see Chinese on busy.org but English only. I tried to switch language for several times but nothing helped.
![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1512973475/lqfd37uobhvakshghzfm.png)

The only Chinese I can find is at the Pending Payout.
![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1512974403/uvckok82dshqgaxsdty0.png)

I think there's some mistake on multi-language translation file, maybe wrong file merged to master branch.

### Steps to reproduce
1. Login into Busy.org
2. Go to `Settings`
3. Select Simplified Chinese from Language (if it is Chinese now you may need to switch it), and click `Save`

Browser: Chrome 62 / Edge
OS: Window 10 64bit

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@daijia/no-chinese-displayed-even-have-the-language-set">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by bonustrack** [comment]
This issue has been fixed in #1182
