### ISSUE TITLE
Wallet history block with double border

### ISSUE THREAD

**Issue by bonustrack** [busyorg/busy#1190]
The block on wallet history has double borders, it should not be the case
Try here: https://staging.busy.org/@fabien/transfers
![image](https://user-images.githubusercontent.com/16245250/33907240-14713c7c-dfb7-11e7-81e4-a013431aa722.png)

**Comment by jm90m** [comment]
Oh yeah I also fixed this in https://github.com/busyorg/busy/pull/1189

re-open if you still see this issue :)
