### ISSUE TITLE
Default avatar color is wrong on busy-img

### ISSUE THREAD

**Issue by bonustrack** [busyorg/busy#1191]
For users not having avatar there is a colored default avatar. It seem that since the recent change the default color depend on the first letter of the username, while it should depend on the full username. Having a different color help user to not confuse `blocktrades` with wrong spelling username like `blocktarde`
![image](https://user-images.githubusercontent.com/16245250/33946501-90d1f32c-e054-11e7-85ac-c8718e13e69b.png)
![image](https://user-images.githubusercontent.com/16245250/33946926-a5dff830-e055-11e7-907a-3feb38cf149a.png)

**Comment by Sekhmet** [comment]
![image](https://user-images.githubusercontent.com/1968722/33963131-2d03384c-e054-11e7-9619-77396c151bad.png)
Should be good now.

**Comment by bonustrack** [comment]
Indeed problem solved, closing this issue.
