### ISSUE TITLE
Usage of Busy on mobile became cumbersome with new items in dropdown menu

### ISSUE THREAD

**Issue by espoem** [busyorg/busy#1193]
#### Expected behavior

Either close the menu after clicking an item or make the menu smaller and scrollable.

#### Actual behavior

New items were added to the menu but it also means that it is more difficult to close the menu because it persists open after clicking a menu item. The only way to close it without any issues is to click on the top bar to dismiss the menu.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/16621517/33949615-692560b8-e02a-11e7-9127-7baac759a082.gif)

#### How to reproduce

1. staging.busy.org
2. open a dropdown menu

* Browser: Brave
* Operating system: Android

**Comment by jm90m** [comment]
Thanks for the feedback, will update this menu to have a fixed height, since I guess not all users have long mobile phone screens

**Comment by jm90m** [comment]
What phone is this @espoem ? I tried it on my iphone 5S and that is a super small screen...

**Comment by jm90m** [comment]
removing this from this release, will look into this more at a later time once we update it / have more time, but this seems like a really rare edge case, since my iphone 5S which has a small screen renders it fine

**Comment by espoem** [comment]
I forgot to include the device spec.
I have Moto G3 2015, 720x1280, Android 7.1.2, Brave browser

**Comment by jm90m** [comment]
thanks @espoem 👍

**Comment by Sekhmet** [comment]
We can make it work this way:
1. Set max-height of PopoverMenu to 50-60% of viewport height.
2. Make PopoverMenu scrollable vertically (only if needed).
