### ISSUE TITLE
Upload image (paste from clipboard), when editing a posted comments, isn't working

### ISSUE THREAD

**Issue by mynameisek** [busyorg/busy#1194]
#### Expected behavior

Paste image on a comment edition. Show [!image] but nothing more, doesnt work.
When paste image in the initial comment box instead of the editing comments, it will work instantaneously and display the imageurl cloudinary

#### How to reproduce
Edit a comment, paste image.

**Comment by Sekhmet** [comment]
I couldn't reproduce, can you give some more context (operating system, browser, video that ideally shows console)?
I found another issue though, that if you paste image into edit comment textbox `Uploading image` message won't go away.
