### ISSUE TITLE
Code Splitting React Intl Locales

### ISSUE THREAD

**Issue by Kennybll** [busyorg/busy#1197]
#### Expected behavior
We should split the react-intl locales to make the bundle smaller. I figure to use webpacks dynamic inport(). This will load it separately. I tried this and it saves around 400k.

#### Actual behavior
Bundles all translations to the main bundles.

#### How to reproduce
[https://busy.org/js/statistics.html](https://busy.org/js/statistics.html) shows translations take up 37.6%.

I started to work on it. I am about to add a pull request. Just thought to add it here first. I am willing to be assigned.

* Browser: 
* Operating system:

**Comment by Kennybll** [comment]
You can check out my webpack visualizer with example code splitting sizes: [https://kennybll.herokuapp.com/js/statistics.html](https://kennybll.herokuapp.com/js/statistics.html). It may need to reload heroku's server ( I have free service not paid ).

**Comment by bonustrack** [comment]
https://kennybll.herokuapp.com/js/statistics.html is bigger than thanhttps://staging.busy.org/js/statistics.html for me

**Comment by Kennybll** [comment]
vendor and main are smaller though. Also for some reason I count 51 locales in src on the kennybll vs 40 on staging.

**Comment by Kennybll** [comment]
I found out why... if you look under src/client/translations/index.js you see no one ever added the extra locals from /src/client/locales. @bonustrack
