### ISSUE TITLE
Update For All Translations

### ISSUE THREAD

**Issue by Kennybll** [busyorg/busy#1198]
#### Expected behavior
We have 51 translation files under [/src/client/locales/*.json](https://github.com/busyorg/busy/tree/master/src/client/locales). But on [Settings.js](https://github.com/busyorg/busy/blob/master/src/client/settings/Settings.js) and [translations/index.js](https://github.com/busyorg/busy/blob/master/src/client/translations/index.js) there is support for  40 of the translation files.

#### Actual behavior
We should have support for all 51 files.

#### How to reproduce
Look at the links above, and count.

* Browser: Chrome
* Operating system: Windows 10

**Comment by Sekhmet** [comment]
I don't think we should enable incomplete translations. Seeing only 40% of page translated would be annoying.

**Comment by Sekhmet** [comment]
We will only make complete (usable) translations available to users.
