### ISSUE TITLE
Wrong avatar on quick post form

### ISSUE THREAD

**Issue by bonustrack** [busyorg/busy#1210]
When i open https://staging.busy.org logged with my account `fabien`, the avatar on quickpost form is wrong:
![image](https://user-images.githubusercontent.com/16245250/34081846-a77e442e-e386-11e7-981c-4df64323d16c.png)

**Comment by bonustrack** [comment]
For some reason, i'm not able to reproduce this issue anymore.

**Comment by bonustrack** [comment]
Can you @jm90m @Sekhmet ?

**Comment by Sekhmet** [comment]
I've never seen this issue.

**Comment by jm90m** [comment]
I don't see this issue..
![screen shot 2017-12-18 at 10 15 10 am](https://user-images.githubusercontent.com/5067716/34113016-59ce1b4a-e3dc-11e7-8587-8ca8f40b5bd1.png)


can we close this?

**Comment by jm90m** [comment]
can we close this @bonustrack ?

**Comment by espoem** [comment]
@bonustrack @jm90m happened today (staging.busy.org)
![image](https://user-images.githubusercontent.com/16621517/34394962-7349ee18-eb5d-11e7-8237-cd89e81da303.png)
