### ISSUE TITLE
Follow Topics

### ISSUE THREAD

**Issue by pareshUD** [busyorg/busy#1212]
Simply click on the topic you want to follow. After you follow particular topics you will see the post from the topics you followed in your feed.

#### Expected behavior

- Explore the topics on left sidebar
- Simply hover to follow them
- After you follow the topic your feed will be populated and you only be able to see the post 

![followtopic 2x](https://user-images.githubusercontent.com/8911074/34095653-431850de-e3f8-11e7-871e-4fde646fe729.png)
![topic hover 2x](https://user-images.githubusercontent.com/8911074/34095654-4354e5a8-e3f8-11e7-81c2-bd1bcee25401.png)
![topic followed 2x](https://user-images.githubusercontent.com/8911074/34095655-438f6b10-e3f8-11e7-97d3-f3418c8780af.png)

**Comment by Sekhmet** [comment]
Moved to #1332
