### ISSUE TITLE
Avatar is not loading

### ISSUE THREAD

**Issue by bonustrack** [busyorg/busy#1214]
This avatar fail to load:
http://img.busy.org/@johurulbot

The original image is https://scontent.fdac3-1.fna.fbcdn.net/v/t1.0-0/p206x206/10262275_506829752761083_8537410738252795849_n.jpg?_nc_eui2=v1%3AAeHhPvYceQG4Dp61qcJ1h5yd6ASDrDjf-GR8dcmojxDLDuN-aE5xKPPNLoCE1h-p-GNm5aSDo4R_qXlhoW7aKx-C-gNWOVHfkIb-u8KImZ2P-w&oh=40f7cea3024bf63ac89045c7464cb5fa&oe=5A6CEF00 and loading fine.

**Comment by Sekhmet** [comment]
Isn't it related to the max length of URL on cloudinary?

**Comment by Sekhmet** [comment]
Looks like it might be problem with image URL length:
https://support.cloudinary.com/hc/en-us/articles/207746165-Why-do-I-get-a-public-ID-too-long-error-when-trying-to-fetch-from-a-remote-URL-
as this image URL is 280 characters long (which is above 256 characters limit from Cloudinary).

**Comment by bonustrack** [comment]
Yes there is a limitation for URL lenght. That must be the issue.

**Comment by Sekhmet** [comment]
@bonustrack I have added Google URL Shortener for cases of images longer than 256 characters. I don't think there is much more we can do about it.

**Comment by bonustrack** [comment]
Cool working fine now, i'm closing this issue.
