### ISSUE TITLE
Improve invite page design

### ISSUE THREAD

**Issue by bonustrack** [busyorg/busy#1216]

**Comment by pareshUD** [comment]
@bonustrack Please check the attached design with updated illustration
![invite people](https://user-images.githubusercontent.com/8911074/34564802-3abe96da-f17e-11e7-80b0-b6a228a3597f.png)

**Comment by jm90m** [comment]
@bonustrack do you approve of this design?

**Comment by bonustrack** [comment]
Yes @jm90m
