### ISSUE TITLE
Estimate account value is wrong

### ISSUE THREAD

**Issue by bonustrack** [busyorg/busy#1218]
Based on the Steem price of 3.13$ with 1089 SP i should see an estimation of 1089 x 3.13 = 3408$ but i see 2498$ instead:
![image](https://user-images.githubusercontent.com/16245250/34168417-0e391e96-e517-11e7-9723-4c8d18b85e72.png)

**Comment by jm90m** [comment]
Is this not the formula? `https://github.com/busyorg/busy/blob/master/src/client/vendor/steemitHelpers.js#L201`

**Comment by jm90m** [comment]
```
  const steemPower = formatter.vestToSteem(
    user.vesting_shares,
    totalVestingShares,
    totalVestingFundSteem,
  );
  return parseFloat(steemRate) * (parseFloat(user.balance) + parseFloat(steemPower)) +
    parseFloat(user.sbd_balance);
```

**Comment by bonustrack** [comment]
Formula looks good but obviously something is wrong on the result in the UI. How do you get the rate?

**Comment by jm90m** [comment]
from here:

```
export const getRate = () => (dispatch) => {
  dispatch({ type: RATE_REQUEST });
  fetch('https://api.coinmarketcap.com/v1/ticker/steem/').then(res => res.json()).then((json) => {
    const rate = parseFloat(json[0].price_usd);
    dispatch({
      type: RATE_SUCCESS,
      rate,
    });
  });
};
```

So https://api.coinmarketcap.com/v1/ticker/steem/

But looks like its kind of on the same rate as the same API that we use for the charts.
