### ISSUE TITLE
Post reloads after upvoting

### ISSUE THREAD

**Issue by espoem** [busyorg/busy#1222]
#### Expected behavior

No visible action with the post except the stats change should occur.

![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/16621517/34216476-c2ee1ee0-e5a8-11e7-8d14-e75d5e0e57c7.gif)

The gif is from the stable version.

#### Actual behavior

The post reloads if a user upvotes a post.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/16621517/34216525-e01f97c8-e5a8-11e7-9737-fb265a4f0ff6.gif)

#### How to reproduce

1. Open a post on staging.busy.org
2. Upvote the post

* Browser: Chrome
* Operating system: Windows 10

**Comment by bonustrack** [comment]
This issue still occur, we will need a hotfix for it.

**Comment by Sekhmet** [comment]
Patch.

```patch
diff --git a/src/client/post/postsReducer.js b/src/client/post/postsReducer.js
index 9a911c2..fac05d9 100644
--- a/src/client/post/postsReducer.js
+++ b/src/client/post/postsReducer.js
@@ -81,6 +81,7 @@ const posts = (state = initialState, action) => {
       };
     }
     case postsActions.GET_CONTENT.START:
+      if (action.meta.afterLike) return state;
       return {
         ...state,
         postsStates: {

```
