### ISSUE TITLE
Add image preview on recommended posts

### ISSUE THREAD

**Issue by bonustrack** [busyorg/busy#1252]
It would be nice to have an image preview on the block "Suggested posts"
![image](https://user-images.githubusercontent.com/16245250/34329026-a11c4fe8-e923-11e7-85c0-128a4070aed0.png)
Can you work on a design for it @pareshUD ?

**Comment by pareshUD** [comment]
@bonustrack Check this out

![recommended posts 2 2x](https://user-images.githubusercontent.com/8911074/34569370-94cd08e0-f18e-11e7-8d75-6f8ea795e8f9.png)
![recommended posts 3 2x copy](https://user-images.githubusercontent.com/8911074/34569371-950ab172-f18e-11e7-8221-c049f965c43a.png)
![Uploading Recommended Posts@2x.png…]()

**Comment by pareshUD** [comment]
Final design for recommended post

![recommended posts 2 2x](https://user-images.githubusercontent.com/8911074/34662776-17d86576-f479-11e7-8e4a-54a6eab7abf1.png)

**Comment by jm90m** [comment]
@bonustrack do you approve of design of this? Should we move this v2.3 milestone?

**Comment by bonustrack** [comment]
Yes @jm90m
