### ISSUE TITLE
Sidebar right block "Let's get started"

### ISSUE THREAD

**Issue by bonustrack** [busyorg/busy#1254]
We should remove the right sidebar block "Never wrote a post? Start Now" and replace it with a list to complete with these steps:
![image](https://user-images.githubusercontent.com/16245250/34329108-840ac6e4-e925-11e7-9211-5bc357e42d59.png)

**Comment by Sekhmet** [comment]
How can we fetch data to check those boxes?
We are already fetching following list, so it's not a problem. How do we find out if user upvoted 5 posts? We  have `lifetime_vote_count` but it's always 0. We have `last_vote_time` but we can find out how many votes user made, only if he did or he did not.
About wiring first post - we have `post_count`, but it includes both posts and comments.
Making 3 requests to load only that doesn't make too much sense to me.

**Comment by bonustrack** [comment]
- For "Writing your first post" we can use `last_root_post`, we are already using it to show the sidebar block "Never wrote a post?"
- For "Upvote 5 more good posts" we can change it to "Upvote some good posts" and use `last_vote_time` to detect if user ever did a vote.

**Comment by bonustrack** [comment]
This is how it's done in hackster.io
![image](https://user-images.githubusercontent.com/16245250/34719316-eeafd87e-f56c-11e7-9425-2a1ae2dad347.png)
Wait for @pareshUD to come out with a design before doing an integration.

**Comment by pareshUD** [comment]
@bonustrack @jm90m Here is the design for profile progress.

![profile progress mobile](https://user-images.githubusercontent.com/8911074/34761186-bb6d832a-f608-11e7-8678-4317af7ae447.png)
![steps completed](https://user-images.githubusercontent.com/8911074/34761187-bba71ae0-f608-11e7-9f53-bd6f8a73476d.png)

**Comment by pareshUD** [comment]
![steps completed 2](https://user-images.githubusercontent.com/8911074/34764128-79acdcdc-f613-11e7-92e9-47820d704144.png)

**Comment by pareshUD** [comment]
Not sure if this is something we can do please let me know

![steps 2](https://user-images.githubusercontent.com/8911074/34764821-b61ce408-f615-11e7-995e-34a3b570b78d.png)
![steps 3](https://user-images.githubusercontent.com/8911074/34764822-b65a10b2-f615-11e7-9e37-07efa767c972.png)

**Comment by bonustrack** [comment]
Some comments:
- We should always use this case for title and texts: "Hello world" not "Hello World"
- The 4 onboarding steps is not just about setting your profile, the title is misleading. I would change "You are 80% completed setting up your profile" to "Let's get started"
- I'm not fan of giving possibility for user to upvote or follow user within the onboarding block. We want user to learn how to upvote content and follow within the normal layout.

**Comment by pareshUD** [comment]
@bonustrack  Aren't we suppose to guide them how much they completed in terms of the progress of the profile how "Let's get started" will tell them what they needs to do and whats the progress?

Regarding Last point I just tried a option where it become user for follow fellow stemians.. Else they to go follow people and then again come to this block.. I think that can help in terms of we want people to get started quickly.. Let me know your thought.

**Comment by pareshUD** [comment]
<img width="374" alt="screen shot 2018-01-10 at 6 35 28 pm" src="https://user-images.githubusercontent.com/8911074/34774535-b90ff694-f635-11e7-9249-037bb65bf283.png">

I think its looks more playful when we have Progress bar and percentage and its more interactive.

**Comment by pareshUD** [comment]
![steps completed v3](https://user-images.githubusercontent.com/8911074/34775699-185d06e2-f63a-11e7-8f7a-9349ddfe1299.png)
