### ISSUE TITLE
Fix AMP issues

### ISSUE THREAD

**Issue by bonustrack** [busyorg/busy#1257]
Webmaster Tools detected a large % of issues on AMP:
![image](https://user-images.githubusercontent.com/16245250/34341027-9cefdec8-e9c1-11e7-8334-1ebb4f48704e.png)

I try to open few issues and see the detail, all issues are same, the problem is that `<iframe>` is not allowed:
![image](https://user-images.githubusercontent.com/16245250/34341033-aef630d6-e9c1-11e7-9a77-97d0c38c096e.png)

For the issues not critical it's always this:
![image](https://user-images.githubusercontent.com/16245250/34341231-b2c090e0-e9c5-11e7-921e-d30cd723bb7d.png)

**Comment by Sekhmet** [comment]
IIRC this always worked this way for non-amp pages, PR deployment was detected properly, and Google cached AMP there:
![image](https://user-images.githubusercontent.com/1968722/34362386-5488656c-ea73-11e7-9dd7-f2809d90e58f.png)

I think that it's using this as placeholder until it will be fetched by Google properly (same as with publisher information).
