### ISSUE TITLE
Busy.org Bug: Previous Page Jumping Issue

### ISSUE THREAD

**Issue by therealFlauwy** [busyorg/busy#1260]
https://steemitimages.com/0x0/https://res.cloudinary.com/hpiynhbhq/image/upload/v1512514647/d2h2xi86qzqdwsuubfgp.gif

This is a bug report for Busy.org. It covers an issue with the __previous page__ function of the browser. The same bug appeared on Utopian.io (Busy fork) but was fixed with a recent update. 

## Issue
<hr>

When browsing through a category or trending/hot page and then clicking on a post to read it one of the common things to do afterwards is to return to the previous page via the according browser function. However, on Busy.org it seems to lock to a certain post and disregards the previous position within that list of posts. You can see a quick jump happening where the browser jumps away from the correct one to the one that is locked. 

For better understanding I made a video about that behaviour. As you can see it doesn't happen after the first post but after the second as it seems. I was able to reproduce that exact behaviour a few times.

https://youtu.be/wWishEAuht0

For comparison you can try the same on Utopian.io and see that it returns there to the correct post in the list. 

_This was tested on a Windows 10 PC with Firefox 57.0.2_

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@flauwy/busy-org-bug-previous-page-jumping-issue">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by Sekhmet** [comment]
I could reproduce this issue on FF, but it doesn't seem to be a problem on Chrome.
I'm not sure what is causing this problem, because we rely on browser behaviour for this.
Any ideas @jm90m?

**Comment by jm90m** [comment]
I am not too sure @Sekhmet but I will try to look into it, might be some react router navigation issue, or some CSS styling, I can try to look into it

**Comment by jm90m** [comment]
Is this still an issue, I can't reproduce this on Chrome and FF @bonustrack @Sekhmet ?

**Comment by bonustrack** [comment]
I can reproduce it on Firefox, on Chrome it's working but i see another page for few milisecond.

**Comment by jm90m** [comment]
@bonustrack I think you see another page because it is trying to take you back to where you were in the feed infinite scroll, so it loads all others before it, depending on how far down you go, the page actually jumps multiple times until it gets to the post when on Chrome
