### ISSUE TITLE
A comment can't be edited if it was voted

### ISSUE THREAD

**Issue by espoem** [busyorg/busy#1262]
#### Expected behavior

The user should be able to edit their comments even though the comment has been already voted. It was possible before and there is no issue on Steemit.

#### Actual behavior

If the comment has been voted, it can't be edited. An error pops up saying that it needs to have zero rshares.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/16621517/34356366-4c484e2a-ea3d-11e7-80d7-9f424789c6dd.gif)

![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/16621517/34356373-62a44c96-ea3d-11e7-8873-970a744f01d9.gif)

#### How to reproduce

1. Write a comment (busy.org or staging.busy.org)
2. Upvote it
3. Edit it and submit

* Browser: Chrome
* Operating system: Windows 10

**Comment by bonustrack** [comment]
It may be related with disabled curation rewards.
