### ISSUE TITLE
Add hreflang on meta

### ISSUE THREAD

**Issue by Sekhmet** [busyorg/busy#1274]

**Comment by Sekhmet** [comment]
@bonustrack how we should do that?
Just `<link rel="alternate" hreflang="x-default" href="http://www.example.com/" />` that links to itself?

**Comment by bonustrack** [comment]
I wonder how `hreflang` make sense if we dont have subdomain or the language specified on the url. It seem the only thing we can do without a subdomain is adding `x-default`, not sure if that will have any impact on our SEO.

**Comment by bonustrack** [comment]
Does it worth to create subdomains for each locale?

**Comment by Sekhmet** [comment]
Should we add this or can it be closed?
