### ISSUE TITLE
Double border on activity row

### ISSUE THREAD

**Issue by bonustrack** [busyorg/busy#1289]
There is a double border on activity row see: 
![image](https://user-images.githubusercontent.com/16245250/34468041-5720150e-ef32-11e7-9c3b-5fb749410d4a.png)
https://busy.org/@sekhmet/activity

**Comment by sweever** [comment]
it should be one class to all of them + another one for **type** of activity

``<div class="UserActivity Action">…</div>``
``<div class="UserActivity transaction">…</div>``
