### ISSUE TITLE
Post PopoverMenu overflow at NavigationBar

### ISSUE THREAD

**Issue by sweever** [busyorg/busy#1293]
![3xwkdw7xqx](https://user-images.githubusercontent.com/18384831/34481317-64a8201e-efa9-11e7-8d76-8a4fb4a75f88.gif)

#### Expected behavior

The **Popover** should appear behind the NavigationBar.

#### Actual behavior

The **Popover** appear in front of NavigationBar.

* Browser: chrome
* Operating system: win7

**Comment by bonustrack** [comment]
This make the header visible when a modal is open:
![image](https://user-images.githubusercontent.com/16245250/34615640-2bf2aaa2-f268-11e7-86a1-5c7aa599ef3e.png)

**Comment by jm90m** [comment]
@sweever I don't think this is a real issue.

See my comment in this PR - https://github.com/busyorg/busy/pull/1303

but could just be my opinion, what do you think @bonustrack @Sekhmet

**Comment by sweever** [comment]
@jm90m i agree , the prob is from antd module ,  but in other case we can prove that **busy** is better than others platform.
