### ISSUE TITLE
Reputation score is wrong in some cases

### ISSUE THREAD

**Issue by espoem** [busyorg/busy#1294]
#### Expected behavior

The score for user codingdefined should be 61.

![image](https://user-images.githubusercontent.com/16621517/34482173-b3ecdf72-efb6-11e7-8d85-49fb472b300d.png)

![image](https://user-images.githubusercontent.com/16621517/34482177-b65f2990-efb6-11e7-8355-f21ba12cca50.png)

#### Actual behavior

The reputation score is 70 in busy.org and staging.busy.org

![image](https://user-images.githubusercontent.com/16621517/34482193-c78ac33c-efb6-11e7-9c07-885a99ee8a85.png)

The same behaviour shows steemnow.com too.

#### How to reproduce

1. open https://staging.busy.org/@codingdefined
2. compare with https://steemd.com/@codingdefined
* Browser: Chrome
* Operating system: Windows 10

**Comment by Sekhmet** [comment]
I have tried right now and it shows correct reputation score:
![image](https://user-images.githubusercontent.com/1968722/34612145-b86318f4-f228-11e7-9c5a-e94e2d1bfa1f.png)

**Comment by espoem** [comment]
This might have been temporary glitch. It happened in busy, utopian and steemnow.

![image](https://user-images.githubusercontent.com/16621517/34638072-b8940666-f2c4-11e7-9020-b8d3f9b5766e.png)

Screenshots from other apps at that time.

Utopian

![image](https://user-images.githubusercontent.com/16621517/34638077-cad5e9de-f2c4-11e7-8584-1482e7bf5404.png)

https://github.com/utopian-io/utopian.io/issues/238

Steemnow

![image](https://user-images.githubusercontent.com/16621517/34638079-d1fc6aa8-f2c4-11e7-8bc7-77d7e3589551.png)

We got similar report for Steemnow in Utopian

https://busy.org/utopian-io/@ravik2492/bug-found-while-checking-profile-and-vote-status-of-my-friend-on-steemnow-com

Screenshot of the chat history. Other users were able to see it too.

![image](https://user-images.githubusercontent.com/16621517/34638100-2088ae70-f2c5-11e7-9b03-0c3d80f76dce.png)

@Sekhmet

**Comment by Sekhmet** [comment]
Thanks,
I doesn't seem to be problem with Busy (and Utopian and Steemnow as well), but temporary API error that we are using. I don't think we can do anything to prevent this from happening.
