### ISSUE TITLE
Design improvement

### ISSUE THREAD

**Issue by bonustrack** [busyorg/busy#1295]
![unknown](https://user-images.githubusercontent.com/16245250/34522397-fdafa9c8-f0c4-11e7-9ba6-03b6871ff232.png)

1. Sidebar and likelist follow buttons: use `0.1` transparency background and set font color to purple (Don't change profile main follow button).
2. Topics: use color `#42bb8b` for topic border and text color and use `0.1` transparency background. Editor should also have same style for topics.
3. Remove the grey background on sidebar title.
4. Single post: on small screen, use `18px` font-size for `<p>`

**Comment by jm90m** [comment]
I can do this. @bonustrack do we need @pareshUD to confirm design?

**Comment by bonustrack** [comment]
5. Set `font-size: 18px;` for user profile "about"
![image](https://user-images.githubusercontent.com/16245250/34542947-42c34f78-f111-11e7-9f4d-5e27b675f8c2.png)

**Comment by bonustrack** [comment]
@jm90m its fine you can do it

**Comment by bonustrack** [comment]
6. On mobile view, move the search icon in left of the menu
![image](https://user-images.githubusercontent.com/16245250/34543069-b38f9f40-f111-11e7-8684-66bbad2dae68.png)
![image](https://user-images.githubusercontent.com/16245250/34543114-e1743272-f111-11e7-809d-fc9ed2dacc50.png)

**Comment by bonustrack** [comment]
7. Move top right feed story menu into bottom action bar next to "reblog" and change icon to 3 dots icon, the same used in top right of single post
![image](https://user-images.githubusercontent.com/16245250/34543361-06a23da4-f113-11e7-9014-4bc87e3639c6.png)
Then move topic in top right of story preview block
![image](https://user-images.githubusercontent.com/16245250/34543358-fd9a6e7a-f112-11e7-9907-4439e2f7f54c.png)

**Comment by bonustrack** [comment]
8. Can we have this background-color: #fcfcff instead of #f9f9f9
