### ISSUE TITLE
Market price is wrong for BitConnect

### ISSUE THREAD

**Issue by bonustrack** [busyorg/busy#1307]
The price is wrong on the right sidebar for BitConnect:
![image](https://user-images.githubusercontent.com/16245250/34615843-c6518640-f268-11e7-8ab5-59c4b4ebd1a3.png)
![image](https://user-images.githubusercontent.com/16245250/34615869-d973a2b2-f268-11e7-972a-593e4fdbd8df.png)
You can test it here:
https://staging.busy.org/bitcoin/@haejin/bitconnect-bcc-a-high-impact-trade-higher-risk-and-higher-roi-potential

**Comment by Sekhmet** [comment]
It's an API issue:
https://min-api.cryptocompare.com/data/histoday?fsym=BCC&tsym=BTC&limit=6
It doesn't seem to be possible to check if they return history for correct crypto.

**Comment by jm90m** [comment]
@Sekhmet If you want I can take over this issue and add an error check?
