### ISSUE TITLE
External links to the Busy.org ，Web site are easy to occur security loopholes in Wechat client. －－－busy网站的外链接，在微信客户端出现安全漏洞

### ISSUE THREAD

**Issue by chinesefood2018** [busyorg/busy#1322]
#### Expected behavior

Webpage links should be very safe

#### Actual behavior

 In the Wechat client, click on the other person from thebusy.org site to copy the link, you can go directly to the User Center, for comments and postings.

#### How to reproduce

You can visit my article for details
https://steemit.com/busy/@lovemyson/external-links-to-the-busy-org-web-site-are-easy-to-occur-security-loopholes-in-wechat-client-busy

* Browser: 
* Operating system:

**Comment by chinesefood2018** [comment]
@busy.org In the Wechat client, click on the other person from thebusy.org site to copy the link, you can go directly to the User Center, for comments and postings.
The details can be seen in the video.

You can visit my article for details

https://steemit.com/busy/@lovemyson/external-links-to-the-busy-org-web-site-are-easy-to-occur-security-loopholes-in-wechat-client-busy

**Comment by Sekhmet** [comment]
I'm not sure what you mean.
If you mean that sharing link like this: `https://busy.org/callback?access_token=XXXXX&expires_in=604800&state=%2F%40alishannoor&username=towardsthesun` is insecure, I agree, but there is nothing we can do to prevent sharing your login URL (the same way we can't prevent you from sharing your private keys).

**Comment by Sekhmet** [comment]
I will close this as not a bug.
If I understood something let me know and I will open this again.
