### ISSUE TITLE
#app emtied after middle mouse button click on an image

### ISSUE THREAD

**Issue by mciszczon** [busyorg/busy#1326]
## Introduction

I have stumbled upon a strange bug while using Busy, that makes the whole app disappear and can be very dangerous, i.e. it can lead to loss of any data that user entered into comment field under an article.

## Steps to reproduce

The problem occurs on Firefox Quantum on Ubuntu. I have checked it, and everything works fine on Chromium. Did not test other combinations. Exact versions available below.

1. Open any article on Busy that has got some images in the content.
2. Use the middle mouse button (the scroll wheel) click on the image (by default this is a shortcut to open a link in a new tab).

Upon doing that, all the page content will disappear and you'll only be able to see a white background.

I have also looked up the source of the website, and the `#app` container is just an empty `div`—everything gets removed from it.

## Additional information

The bug only appears to be happening when the image is also a link. When the image is only inserted and not wrapped in a link, then everything works as expected and a lightbox-like gallery opens up.

The bug is present when using __Firefox Quantum 57.0.4__ 64-bit on Ubuntu 17.10 with X.org as the display manager (I doubt it has anything to do with it, but anyway).

As said before, I tested it on Chromium 62.0.3202.94 64-bit and the bug is not present. I haven't tested it on other browsers nor other operating systems, but I might if you cannot reproduce the bug.

### Edit

I have tested in on Windows 10 operating system with Firefox 57.0.4 and the bug is also present.

## Demonstration

https://youtu.be/hNa8cTGe7q0

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@mciszczon/app-emtied-after-middle-mouse-button-click-on-an-image">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by Sekhmet** [comment]
#1309 should fix that.
