### ISSUE TITLE
Busy.org Display NSFW Post Problem

### ISSUE THREAD

**Issue by sdtyldz** [busyorg/busy#1327]
Record it after clicking on the Display NSFW Posts button in the Busy.org settings. There is no problem when you refresh the page later. However, if you enable and save the slider from the top before pressing the Display button, the Display button disabled.

https://youtu.be/Io_FGB142tg

**Steps to reproduce**
1. Open https://busy.org/settings
2. Change the NSWF settings as shown in the video.
- Browser: Google Chrome
- OS: Windows & Android
- Desktop & Mobile

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@sedatyildiz/busy-org-display-nsfw-post-problem">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by Sekhmet** [comment]
This has been fixed in #1313.
However, when saving settings slider settings are cleared.
