### ISSUE TITLE
Hello Where can i change the authentication mode

### ISSUE THREAD

**Issue by pranishg** [busyorg/busy#1330]
Hello ,
 i Forked this project and deployed on heroku to test ..
i want to launch the similar version on Neplease FOnts and i would like to change few things 

as steemconnect will authenticate busy.app  i wantto change it to powernepal 

where can i do that 

thank you 

#### How to reproduce

* Browser: 
* Operating system:

**Comment by bonustrack** [comment]
You can set the SteemConnect client id with the config var `STEEMCONNECT_CLIENT_ID`. See example: https://github.com/busyorg/busy/blob/master/.env.example#L1

**Comment by pranishg** [comment]
so if i just change the name of the account in the env.example file will it work..
i am sorry for the lame question..but i am actually not a programmer

**Comment by Sekhmet** [comment]
You have to update variables inside this file and rename it to `.env`.
