### ISSUE TITLE
Add post modal

### ISSUE THREAD

**Issue by bonustrack** [busyorg/busy#1331]

**Comment by jm90m** [comment]
I can do this if we have mockup and specs ;)

**Comment by pareshUD** [comment]
@bonustrack What is this?

**Comment by jm90m** [comment]
@pareshUD The post modal that busy v1 had, it displays the full contents of the post as a modal.

**Comment by pareshUD** [comment]
okhey got it.. I will draft some design concept today and update it

**Comment by bonustrack** [comment]
Do you have the design @pareshUD ?

**Comment by pareshUD** [comment]
![post in pop up](https://user-images.githubusercontent.com/8911074/35376393-f7236c76-01d0-11e8-948f-c22313855b8d.png)

@bonustrack here is the design for pop up..

**Comment by bonustrack** [comment]
Can we have it for mobile too?

**Comment by pareshUD** [comment]
![post pop up mobile](https://user-images.githubusercontent.com/8911074/35377152-14770532-01d4-11e8-8b7f-2e44db369569.png)

@bonustrack here is the mobile design for the same.

**Comment by bonustrack** [comment]
Can we have a top nav with back button instead?

**Comment by pareshUD** [comment]
@bonustrack That can be done when we have app.. This is more of a responsive version so thats why I kep it similar to web to have the same experience.. Let me know if youstill want to add back button I will add it.

**Comment by pareshUD** [comment]
![post pop up 2 mobile](https://user-images.githubusercontent.com/8911074/35378948-84fe94b8-01da-11e8-875d-73a9c2f422c8.png)

**Comment by bonustrack** [comment]
We dont need the full menu on top, just a `< Back` is enough @pareshUD
