### ISSUE TITLE
Power up and power down buttons

### ISSUE THREAD

**Issue by bonustrack** [busyorg/busy#1333]

**Comment by bonustrack** [comment]
@pareshUD can we have design for this?

**Comment by bonustrack** [comment]
This is how to do a power down of `10000 VESTS`:
https://steemconnect.com/sign/withdraw-vesting?vesting_shares=10000%20VESTS
And a power up:
https://steemconnect.com/sign/transfer-to-vesting?to=fabien&amount=10000%20VESTS

**Comment by pareshUD** [comment]
@bonustrack Nope as I asked you before we never discussed nor we had any brief.. 

For example if you remeber our conversation I asked you do we reduce the earning of a user if someone vote down? or just the numbers?

**Comment by pareshUD** [comment]
@bonustrack Expected behaviour

User A upvoted the post and gave 0.20$ reward and then User B downvoted.. Now here we will reduce the rewards (like he got 0.20$ from user A and then B down voted for 0.10$ so we will remove the 0.10$ reward from his rewards right?)

**Comment by Sekhmet** [comment]
@pareshUD

**Comment by pareshUD** [comment]
Hey @Sekhmet yes I am looking at it already. I will update something today.

Thanks
Paresh
