### ISSUE TITLE
Page is not fully visible on fresh loading

### ISSUE THREAD

**Issue by bonustrack** [busyorg/busy#1337]
When i open a fresh tab with busy.org for few milisecond i can see only the top of the website:
![image](https://user-images.githubusercontent.com/16245250/34914718-f57bd072-f94a-11e7-9aa7-d5e14fdf862e.png)
At the level of `Replies` button, everything get hidden. This should not happen

**Comment by jm90m** [comment]
Fixed in https://github.com/busyorg/busy/pull/1370
