### ISSUE TITLE
Market sidebar block have week days in wrong order

### ISSUE THREAD

**Issue by bonustrack** [busyorg/busy#1345]
The days are not in the correct order:
![image](https://user-images.githubusercontent.com/16245250/35001151-c20840fc-fb18-11e7-8f11-90fc490a7176.png)

**Comment by jm90m** [comment]
It is the correct order. It changes the order depending on the current day, so today was Tuesday, so it is at the end and shows last 6 days before it.

**Comment by Sekhmet** [comment]
@jm90m shouldn't this be `Wed Thu Fri Sat Sun Mon Tue`? To me it looks like it's in reversed order.

**Comment by jm90m** [comment]
@Sekhmet oh my fault, thanks for catching that, you're right
