### ISSUE TITLE
Lag when creating bulk actions

### ISSUE THREAD

**Issue by 1000goalgaming** [busyorg/busy#1351]
#### Expected behavior

Similar to vanilla Steemit, bulk actions shouldn't be that much of a problem. Got 20 people to follow? Do it smoothly.

#### Actual behavior

Lag gets VERY intensive with every action you do, increasing more and more as you continue. Bulk actions basically become impossible on Busy.org. 
#### How to reproduce

Perform 3+ actions at once, more for greater effect. Following is NOTORIOUS for this problem (try following a few people at once!)
* Browser: Chrome
* Operating system: Windows NT 10.1

**Comment by Sekhmet** [comment]
I could not reproduce this problem.
I went to following list and tried to follow ~10 people at once. No significant slowdown noticed.

**Comment by 1000goalgaming** [comment]
How come this happens for me everywhere? On mobile, on PC, on desktop..

**Comment by Sekhmet** [comment]
Can you make a video that shows this problem?

**Comment by 1000goalgaming** [comment]
Steemit is having issues so I haven't been able to. The issue still occurs, will take video when bandwidth returns
