### ISSUE TITLE
Comments like `<Hello>` can't be previewed and displayed in busy.org

### ISSUE THREAD

**Issue by DoctorLai** [busyorg/busy#1358]
#### Expected behavior
texts like `<Hello>` should be able to previewed and displayed in busy.org without problems.

#### Actual behavior
texts like `<Hello>` are not shown and displayed.

#### How to reproduce
Open any posts in busy.org and write comments `<Hello>`,  as you can see, it doesn't show preview correctly.

![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1516324609/lau7ctoau6urmddxrejt.png)

Once you commit the comment, it is not shown at all.

![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1516324682/o1lrbr1s2arkylvedevy.png)

Please note, steemit.com has this problem as well, which is reported [here](https://steemit.com/utopian-io/@jaysermendez/incomplete-comment-showing-in-comments-tab-in-profile#@justyy/re-sachincool-re-jaysermendez-incomplete-comment-showing-in-comments-tab-in-profile-20180119t010355830z)

* Browser:  Chrome v63
* Operating system: Win 10 64-bit
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@justyy/comments-like-hello-can-t-be-previewed-and-displayed-in-busy-org">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by Sekhmet** [comment]
This is not a bug.
We support HTML and `<Comment>` is treated as HTML tag.
If you want to insert it as is, use:
`&lt;Comment&gt;`
