### ISSUE TITLE
Authentication on steemconnect

### ISSUE THREAD

**Issue by pranishg** [busyorg/busy#1359]
Hello,
 I am very exicted on this porject and we forked it to make our own version at domain power4nepal.com

we have not made any major changes just few texts 

we faced a issue  when changing CLIENT_ID  from busy.app to power4nepal we have a error 
when trying to login its redirected to 404 on steem connect 

i am not much of a programmer but your help would be really appriciated

**Comment by sweever** [comment]
you need to add callback urls to your app.

**Comment by Sekhmet** [comment]
This issue belongs to https://github.com/steemit/sc2-sdk
