### ISSUE TITLE
Page is not fully visible on loading

### ISSUE THREAD

**Issue by bonustrack** [busyorg/busy#1365]
When the page is loading i'm not able to see it fully, the content stop at the red line mark:
![image](https://user-images.githubusercontent.com/16245250/35192315-0f302ac8-fec2-11e7-81af-e48cd2329c7b.png)
The overflow should not be hidden.

**Comment by jm90m** [comment]
Re-opening this since I removed `container-height` but looks like their were some updates done to the feed by @Sekhmet that might have fixed this issue anyways, if this issue is fixed we can close it again
