### ISSUE TITLE
Post images missing on json_metadata image

### ISSUE THREAD

**Issue by bonustrack** [busyorg/busy#1366]
Some posts from busy.org don't have their images saved on `json_metadata.image` for example on this post, images urls are stored in `links`:
https://steemdb.com/steem/@jerrybanfield/steem-blockchain-frees-aggroed-from-the-corporate-world-1/data
Some apps don't fetch the whole body post from feeds and dont know the preview image if the url is not inside the `json_metadata.image`.

**Comment by Sekhmet** [comment]
This is fixed by #1320.
