### ISSUE TITLE
Use rounded (circle) avatars

### ISSUE THREAD

**Issue by bonustrack** [busyorg/busy#1374]

**Comment by pareshUD** [comment]
<img width="390" alt="screen shot 2018-02-02 at 6 41 02 pm" src="https://user-images.githubusercontent.com/8911074/35735095-6cc46ef2-0849-11e8-861e-e95ea61f3339.png">

@jm90m Something like this?

**Comment by Sekhmet** [comment]
There is discussion about reputation score in this thread: #1449.
