### ISSUE TITLE
I'm new to these issues yet

### ISSUE THREAD

**Issue by burakios** [busyorg/busy#1380]
Hello,

I'm new to these issues yet. I am viewing at localhost but how do I view it on the website? what files do I change? what i need to do?

**Comment by Sekhmet** [comment]
I'm not sure what do you mean. Can you explain it more?

**Comment by burakios** [comment]
@Sekhmet site looks on http://localhost:3000 What can I change to show on my own web site?

**Comment by Sekhmet** [comment]
It's not something that's just there.
You have to have some knowledge of how to host your own websites to do it.
We provide Dockerfile and Procfile, but you have to learn how to use them on your own.
I'm afraid we can't really help you with that.

**Comment by burakios** [comment]
@Sekhmet thank you for back. I will continue to research.
