### ISSUE TITLE
Bug with center block height 

### ISSUE THREAD

**Issue by bonustrack** [busyorg/busy#1389]
The height of the center block is bigger than expected.
![image](https://user-images.githubusercontent.com/16245250/35480932-133d4c92-044c-11e8-83b2-e4fcaa74e043.png)
Test here: https://busy.org/@faberium/followed

**Comment by Sekhmet** [comment]
Looks like it's a result of bab93d in #1370.
I will deassign myself from it, as I think @jm90m might have better idea how to update it.
