### ISSUE TITLE
There is no way to refresh content

### ISSUE THREAD

**Issue by Sekhmet** [busyorg/busy#1406]

**Comment by Sekhmet** [comment]
@bonustrack what kind of content do you want to make refreshable? How should it be done?
I think that on the web pressing F5 is the standard way of refreshing content.

**Comment by itharagaian** [comment]
if I may, I agree with the fact it's problematic, the page should refresh when we surf from one tab to another in busy, or when we apply any change.
Can be confusing to save a signature, and not seeing it until F5 pressed, for example
