### ISSUE TITLE
Add option to see reputation score with decimal

### ISSUE THREAD

**Issue by Sekhmet** [busyorg/busy#1409]

**Comment by Sekhmet** [comment]
@espoem @bonustrack is it that important feature to even bother?

**Comment by espoem** [comment]
I don't think that it is important but at that time it was wanted and suggested by users. If they use different services on Steem, they might think that it is not working properly since they might be used to seeing the decimals on other apps (steemd, steemstats, steemnow, esteem).

**Comment by Sekhmet** [comment]
I don't think it's good idea to add this. Busy is not supposed to be blockchain explorer, and we shouldn't present too much of not relevant data.
If we follow other projects, we might end up one-upping them by adding yet-another decimal place, even though it's not really relevant.

**Comment by Sekhmet** [comment]
Closing this as there is no much interest in this.
