### ISSUE TITLE
Suggestion - Signature tool

### ISSUE THREAD

**Issue by itharagaian** [busyorg/busy#1436]
#### Expected behavior

When opening the editor, a button should allow to paste a **predifined signature** at current cursor position. 
The predifined should be editable in the parameters page

#### Actual behavior

As feature is absent, i need to open a previous post, edit, copy the signature, cancel edition, paste it in the new post.

* Browser:  chrome / firefox
* Operating system: Ubuntu latest LTS

**Comment by bonustrack** [comment]
I think it should be in the page edit profile with a markdown editor and stored on user `json_metadata` as `signature`.

**Comment by Sekhmet** [comment]
Probably should be done after #1450.

**Comment by Sekhmet** [comment]
@bonustrack how should it be handled in post editor? Should we have checkbox "Include signature", add "Insert signature" button or something different?

**Comment by bonustrack** [comment]
We dont need to change post editor for that. Just make the signature appear in single post if user has saved a signature on his json_metadata.
