### ISSUE TITLE
Remove default max-height

### ISSUE THREAD

**Issue by bonustrack** [busyorg/busy#1438]
Page come by default with a scrollbar, it should not be the case:
![image](https://user-images.githubusercontent.com/16245250/35632997-cc344a30-06da-11e8-988b-061e14c5bc88.png)
Probably because of recents changes https://github.com/busyorg/busy/pull/1416

**Comment by jm90m** [comment]
hmm yeah, I think I'll try to figure out a better way to solve #1365

**Comment by pareshUD** [comment]
Also once you followed someone is it ok for us to just use the tick mark? or may be use Followed instead? what you think?

**Comment by Sekhmet** [comment]
@pareshUD I'm not sure if you wanted to comment on this particular issue, but I think we could show icons instead of `Follow` `Followed` and show text on hover to mark it clear for users.

cc @bonustrack
