### ISSUE TITLE
Invite button may overflow the link box

### ISSUE THREAD

**Issue by espoem** [busyorg/busy#1443]
#### Expected behavior

The button "Copy link" should remain within the link box and be pull to the right border of the box.

![image](https://user-images.githubusercontent.com/16621517/35647938-73caebac-06d4-11e8-9703-c37298f4dc61.png)

#### Actual behavior

The button overflows the link box with different button text. If the text is short, there is a blank space on the right of the button.

![image](https://user-images.githubusercontent.com/16621517/35648000-a034c906-06d4-11e8-9862-804e3f9ea42a.png)

![image](https://user-images.githubusercontent.com/16621517/35648010-a4dc7e5e-06d4-11e8-9bb0-64f3b077682c.png)

#### How to reproduce

A)
1. https://staging.busy.org/invite
2. click the copy link button

B)
1. change the button text to be longer
2. https://staging.busy.org/invite

* Browser: Chrome 63.0.3239.132
* Operating system: Windows 10

**Comment by Sekhmet** [comment]
Right now the position is hardcoded. We can fix it by positioning it relative to input wrapper:
```diff
diff --git a/src/client/invite/Invite.less b/src/client/invite/Invite.less
index 07e85b4..97a7f7c 100644
--- a/src/client/invite/Invite.less
+++ b/src/client/invite/Invite.less
@@ -49,6 +49,11 @@
     height: 46px !important;
     font-size: 18px !important;
 
+    &-wrapper {
+      display: inline;
+      position: relative;
+    }
+
     &__copy {
       background-color: @green;
       border-radius: @border-radius-base;
```

Then we just have to update Copy button styles to use new positioning.

**Comment by emre** [comment]
My CSS skills are limited but I can work on that. :)

**Comment by Sekhmet** [comment]
Great! Let me know if you need any help with that.
