### ISSUE TITLE
Make it easy to change primary color, simplify CSS

### ISSUE THREAD

**Issue by bonustrack** [busyorg/busy#1460]
Changing the primary color should be easy as changing a single line of code. For this we need:

- `@purple` should be renamed to `@primary-color`
- The color on `.Follow--secondary` `background-color` should come from @primary-color
- Hero image should not have background.
- Use `@primary-color` here: https://github.com/busyorg/busy/blob/8a13f2c5dbc9011ed37dd54a9c7a57f572eef5ae/src/client/components/Sidebar/CryptoChart.js#L216

You should be able to change the `@primary-color` to green and browse busy.org without noticing a single purple.

**Comment by jm90m** [comment]
You can't change that too @primary-color, that isn't a LESS file, its within the JS. We can make a constants file on our end for JS related styles

**Comment by Sekhmet** [comment]
@pareshUD can we have Hero image with transparent background?

**Comment by Sekhmet** [comment]
![busy_banner](https://user-images.githubusercontent.com/1968722/35766768-2e13f76e-08de-11e8-8fa0-88d1a72b469f.png)
