### ISSUE TITLE
Math/Science Formulas

### ISSUE THREAD

**Issue by mynameisek** [busyorg/busy#1467]
Some scientists are interesting to post Maths on Busy, but it does not display correctly, one solution is to use a library like KaTeX
https://khan.github.io/KaTeX/

![image](https://user-images.githubusercontent.com/8390894/35770414-fb19892c-091a-11e8-85ca-a3e5ee1f8364.png)

**Comment by Sekhmet** [comment]
KaTeX is really big dependency and adding this would make our bundle way bigger.

We can however use online service like codecogs that accept latex and return image.

We could add special code that would turn
```
\[x^n + y^n = z^n\]
```
into
```
![equation](https://latex.codecogs.com/gif.latex?x^n + y^n = z^n)
```

So it would show like this:
![equation](https://latex.codecogs.com/gif.latex?x^n%20+%20y^n%20=%20z^n)
