### ISSUE TITLE
Transfer model is stretched out

### ISSUE THREAD

**Issue by pareshUD** [busyorg/busy#1473]
Please check the screenshot.. Transfer model has some weird spacing issues.

<img width="673" alt="screen shot 2018-02-05 at 1 30 44 pm" src="https://user-images.githubusercontent.com/8911074/35793963-b6c2dba6-0a79-11e8-9253-955694f2d11a.png">
<img width="665" alt="screen shot 2018-02-05 at 1 32 00 pm" src="https://user-images.githubusercontent.com/8911074/35793971-bfb106c0-0a79-11e8-9df0-b87dffe62601.png">

**Comment by Sekhmet** [comment]
It has been fixed there: #1453.
