### ISSUE TITLE
Integration of DLive & Dsound player/embed

### ISSUE THREAD

**Issue by mynameisek** [busyorg/busy#1474]
Embed for DLive player and also DSound, just like DTube
in feed + posts
![image](https://user-images.githubusercontent.com/8390894/35804756-57022cbc-0a79-11e8-9e95-404d4c10c0be.png)

https://busy.org/@jimmylin/86ffeef0-08b6-11e8-bfa8-b38aed9f7354
https://www.dlive.io/#/video/quinneaker/53d069f0-093e-11e8-ba0c-f3a3cb258ab6

https://dsound.audio/#/@hebrew/several-passages-read-in-fluent-hebrew-as-promised
https://busy.org/@hebrew/several-passages-read-in-fluent-hebrew-as-promised

**Comment by Sekhmet** [comment]
I'm not sure where DLive stores information about video, but there is nothing about it in post itself, so we won't be able to extract it.
DSound has information in metadata, so we can add audio tag, but it won't look like DSound, because they don't provide their own player (unlike DTube).

**Comment by Sekhmet** [comment]
We can't do this as neither DLive nor DSound provide their own players.
