### ISSUE TITLE
After entering the username and password, the "localhost:3000/callback?" error returned. 

### ISSUE THREAD

**Issue by iguozi** [busyorg/busy#1497]
#### How to reproduce

* Browser: 
* Operating system:

**Comment by iguozi** [comment]
Hello, we want to build busy.org in China. Everything else is no problem, but only to log in have bug. After clicking on the login, enter the authorization interface, but after entering the username and password, the "localhost:3000/callback?" error returned. What can we do with the code?Thank you！

**Comment by bonustrack** [comment]
Are you using a fork of Busy? We dont offer support for fork, this issue is not a Busy.org issue. I recommend you to learn development or use Busy.org directly (yes we have chiness language).

**Comment by iguozi** [comment]
We want to develop a travel proprietary interface on the basis of busy.org。can you give us some help？

**Comment by Sekhmet** [comment]
This is Busy.org related issue tracker. We don't offer support for forks.
