### ISSUE TITLE
Possible minor mistakes in webpack configuration

### ISSUE THREAD

**Issue by vsnikkil** [busyorg/busy#1499]
https://github.com/busyorg/busy/blob/bd5245616e1bd63eec31960ce5bb1dcd8aa630b7/webpack/makeConfig.js#L119
https://github.com/busyorg/busy/blob/bd5245616e1bd63eec31960ce5bb1dcd8aa630b7/webpack/makeConfig.js#L142
https://github.com/busyorg/busy/blob/bd5245616e1bd63eec31960ce5bb1dcd8aa630b7/webpack/makeConfig.js#L191

**Lines 119, 142**
I think what is meant to be in the regexp instead of `/\.css|.less$/`: `/(\.css|\.less)$/i`

**Line 191**
Replace `/\.js?$/` with this `/\.jsx?$/i`

*(lines 119, 142)*
 - **Current** - https://regexper.com/#%2F%5C.css%7C.less%24%2F
 - **Fixed** - https://regexper.com/#%2F(%5C.css%7C%5C.less)%24%2Fi

*For reference (line 191):*
 - **Current** - https://regexper.com/#%2F%5C.js%3F%24%2F
 - **Fixed** - https://regexper.com/#%2F%5C.jsx%3F%24%2F

**Comment by Sekhmet** [comment]
You are right, it was this way for the long time.
Do you want to work on this?

**Comment by vsnikkil** [comment]
Yes, sure. Ill do pull request after I get home and apply the fix.

**Comment by vsnikkil** [comment]
https://github.com/busyorg/busy/pull/1501
