### ISSUE TITLE
https://nd.busy.org/ not working ?

### ISSUE THREAD

**Issue by damaera** [busyorg/busy#1503]
i openend https://nd.busy.org/ showing in the wiki/contributor page
![image](https://user-images.githubusercontent.com/5365957/36018188-6371c534-0dad-11e8-9de5-90a1c3407a67.png)

**Comment by bonustrack** [comment]
This is an old domain, this wiki page is not relevant anymore. You should check "Lets get started" instead.

**Comment by damaera** [comment]
so the contrib wiki page must be deleted or changed?

**Comment by bonustrack** [comment]
I changed the broken link. Wiki contrib page will probably be deleted at some point.
