### ISSUE TITLE
Busy.org bug: Long post can't be edited

### ISSUE THREAD

**Issue by artemishe** [busyorg/busy#1512]
#### Expected behavior
When you click on "Edit post" button under your post - you should be redirected to post editor page.

#### Actual behavior
When you click on "Edit post" button under a **long** post (can't say the exact number of symbols. I can't edit my post with 40322 characters) - nothing happens.

#### How to reproduce
1. Make a very long post (more than 40k characters in my case) and publish it via Busy.org
2. Try to edit it. There will be a loading icon for some seconds. And nothing happens.
<p>

* Browser: Safari Version 11.0.1 (13604.3.5), Firefox 57.0.4, Yandex.Browser (based on Firefox) 17.10.0.2052
* Operating system: macOS High Sierra 10.13.1

#### Recording Of The Bug
Here I try to edit a long post (40322 characters) with no success and another post (6309 characters) successfully:
https://i.imgur.com/9jZo480.gif    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@artz/busy-org-bug-long-post-can-t-be-edited">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by Sekhmet** [comment]
It happens because it is saved on SteemConnect, but there is a size limit.

cc @bonustrack

**Comment by Sekhmet** [comment]
Migrated to #1685
