### ISSUE TITLE
Sidebar in the post jumps to the top of the page

### ISSUE THREAD

**Issue by espoem** [busyorg/busy#1515]
#### Expected behavior
The sidebar in the post should remain fixed on the right, visible to the user.

![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1518200811/dks7ovcizft0uqfk5tpg.png)

#### Actual behavior
If you open a post with a sidebar that is higher than the window (you must scroll to see full content), it may disappear / jump to the top of the page while scrolling up within the post.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/16621517/36092686-86b5cd46-0fe8-11e8-8f17-6fc73bfd1cab.gif)

![ezgif com-video-to-gif 2](https://user-images.githubusercontent.com/16621517/36092704-95d2608c-0fe8-11e8-81bf-8524d296618f.gif)

#### How to reproduce
1. Open a post in staging.busy.org (https://staging.busy.org/@justyy/utopian-chrome-extension-v0-0-9-integrate-stats-api-add-node-list)
2. Make sure that the sidebar does not fit the window (You can resize the window)
3. Scroll down to toggle the comment section so that there is enough space to scroll up
4. Scroll up / Scroll down

* Browser: Google Chrome 64.0.3282.140
* Operating system: Windows 10

### Additional recordings

![ezgif.com-video-to-gif (3).gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1518211683/kiekss7unldujid72ahd.gif)

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@espoem/sidebar-in-the-post-jumps-to-the-top-of-the-page">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by Sekhmet** [comment]
I feel like we should use `position: sticky` for sidebar instead of trying to mimic it. It doesn't work in IE11 though, but I hope polyfill would be enough.

**Comment by Sekhmet** [comment]
We will track it there: #1868
