### ISSUE TITLE
Embedded Video Thumbnails are Removed from Steemit & eSteem when Edited from Busy

### ISSUE THREAD

**Issue by adlyjailani** [busyorg/busy#1520]
![](https://marketingdeconteudo.com/wp-content/uploads/2017/06/thumbnail.png)
[Image Source](https://marketingdeconteudo.com/thumbnail/)

---

#### Expected behavior
[Posts](https://steemit.com/music/@adly.jailani/music-of-the-week-2-harris-j-salam-alaikum-my-steemian-fellows-around-the-world) created on Steemit which display an Embedded Video as its Thumbnail will still have that same Thumbnail on Steemit.com when edited on Busy.org without any changes being made.

#### Actual behavior
Posts created on Steemit which display an Embedded Video as its Thumbnail will no longer have that Thumbnail on Steemit.com when edited on Busy.org, without any changes being made.  Editing on Busy.org as breaks the video thumbnail on eSteem.

#### How to reproduce

1. Login to Steemit.com on Chrome
2. Start a New Post
3. At the top, put an Embedded Youtube Video
4. At the bottom, put a GIF
5. Submit the Post
6. Observe the Thumbnail on Account Blog is from Video
7. Login to Busy.org on Chrome
8. Open the Post made on Steemit for Editing
9.  Change nothing and Submit the Post
10. Check Steemit.com Account Feed again
11. Observe the thumbnail is the GIF image
12. Login to eSteem on Android
13. View account feed
14. Observe the thumbnail is GIF image

---

* Browser: Google Chrome Version 64.0.3282.140 (Official Build) (32-bit)

* eSteem v.1.5.1

* Operating system: Windows 7 Ultimate SP1 (32-bit).

---

#### Recording Of The Bug
And here are screenshots of the thumbnail post that I've captured, which I consider as a bug.

---

![](https://res.cloudinary.com/hpiynhbhq/image/upload/v1518244607/lfoxnxizqgxwhsarbuk1.jpg)
###### *This is the thumbnail view on the front page of my blog, that you can access throught this link > https://steemit.com/@adly.jailani*.

---

![](https://res.cloudinary.com/hpiynhbhq/image/upload/v1518249258/pnfnrusiyf1k2vlpyi0z.jpg)
###### *For more details about the body of the post, please refer to this link where the case comes from > https://steemit.com/music/@adly.jailani/music-of-the-week-2-harris-j-salam-alaikum-my-steemian-fellows-around-the-world*.

---

![Steemit correct thumbnail.jpg](https://res.cloudinary.com/hpiynhbhq/image/upload/v1518461016/ykev6vp1bfclfthbadfq.jpg)

---
###### *The correct thumbnail, before editing on Busy.org*
---

![Steemit breaks thumbnail.jpg](https://res.cloudinary.com/hpiynhbhq/image/upload/v1518461420/sntkmy7e6eaapjvozwhv.jpg)
###### *And this is the broken thumbnail, after editing on Busy.org.*

--- 

**Regards,
@adly.jailani**

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@adly.jailani/request-to-fix-thumbnail-post-view-which-includes-video-and-picture-on-steemit-com">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by jm90m** [comment]
Might have to do with something here - https://github.com/busyorg/busy/blob/29b9897ba4a029de59015bef21b36622e3c90bac/src/client/post/Write/Write.js#L188

I could be wrong though.

cc: @Sekhmet

**Comment by Sekhmet** [comment]
Right. We merge jsonMetadata with previous metadata, but `tags`, `users`, `links` and `image` are just overwritten. We should merge those as well.

**Comment by Sekhmet** [comment]
It has been fixed.
