### ISSUE TITLE
Embed code on post with GitHub

### ISSUE THREAD

**Issue by bonustrack** [busyorg/busy#1523]
Can we have something like this for markdown code
https://medium.com/javascript-scene/10-tips-for-better-redux-architecture-69250425af44
![image](https://user-images.githubusercontent.com/16245250/36147680-bb128986-10eb-11e8-9265-5568facfa0bd.png)

**Comment by Sekhmet** [comment]
There is script tag that renders those:
`<script src="https://gist.github.com/Sekhmet/1ace20856d2b524c7a3295c40d4261cf.js"></script>`

**Comment by Sekhmet** [comment]
We can add more embeds in the future when we update post rendering.

**Comment by kirkins** [comment]
+1 for this, been watching this one for a while.
