### ISSUE TITLE
busy App | Tag Suddenly Clears While Correction

### ISSUE THREAD

**Issue by dheerajsharma14** [busyorg/busy#1524]
While I was writing a post on Busy.org, I found a bug as I entered the wrong spelling and went to correct it. As you write, mistakes can happen but it does not mean the whole writing content gets cleared. As a user, I would like to edit a character if something has been misspelled.

![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1518274348/fmde2zqevsmlmgccbtil.png)

#### Expected behavior
User should always be allowed to edit the tags for any spelling mistakes even if there is a mistake of single character. User should be allowed to go to the character, correct the spelling and come back to the end of the word to continue typing it to complete it without loosing the content.

#### Actual behavior
As a user when you type the full tag and realize that the second or third character is incorrect in spelling, if you will go to the position of the misspelled character, edit to make it correct and come back to the end of the tag, the whole tag or word will disappear. User looses the whole word he typed before. Here the user should be allowed to continue typing to complete the tag.

#### How to reproduce
1. Open [Busy.org](https://busy.org/) and login to it using your user credentials.
2. Click on the Write Post link/button next to your profile image on upper right hand corner.
3. This will open the Write Post form. Enter the Title in the textbox first and then move to Tags textbox to enter the tags.
4. Write "Llandscapephotograp", notice in the spelling that I used two "L" at the start making it incorrect spelling. Using mouse, click the posting of the second "l" to delete it and correct the spelling of the tag you entered. 
5. Now that spelling  is correc in the tag, using mouse, click the end of the word next to "p" to complete the tag of "Landscapephotography" by entering the remaining "hy" in it. Notice the issue that the whole word that you entered just got disappeared.

* Browser: Google Chrome (Version 64.0.3282.140 (Official Build) (64-bit))
* Operating system: macOS High Sierra v10.13

#### Recording Of The Bug
To reproduce the issue, I have created a screen recording as well which can be found at the link: [Screen Recording Link](https://drive.google.com/file/d/18yC-u65H0I4FN8Lj2mlrZW_CrZIsKwuL/view)    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@devilonwheels/busy-app-or-tag-suddenly-clears-while-correction">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by Sekhmet** [comment]
This is not possible due to the fact tags are tokenized and are no longer editable after setting.
