### ISSUE TITLE
busy.org "Followers" and "Following" tabs lack one user in the list

### ISSUE THREAD

**Issue by crokkon** [busyorg/busy#1532]
The "Followers" and "Following" tabs on busy.org show the correct number of followers in the tab header but the list contains one user less.

#### Expected behavior
The given account currently has 3 followers. All 3 followers should be listed. Steemit.com shows the full list:
![Screenshot_2018-02-13_22-27-14.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1518557281/o4mrjfcjr9vlkzcb25ef.png)

The blockchain also reports 3 followers:
```python
>>> from steem.account import Account
>>> a = Account("stmdev")
>>> len(a.get_followers())
3
```

#### Actual behavior
Busy.org shows only 2 of the 3 followers in the list:
![Screenshot_2018-02-13_22-47-05.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1518558466/ubc3u1zgiozcz0qsgrz6.png)

The number of followers is however shown correctly.

The API call to api.steemit.com returns all 3 results:
![Screenshot_2018-02-13_22-31-50.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1518557574/lv2yq6en35n2mtcgkukv.png)

There is no entry in the console error log.

Here's a screenshot from a different account:
* This user has 9 followers but the list shows only 8 entries
![Screenshot_2018-02-13_22-38-15.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1518557926/l6mhqw4ox1n6cfanb5mk.png)
* This user is following 13 accounts, but the list only shows 12
![Screenshot_2018-02-13_22-45-16.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1518558340/wtwdumbwexjubiw27cia.png)

Here's another one following one user, but the list is empty:
![Screenshot_2018-02-13_22-52-51.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1518558806/eqfppvvg9l1elsay28ju.png)

#### How to reproduce
I could reproduce it with the following accounts:
* https://busy.org/@stmdev/followers
* https://busy.org/@onelifeonearth/followers 
* https://busy.org/@onelifeonearth/followed
* https://busy.org/@yxeyuo/followed

I can't tell if all accounts are affected since it's pretty hard to count the list entries for accounts with more than a couple of followers.

Tested with Chrome 64 and Firefox 52.6 on Linux, as well as Fennec 56.0 on Android.

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@stmdev/busy-org-followers-and-following-tabs-lack-one-user-in-the-list">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by jm90m** [comment]
Hi,

Great work reporting this! This had totally slipped past us when we were optimizing performance for follower/following lists, this will be fixed soon in https://github.com/busyorg/busy/pull/1556

Thanks again!
