### ISSUE TITLE
Unable to edit a specific post anymore

### ISSUE THREAD

**Issue by itharagaian** [busyorg/busy#1550]
#### Expected behavior

After creating : https://busy.org/@lebastion/contact-whales-difficult-task-contacter-des-baleines-c-est-dur I wish to beeing able to edit while clicking on edit button

#### Actual behavior

Waits some seconds and nothing as if you didn't click.

#### How to reproduce

Click on edit button on that  busy article I posted recently.
https://busy.org/@lebastion/contact-whales-difficult-task-contacter-des-baleines-c-est-dur

Bizarre thing : It works fine on other posts.
I see no error message
* Browser: chrome
* Operating system: ubuntu

**Comment by itharagaian** [comment]
note that it might be reported as steemit article, as I had to modifidy it to correct some errors
but it was done on busy.

**Comment by jm90m** [comment]
Can you still reproduce this? @itharagaian

**Comment by itharagaian** [comment]
Yes, but as I said, only on that post... so for me you can archive this issue and keep it somewhere if someone finds the same issue to compare what happened to both posts.

**Comment by jm90m** [comment]
We'll just keep it here, maybe others might be able to reproduce. 

Thanks for your feedback and creating this issue, there is always a chance that others might have this same issue somewhere out there 👍

**Comment by itharagaian** [comment]
Might be a CACHE issue as, after a very long while, I finally could edit it

**Comment by itharagaian** [comment]
ah new issue, same problem post : https://busy.org/@lebastion/awaiting-en-attente
Don't get what triggers the issue

**Comment by itharagaian** [comment]
could it be related to a bad reaction when you delete a draft ?

**Comment by Sekhmet** [comment]
Migrated to: #1685
