### ISSUE TITLE
Fix Top Navigation from shifting every time a modal is opened

### ISSUE THREAD

**Issue by jm90m** [busyorg/busy#1554]
#### Expected behavior
Every time a Modal is opened, the top navigation should remain in the same spot and not move.

#### Actual behavior
Top navigation header shifts awkwardly.

#### How to reproduce
- open any modal (Post modal, reblog modal, login modal...)

* Browser: Chrome
* Operating system:  OSX

**Comment by kirkins** [comment]
Tried fixing this. Haven't but here is some more info:

Notice the width of Topnav and div called `ant-layout-header` it stretches out.

Normally:

![screenshot from 2018-02-24 16-48-47](https://user-images.githubusercontent.com/9503662/36635465-0d25abb4-1983-11e8-8ddb-3494b591b77c.png)

With modal:

![screenshot from 2018-02-24 16-49-24](https://user-images.githubusercontent.com/9503662/36635468-14eb1848-1983-11e8-913c-004a72631bd9.png)

While both of these screenshots show scroll bars on the right they are not actually the same scrollbar.

The normal one is the result of the CSS:

```
body {
    overflow-y: scroll;
}
```

Which disappears when the modal pops up (notice no scroll bar):

![screenshot from 2018-02-24 17-00-38](https://user-images.githubusercontent.com/9503662/36635519-7b0825d4-1984-11e8-913c-83c922722177.png)


If you change the above to have a `!important` the navigation moving is fixed, as the scroll bar is always there even with modal up.

Unfortunately for some reason that makes the body do the same thing, except it moves some pixels to the left.

**Comment by jm90m** [comment]
yeah @kirkins, I ran into this same issue, then didn't have time to delve deeper into it, so I just created an issue about it since this has been happening for months now.

**Comment by Sekhmet** [comment]
It was fixed.
