### ISSUE TITLE
thumbnail in discord

### ISSUE THREAD

**Issue by itharagaian** [busyorg/busy#1557]
#### Expected behavior

When promoting post in Discord, users want to see the thumbnail as it works for steemit

#### Actual behavior

Link shown, post preview shown, but no thumbnail

#### How to reproduce

Simply put a busy link to post in discord, you may choose to paste an image in your post OR link the image, same result

* Browser: all
* Operating system: all

**Comment by tonimese** [comment]
This issue was resolved for a few days, now again there is no thumbnail.

**Comment by Sekhmet** [comment]
It seems to be working now:
![image](https://user-images.githubusercontent.com/1968722/37242051-1a380dca-2463-11e8-8173-e108978957b3.png)

**Comment by tonimese** [comment]
This bug keeps bugging people. Today jerrybanfield reported it. If this issue is closed, can it be reopened or I need to open another?
![image](https://user-images.githubusercontent.com/20820467/40737986-fd2d9e02-644a-11e8-9ba4-e9be364db79b.png)
