### ISSUE TITLE
More effective bold effect is needed in the posting

### ISSUE THREAD

**Issue by dakeshi** [busyorg/busy#1572]
It's very hard to figure out bold font in the posting on busy.org

![utopian_io_ _ _ _ _general_rule_](https://user-images.githubusercontent.com/8563047/36718315-a7a3bf7e-1be4-11e8-8c2b-eb531c6204d8.png)

In the steemit, it is more visual.
![utopian_io_ _ _ _ _general_rule__ _steemit](https://user-images.githubusercontent.com/8563047/36718334-b776678a-1be4-11e8-8e74-91d46dcf738a.png)

Add color to bold font or it needs to think more effective way for bold font.

* Browser: Chrome 64.0.3282.186
* Operating system: macOS Sierra

**Comment by dakeshi** [comment]
busy.org/@dakeshi/1-utopian-io

In default view size(100%), I can not find out where the bold effects are used.

**Comment by Sekhmet** [comment]
I think that link got cut off.

**Comment by dakeshi** [comment]
fixed
