### ISSUE TITLE
Bug About The Table Showing Upvotes' 

### ISSUE THREAD

**Issue by biriki3** [busyorg/busy#1575]
#### Expected behavior
I would look a post's upvote statistics by clicking the number near the upvote button. I expected to see the click-to-open table. 

![20180225_204408.jpg](https://res.cloudinary.com/hpiynhbhq/image/upload/v1519580711/y6lzq7ekfoawtwl6beqm.jpg)

#### Actual behavior
Two tables opened when i clicked the number. One of them was hover-to-open and other one was click-to-open table. Because of the hover-to-open table i couldn't see the other table clearly.

![Screenshot_20180225-204551.jpg](https://res.cloudinary.com/hpiynhbhq/image/upload/v1519580781/k9cu775j8fwatkzsliii.jpg)

#### How to reproduce
"Hover-to-open table" should be disabled for browsers that are used with mobile devices.

* Browser: 
![Screenshot_20180225-204905.jpg](https://res.cloudinary.com/hpiynhbhq/image/upload/v1519581022/wjsdrqcpa6d5diz8lql1.jpg)

* Operating system: 
![Screenshot_20180225-204927.jpg](https://res.cloudinary.com/hpiynhbhq/image/upload/v1519581086/doajxoufdaihbuxuwnkk.jpg)

#### Recording Of The Bug
https://d.tube/#!/v/biriki3/340oquc1
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@biriki3/bug-about-the-table-showing-upvotes">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by Sekhmet** [comment]
It should be fixed now.
