### ISSUE TITLE
troubleshoot problem, need help (busy slowness)

### ISSUE THREAD

**Issue by itharagaian** [busyorg/busy#1576]
#### Expected behavior

Browsing fast on busy

#### Actual behavior

User has terrible delays while opening busy and staging, we cleared cache and rebooted machine, but issue remains. username : @dodybireuen 

#### How to reproduce
cannot reproduce, I do suspect backbone bottleneck between him and busy, o I think it will self resolve, but if you have an idea ... I welcome it
* Browser: all
* Operating system: all

**Comment by itharagaian** [comment]
other users from indonesia suffer same ... seems to confirm backbone issue

**Comment by tonimese** [comment]
I had this slowness problem a few days ago. The top of the page was loading fast but not the content. Could have been a Steem node problem, the steemit site was slow loading too, but not the other sites like google and discord. The issue resolved itself after a few hours.

**Comment by Sekhmet** [comment]
Sometimes Steem API or SteemConnect take quite some time to load and thus content is loading for more than usual time. I'm afraid we can't do anything with that.
