### ISSUE TITLE
"undefined" account replaced all profiles in the right sidebar

### ISSUE THREAD

**Issue by tonimese** [busyorg/busy#1580]
#### Expected behavior

Right sidebar should show different profiles to follow

#### Actual behavior

All the links in the sidebar point to a single profile named "undefined"

#### How to reproduce

Navigate to any profile page in staging.busy.org

* Browser: Chrome, Chromium and Firefox
* Operating system: Ubuntu Linux, Android
![selection_124](https://user-images.githubusercontent.com/20820467/36819271-7703aef2-1cf1-11e8-8f57-e7d105e93e97.png)
![selection_125](https://user-images.githubusercontent.com/20820467/36819280-89eb65be-1cf1-11e8-85a2-7d1632c49720.png)

This issue was resolved after a few minutes, while I was writing this.

**Comment by tonimese** [comment]
Thanks to espoem for reporting this issue in Discord. He asked us to make the issue here. Today this situation happened again and espoem came with more evidence.
https://steemitimages.com/u/zainansari.stare/avatar
https://staging.busy.org/@zainansari.stare
https://media.discordapp.net/attachments/357941281973993473/419270829004816384/unknown.png?width=858&height=424
and asking: "Should the default avatar be displayed in case of any error with the user's avatar?"

Five hours later I am online and confirm that I see no right sidebar on the profile page of zainansari.stare
![image](https://user-images.githubusercontent.com/20820467/36930015-cff68d52-1ea1-11e8-8c67-f6cd63d5b235.png)
and all other profiles show only "undefined" account in right sidebar, on PC and mobile.
![image](https://user-images.githubusercontent.com/20820467/36930053-7e2240a6-1ea2-11e8-867e-d01c8fe06c5c.png)

The sidebar on feed page is OK, only on profile pages has this issue

**Comment by caleblogan** [comment]
zainansari.stare hasn't reblogged anyone so the right sidebar isn't supposed to display.

**Comment by jm90m** [comment]
This was because steemit was testing out their new api on prod, so they reverted it but it affected the endpoint for reblog list. 

I added a fix a few days ago, that handled both the new and old API responses. Please re-open this issue if this arises again.

CC: @bonustrack
