### ISSUE TITLE
Busy wallet isnt getting updated..

### ISSUE THREAD

**Issue by pareshUD** [busyorg/busy#1581]
Please check the attached screenshot.

<img width="1092" alt="screen shot 2018-03-01 at 4 39 12 pm" src="https://user-images.githubusercontent.com/8911074/36842077-78680dae-1d70-11e8-85e6-c0d228ea6d1f.png">
<img width="1393" alt="screen shot 2018-03-01 at 4 39 22 pm" src="https://user-images.githubusercontent.com/8911074/36842108-909bc37a-1d70-11e8-9b8b-0a145eb189d8.png">

**Comment by Sekhmet** [comment]
We can't do anything about it if API returns old amount.
