### ISSUE TITLE
installing busy with yarn install failed. The engine "node" is incompatible with this module

### ISSUE THREAD

**Issue by pavsh** [busyorg/busy#1583]
hi,
i tried to install busy locally on my laptop as explained in your readme file.
and i got the following error:
~/busy$ yarn install
yarn install v1.5.1
[1/5] Validating package.json...
error busy@2.4.0: The engine "node" is incompatible with this module. Expected version ">=7.10.1".
error An unexpected error occurred: "Found incompatible module".
info If you think this is a bug, please open a bug report with the information provided in "/home/pav/busy/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

thanks for your help

**Comment by bonustrack** [comment]
You need to use a newer version of Node.js. The minimum is `7.10.1`.

**Comment by pavsh** [comment]
you right it worked. thank you!!
