### ISSUE TITLE
Header labels hover/focus color

### ISSUE THREAD

**Issue by KrallXZ** [busyorg/busy#1593]
#### Expected behavior
It should behave like any other menu links (for example left sidebar), it should change its color to @primary-color. 
It should be 'hoverable' with TabKey too.
#### Actual behavior
It changes its color to black.
![obraz](https://user-images.githubusercontent.com/6277709/36945138-b13ef774-1fa9-11e8-9387-03738276e202.png)

#### How to reproduce
Just hover any link in topnav.

* Browser: Firefox 58
* Operating system: Win10

**Comment by bonustrack** [comment]
The color is not an issue, we will change the color for left menu to be similar than topnav (see #1549)

**Comment by KrallXZ** [comment]
So, only thing is make links tab-hoverable.

**Comment by jm90m** [comment]
This will no longer be an issue in here - https://github.com/busyorg/busy/pull/1552

**Comment by Sekhmet** [comment]
Fixed in #1552.
