### ISSUE TITLE
html5shiv

### ISSUE THREAD

**Issue by 100Errors** [busyorg/busy#1603]
### Expected behavior
html5shiv available

#### Actual behavior
http://html5shiv.googlecode.com/svn/trunk/html5.js responds with a 404 error.

#### How to reproduce
Go to busy.org and look at the source.

#### How to fix
* Remove html5shiv
* replace CDN [with cdnjs](https://github.com/busyorg/busy/compare/master...100Errors:master)

* Browser: any, but affected is only Internet Explorer with a version number lower than 9
* Operating system: windows

**Comment by bonustrack** [comment]
You wanna do a PR for this @100Errors ?
