### ISSUE TITLE
Cursor going out of the textarea while commenting

### ISSUE THREAD

**Issue by bonustrack** [busyorg/busy#1613]
Reported by @evildido

![image](https://user-images.githubusercontent.com/16245250/37146686-13d6b64c-22f7-11e8-92db-8d18ff797d8e.png)

**Comment by Sekhmet** [comment]
It happens only in post modal when scrolling page.
@jm90m

**Comment by jm90m** [comment]
thanks @Sekhmet, will check on this

**Comment by Sekhmet** [comment]
This is safari bug:
https://bugs.webkit.org/show_bug.cgi?id=138201
https://openradar.appspot.com/18819624
