### ISSUE TITLE
Bot issue workaround (suggestion)

### ISSUE THREAD

**Issue by itharagaian** [busyorg/busy#1630]
#### Expected behavior

Receive a vote when posting using busy tag on busy.org when the message in the "new post" page is shown, and see a "bot is recovering" while the bot can't vote

#### Actual behavior

skips/refuses vote if VP <16.6%, inducing user's complaints

#### How to work around

When you post on busy, on the right side you have a "need a help, use busy tag" message announcing the bot.

This message should be made dynamic, and announce "a bot cooldown" if anywhere under 20%
the bot script should enter a sleeping mode as long as VP <25% (or more, yours to choose)

when bot is alive the dynamic message should show the vote is available
when the bot is in recovering dynamic message should show : bot is in recovery, you may want to delay your post

So the bot recovers up to 25% before restarting, people couldn't complain not receiving a vote as they would see the bot is in pause, and thus they might choose to delay their post.

25% or more is important, so people get the vote when they delay it, or at least should minimize the chance of beeing in a massive flux and get the bot <20% again.

**Comment by tonimese** [comment]
This suggestion is also about the voting bot: https://github.com/busyorg/busy/issues/1560:

**Comment by Sekhmet** [comment]
Busy bot advertisement will disappear soon.
We redesigned bot and we will add automatic pause when VP is too low soon. It upvotes both live and past votes, so it's not required to time your post.
