### ISSUE TITLE
Comment widget separate bundle

### ISSUE THREAD

**Issue by bonustrack** [busyorg/busy#1637]
The page comment widget should have his own bundle, something like `/widgets/comments.min.js` instead of being within the app bundle `app.min.js`. It should make it way lighter and easier to load from 3p apps as comment widget.

**Comment by pareshUD** [comment]
@bonustrack Something like https://disqus.com/?

**Comment by bonustrack** [comment]
Closing this issue, we will use a separated repo for it.
