### ISSUE TITLE
Profile description over profile picture - rare bug

### ISSUE THREAD

**Issue by tonimese** [busyorg/busy#1651]
#### Expected behavior

Profile description should always render below the profile top section.

#### Actual behavior

Sometimes the profile description (About) renders over the profile top section, overlaying profile picture, profile name, etc.

![image](https://user-images.githubusercontent.com/20820467/37576228-20cb5156-2b34-11e8-84f1-550db5ddd9b9.png)

#### How to reproduce

This is rare and can be hard to reproduce. While browsing, open your Discussions page by clicking your profile picture in the top right.

* Browser: Version 64.0.3282.167 (Official Build) Built on Ubuntu
* Operating system: Ubuntu 16.04 (64-bit)

**Comment by Sekhmet** [comment]
We will track it there: #1868
