### ISSUE TITLE
On iOS Chrome, article pages can be moved sideways

### ISSUE THREAD

**Issue by quochuy** [busyorg/busy#1660]
#### Expected behavior
Just like the homepage, the article pages should stay fixed horizontally.  As the user tap and swipe up and down, the pages should only scroll up and down but not move left and right.

#### Actual behavior
When the user’s finger moves sideways as they swipe vertically, the article pages are moving left and right, making it a poor user experience.

#### How to reproduce
* Browser: 65.0.3325.152
* Operating system: iOS 11.2.6 (15D100)

- Load https://busy.org/ and start scrolling up and down, as you scroll, the page is scrolling: good
- Try moving the page left and right by taping and swiping horizontally, the page does not move sideways: good
- Click on an article preview to get to it’s own page.
- When the article page isn’t loaded, try to move it left/right, the page will move: not great.
- As you scroll the page up and down, the page will also follow your finger left and right. Having not much margin/padding around the text, the user might not be able to continuously read as the scroll up because the text might just be hidden if the page gets moved too much.

#### Notes
This bug does not happen if you load the article page directly (if you know the URL, reload the page after coming from the homepage, or open it on a new tab from a link on the homepage). This is because opening it from the homepage does not actually load a new page but loads the article in an overlay on top of the homepage content (seescreenshot).

#### Screenshots and comments
A page being moved to the right, moving the page sideways reveals a faded out content in the background. It looks like the previous page is still there and the article page is opened in an overlay on top. That overlay is not fixed horizontally.
![2B19C193-8A3C-4E52-8A21-7B33019CC1DF.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1521579968/xkvud4qzbkkfybinmbew.png)

 What breaks it for me is the movement as you scroll up/down. I often scroll slowly and read as I scroll and the text is often hidden away. It also make me feel a little dizzy as the page ondulates as it moves up/down.
![9B970EC0-4A38-4C55-AE9E-384482350AA2.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1521580323/bv2ghidjdvnrw0sme92o.png)

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@quochuy/on-ios-chrome-article-pages-can-be-moved-sideways">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by jm90m** [comment]
Related to #1589
