### ISSUE TITLE
Editor previewer stops working after tag delete

### ISSUE THREAD

**Issue by espoem** [busyorg/busy#1666]
#### Expected behavior

The editor previewer should work the same regardless of other actions.

#### Actual behavior

If the user writes text in the editor, adds a tag and remove it after that, the previewer freezes and does not update the output.

Video: https://streamable.com/jkm10

#### How to reproduce

1. Create new post
2. Write text in the body
3. Add a tag, remove it with backspace
4. Edit text in the editor body

* Browser: Chrome 65
* Operating system: Windows 10

**Comment by tonimese** [comment]
I confirm the bug, but it happens only after all tags are deleted, When the "Please enter topics, You have to add 1 to 5 topics" warning is visible.
![image](https://user-images.githubusercontent.com/20820467/37773782-2770186a-2de7-11e8-9efe-170a7c0cdaf5.png)
