### ISSUE TITLE
Like this post is active if user tries to write second post despite having it disabled in settings

### ISSUE THREAD

**Issue by espoem** [busyorg/busy#1667]
#### Expected behavior

Like this post checkbox should be checked/unchecked same for all new posts.

#### Actual behavior

If the user has "like my posts" unchecked in the settings, the checkbox is unchecked in the first new post. When they starting writing a draft and want to create a new post, the checkbox is checked after that.

Video: https://streamable.com/r7e04

#### How to reproduce

1. Uncheck "like my post" in the settings
2. Create new draft
3. Create new post

* Browser: Chrome 65
* Operating system: Windows 10

**Comment by tonimese** [comment]
I noticed that if I check the "Like my post" box while writing a post and click "Post", the option is also updated in Settings. I did not consider it a bug. I got use to it. Maybe it should be updated only from Settings.
