### ISSUE TITLE
Cannot search on mobile version

### ISSUE THREAD

**Issue by decebal** [busyorg/busy#1672]
#### Expected behavior
Tapping the search icon on mobile should show keys and focus on the search text box.

#### Actual behavior
When tapping the search icon the page becomes blank. No interface is shown for the user to interact with, only course of action left is refreshing the page.

#### How to reproduce
1. Open busy.org in a mobile browser (chrome, opera...)
2. tap the search icon
3. the page becomes a blank page
(alternatively the bug can be reproduced on Chrome toggling device display)

#### Recording Of The Bug
![Selection_002.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1521670231/yzgthnu4zp1on4wdxew8.png)

On clicking this message is shown in the console, while the content is turned into a blank page.
```
TypeError: Cannot read property 'focus' of undefined
```

![Selection_001.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1521670240/tlohssz2zo6x6min77t5.png)

    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@decebal2dac/cannot-search-on-mobile-version">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by espoem** [comment]
I can confirm this on Android 7.1.2, with browser Brave which is based on Chrome.

**Comment by jm90m** [comment]
This should be fixed in #1661

**Comment by jm90m** [comment]
@decebal @espoem is this fixed now for you guys on staging.busy.org?

**Comment by decebal** [comment]
yes

**Comment by jm90m** [comment]
@decebal Awesome, closing this issue, thanks for reporting it
