### ISSUE TITLE
Rotate images automatically, based on exif data

### ISSUE THREAD

**Issue by tonimese** [busyorg/busy#1676]
#### Expected behavior

Busy should rotate images automatically, based on exif data.
Here is the code needed: https://gist.github.com/runeb/c11f864cd7ead969a5f0

#### Actual behavior

Some images are displayed rotated (left, right or upside down, depending on camera hold)

#### How to reproduce

https://staging.busy.org/dlive/@fukako/44319bf0-2de6-11e8-8c78-95b7c3b77998#@fukako/re-vaelriey-re-fukako-re-vaelriey-re-fukako-44319bf0-2de6-11e8-8c78-95b7c3b77998-20180323t212821821z

https://ipfs.busy.org/ipfs/QmXjGBmHuodg27sGFu5HM3tJtgF3MGMVKN7nvHVuBbBihU

First reported in Discord by @fukako then on Utopian here: https://busy.org/@fukako/incorrect-picture-rotation-on-busy-org 

I also noticed this bug around Christmas this year while trying to upload this picture:
https://ipfs.busy.org/ipfs/QmRQBgsHmXzPfhRyDDBDDkStKhAGz3Kih851EzexUbuiWb
I did not report it then. I edited the picture and uploaded it again. 

* Browser: Chromium, Safari on the phone
* Operating system: Ubuntu, iOS

**Comment by Sekhmet** [comment]
I don't think it's worth doing on the client. I will update BusyIPFS to autorotate before uploading.

**Comment by Sekhmet** [comment]
Now server rotates images automatically based on EXIF.
