### ISSUE TITLE
Use official IPFS node urls to make it easier to replace node

### ISSUE THREAD

**Issue by bonustrack** [busyorg/busy#1679]
See this comment which explain it well: https://busy.org/@busy.org/busy-v2-4-release-new-features-that-will-make-you-love-busy-org#@sneak/re-busyorg-busy-v2-4-release-new-features-that-will-make-you-love-busy-org-20180323t222900301z

Should we use gateway.ipfs.io or ipfs.io?

**Comment by Sekhmet** [comment]
Should we return gateway URL in ipfs.busy.org response + replace current links, or we just replace it client side?

**Comment by Sekhmet** [comment]
Now busy-ipfs returns gateway URL.

https://github.com/busyorg/busy-ipfs/commit/64ec3f0e770984ce17e58520849c1d5482fc9cfa
