### ISSUE TITLE
Error Cannot GET / may be api key Problem I don't know where is the config file 

### ISSUE THREAD

**Issue by syedmustafa54** [busyorg/busy#1680]
#### Expected behavior

May Be API key do we have to give API key if yes please give the config file 

#### Actual behavior

Here is the cmd output 

```
C:\Users\ustafa\Desktop\Busy\busy>yarn dev-server
yarn run v1.5.1
$ run-p dev-server:auth-server dev-server:client
$ webpack-dev-server --config ./webpack/webpack-dev-server.js
$ node ./src/server/auth-server.js
Auth server running at http://127.0.0.1:3001/
Project is running at http://localhost:3000/
webpack output is served from /js/
Content not from webpack is served from C:\Users\ustafa\Desktop\Busy\busy\templa
tes, C:\Users\ustafa\Desktop\Busy\busy\assets
404s will fallback to /index.html
```

![error1](https://user-images.githubusercontent.com/24798263/37876874-c074f9a0-3070-11e8-9690-816cab46fd60.PNG)

#### How to reproduce
here is the yarn error log file 
[yarn-error.log](https://github.com/busyorg/busy/files/1845490/yarn-error.log)

* Browser: 
chrome
* Operating system: 
Windows

**Comment by Sekhmet** [comment]
You already have something running on port 3000.
