### ISSUE TITLE
Support for blind users

### ISSUE THREAD

**Issue by stpetecko** [busyorg/busy#1681]
#### Support for blind users

@cambridgeport9032 write:

```
Only problem, being a blind person using screen readers to interact, I can't see how to share posts, I can't activate the link to reply to someone using the keyboard, and so on.
```

**Comment by stpetecko** [comment]
@cambridgeport9032 write:
```
Indeed. It's in fact, simpler than you might think. All it takes to make a site accessible is ensuring that the screen reader can read the labels.
NVDA 
Is a good option since it's free and open source.
```
https://nvda-project.org/

**Comment by Sekhmet** [comment]
I agree that accessibility is something we struggle with.
I will combine the list of files that might need accessibility features and we will gradually improve on this.
Thanks a lot for a suggestion.

**Comment by Sekhmet** [comment]
We will track this issue here #1754.
