### ISSUE TITLE
i cant edit my post.maybe post with too many text is occured problem

### ISSUE THREAD

**Issue by mlnl17** [busyorg/busy#1685]
#### Expected behavior
when i touched “edit post”,should move in to edit page.

#### Actual behavior
nothing happen.just load symbol spining around

#### How to reproduce
https://busy.org/@coolzero/3-22-coinmarketcap-cmc
other post are ok.just this one.
and other platforms are no problem ocuur.
in steemit.com,i can edit.
even in steemkr.com,i can edit.

maybe too many text in post is problem?

* Browser: safari
* Operating system: ios iphone6s plus

**Comment by mlnl17** [comment]
https://imgur.com/gallery/KTymU
made gif file.just spinning,nothing happen

**Comment by Sekhmet** [comment]
Problem is that you have limited space for your data on SteemConnect and if you have too many (or too big) posts it won't let you create new ones. We should display error message with description in that case.

**Comment by dakeshi** [comment]
I have same issue on chrome browser. I wrote a posting which a quite long and then could not edit it.

![busy_org_edit](https://user-images.githubusercontent.com/8563047/38288135-b3f309e2-3809-11e8-8c18-5642a50ef836.gif)

**Comment by bonustrack** [comment]
💯 that would be great to have a specific error message when this issue happen. I know others users who got the same problem.

**Comment by Sekhmet** [comment]
It might be more common for Korean posts because every letter counts as three bytes (instead of 1 for English letters).

**Comment by Sekhmet** [comment]
Fixed in #1725
