### ISSUE TITLE
Request to run promotion for busy

### ISSUE THREAD

**Issue by engrbrain1** [busyorg/busy#1691]
I am a true follower of busy and I use busy in almost all my post, I would like to contribute also to busy in a way which i hope will be be fitting to you.
I have a facebook page which I believe can be used to promote busy with the use of a promotional ad will I will provide.
I want to request your permission before I can carry out the promotion or task. In doing this, I hope to contribute to the busy community in my own way.

**Comment by jm90m** [comment]
Talk to @mynameisek / (@ekitcho) on discord - https://discordapp.com/invite/G95rNZs
