### ISSUE TITLE
Category link / requested by fabien

### ISSUE THREAD

**Issue by itharagaian** [busyorg/busy#1694]
#### Expected behavior

always have the shorted link possible, thus not with category
ex: https://busy.org/busy/@itharagaian/march-18-busy-support-report
instead of https://busy.org/@itharagaian/march-18-busy-support-report

#### Actual behavior

while creating the post, the main category is included in the generated link

#### How to reproduce

Create a new post and while pressing publich, check the first given link

* Browser: all
* Operating system: all

**Comment by Sekhmet** [comment]
Fixed in #1696
