### ISSUE TITLE
`Claim rewards` button looks like disabled

### ISSUE THREAD

**Issue by rnickson** [busyorg/busy#1695]
#### Expected behavior

Should look like clickable

#### Actual behavior

Looks like non-clickable/disabled

#### How to reproduce

1. Have an account with pending rewards
2. Go to your wallet
3. It should be on the right side

* Browser: Firefox 59.0.2
* Operating system: Kubuntu 17.10

I'm really sorry, but I don't have any screenshots.

**Comment by Sekhmet** [comment]
![image](https://user-images.githubusercontent.com/1968722/38191672-07f1c002-366a-11e8-8c94-e5c8559ff5ce.png)

**Comment by jm90m** [comment]
@pareshUD can we have a better design or @bonustrack should we use the primary button color?

**Comment by pareshUD** [comment]
@jm90m I think we can make the button purple..
