### ISSUE TITLE
Where is the Html and css files and database is busy or localhost 

### ISSUE THREAD

**Issue by syedmustafa54** [busyorg/busy#1698]
Hello Where is the html files an css i just want to see the database  where its store steemconnect api will it be store in busy database or localhost database please help me out whre is the full DOC

**Comment by Sekhmet** [comment]
https://github.com/busyorg/busy/search?l=Less

Data is stored either on SteemConnect or Steem blockchain.

**Comment by syedmustafa54** [comment]
Thanks, @Sekhmet For the Reply But Where Is the Html files like I want to change the layout of busy Please Help me If you Have A discord channel Where you can help.Send The link

**Comment by syedmustafa54** [comment]
Sorry for the Trouble I founded it was in /src/client/components Closing this
