### ISSUE TITLE
Upload Image Gives Undefined Url

### ISSUE THREAD

**Issue by mypanoramicview** [busyorg/busy#1704]
When uploading an image, "Undefined" is given instead of actual url of the image

#### Expected behavior

After selecting an image a url is generated and will be placed in the Editor

#### Actual behavior

"Undefiined" is given instead of actual url of the image

#### How to reproduce

- Click `Select image or paste it from the clipboard.`
- Select an image and click open
- Wait for it to finish the upload
- Undefined is displayed in instead of actual image URL
- Broken image is displayed in the preview

* Browser: Google Chrome
* Operating system: Windows 10

Please see this screenshot:
![image](https://user-images.githubusercontent.com/36666202/38346362-31ab10c4-38c7-11e8-9a08-db3ba1252b86.png)

Please see attached screencast:
https://res.cloudinary.com/panoramicview/video/upload/v1522899704/Busy%20Upload%20Image%20Bug.mp4

**Comment by dakeshi** [comment]
Additionally, dragging image for writing posting/commenting has the same issue. 

testing env: chrome browser on busy.org/staging.busy.org

**Comment by mys** [comment]
It was temporary issue of external server https://ipfs.busy.org
The response while uploading image was `{"error":"INTERNAL_SERVER_ERROR"}`.
Seems working for now.

**Comment by Sekhmet** [comment]
I missed one thing when creating BusyIPFS that prevented uploading images after some time. This should be solved now.
