### ISSUE TITLE
Drafts are stored multiple times

### ISSUE THREAD

**Issue by bonustrack** [busyorg/busy#1705]
There is an issue atm when writing a post, draft is stored multiple time
![image](https://user-images.githubusercontent.com/16245250/38360428-56d28f3a-38f4-11e8-8a3e-142026d73973.png)
This issue is on staging.busy.org and busy.org

**Comment by planetenamek** [comment]
I don't open a niew exit but I noticed another problem with the drafts. When writing an article, we are automatically sent at the end of the page. I leave you a gif so you can see the problem in action.

![busy-preview](https://user-images.githubusercontent.com/35628060/38440790-c8449714-39e2-11e8-9d6d-c53c80067d46.gif)
