### ISSUE TITLE
Busy question of clarity

### ISSUE THREAD

**Issue by lonnieOST** [busyorg/busy#1708]
Hello,

Sorry if this is not the correct place to post this, but I recently came across "Busy" and am trying to get a feel for the code.

I know that it acts in a similar fashion as the Steemit.com site, but I cannot seem to find out if it is able to run independently of Steemit.com by calling a Steem Full-Node with the API, or does it rely on the Steemit.com API which has a database for users?

Thanks and have a good night

**Comment by bonustrack** [comment]
@lonnieOST Busy.org rely on Steem JSON RPC full node, we don't rely directly on Steemit.com.

**Comment by lonnieOST** [comment]
That's awesome to hear. So then, if I have private testnet setup as a Steem Full Node JSON RPC then I, in theory, should be able to connect Busy to it and create new users on the TESTNET blockchain (of course not interfering with the real Steem Blockchain)?

The reason for the question is that I did not see any database associated within the Busy code and was wondering where user wallets were created and stored, but then again I am not sure if Busy even keeps track of user wallets at all.

Thanks again and have a great day

**Comment by Sekhmet** [comment]
Yes, it should be possible. However, we are using SteemConnect for signing in and broadcasting transactions.
