### ISSUE TITLE
Change Feeds Tag's "ALL" to Custom Tag "dtube"

### ISSUE THREAD

**Issue by syedmustafa54** [busyorg/busy#1714]
What I wanted is for example dtube in dtube you get only dtube post, not others and another example in steepshort you get only steepshort post not others what I wanted to do is use a tag "introduction"and filter all this to my feeds and all others feeds. I should not see other than introduction tag here like dtube is doing not showing all post there.
here is what I tried
I tried to change
https://github.com/busyorg/busy/blob/master/src/client/feed/feedActions.js#L35
to `category: category || 'dtube',`
and
https://github.com/busyorg/busy/blob/master/src/client/feed/feedActions.js#L71
to `category: category || 'dtube',(edited)`
here is the oputput i am gettiing
[Image](https://images-ext-1.discordapp.net/external/yyfmaT2bE_nve_bAvw_RCLHKLlCf10w9uAUysu59Yrk/https/cdn.discordapp.com/attachments/431921262831468544/431931687669334056/unknown.png?width=331&height=301)

Even I tried to change 
https://github.com/busyorg/busy/blob/master/src/client/helpers/stateHelpers.js#L1
`export const getFeedFromState = (sortBy, category = 'dtube', state) => {`
here also the same problem

**Comment by Sekhmet** [comment]
AFAIK it's not possible without filtering it on your own.
This belongs here: https://github.com/steemit/steem-js
