### ISSUE TITLE
Replies section keeps showing the same reply multiple times if you navigate away and come back

### ISSUE THREAD

**Issue by jrawsthorne** [busyorg/busy#1715]
#### Expected behavior
When you click replies it should load all your replies. If you navigate to another page and come back, those same replies should still only show up once.

#### Actual behavior
When you first visit the replies page it shows the correct number of replies. If you go to another page and then back to the replies page, it now shows two. If you repeat, it then shows three and so on.

#### How to reproduce
Go to https://busy.org/replies whilst signed in and then click on news for example. When you click back on to replies the same one should now show up twice. It's easier to see in the video below

* Browser: Opera 52
* Operating system: Windows 10

#### Recording Of The Bug
https://media.giphy.com/media/yvqSzpaBO7YW3JbCC0/giphy.gif

Recording with more replies to show the issue more clearly

https://streamable.com/9z459

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@jrawsthorne/replies-section-keeps-showing-the-same-reply-multiple-times-if-you-navigate-away-and-come-back">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by espoem** [comment]
The report also includes my recording.

I reproduced the issue in Chrome 65, Windows 10.

**Comment by syedmustafa54** [comment]
Every Thing is Working Fine I tried No Such Issue with Windows 7 Chrome Version 65.0.3325.181 (Official Build) (64-bit)
May Be there was a problem with cache memory.
