### ISSUE TITLE
Busy Bug Report - Picture Link display while Opening Comment reply from Notification - Busy.org

### ISSUE THREAD

**Issue by ironclad010** [busyorg/busy#1716]
# <center>Bug Report - Picture Link display while Opening Comment reply from Notification - Busy.org</center>

### Expected Behaviour

*Busy* is a decentralized social network based on Steem blockchain. When you open a notification thread related to comment in this platform, the thread opened should be clear. No any icon / link should be shown unless added in comment. 

### ActuaL Behaviour

Actual behaviour was different. A link with thumbnail image is constantly shown once I comment even I dont add any image in editor. I see it when I open comment notification from my Notifications.

1. When I opened the comment notification on busy.org ( for reply), following the link, I found this image link only below my own comment. 
2. To check it in editor, I clicked on Edit. I couldnt find any image link in editor.
3. I refreshed the link but still image link was shown

#### How to reproduce the bug

Devices used :

1. Operating System: Windows
2. Windows 7
3. Browser: Chrome Version 65.0.3325.181 (Official Build) (64-bit)
4. Application : busy.org Version beta

**Please Follow steps to reproduce** :

- I opened my profile in busy.org
- I clicked on my comment notification in Notification. 
- When page was opened, I found link under my comment which was a bug
- To further check, I clicked edit to check the post content, No such link was written in editor as well.
- I refreshed the page but this bug again appeared.
- I further checked some more comment notifications, I experienced the same behaviour

 Please refer to video for screen recording of this bug.

### Recording of the Bug

http://youtu.be/JlQS2bBwvGA?hd=1

Thankyou @dynamicgreentk and @thundercurator for guidance.

If anyone else is facing same problem, please share it down below in comments

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@ironclad010/bug-report-picture-link-display-while-opening-comment-reply-from-notification-busy-org">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by Sekhmet** [comment]
Hey.
It's not a bug.

You have added signature that will be shown under your posts.
You can edit or remove it there: https://busy.org/edit-profile (on the bottom there is Signature section).

**Comment by ironclad010** [comment]
Thankyou mate. It was not bug :)
It really helped me :)
