### ISSUE TITLE
Drafts invalid date

### ISSUE THREAD

**Issue by bonustrack** [busyorg/busy#1718]
reported by @pareshUD 

> When you writing a blog draft block on right show the invalid date.
![image](https://user-images.githubusercontent.com/16245250/38515809-80bf6c1e-3c5f-11e8-8e03-044ecc24f8f5.png)

**Comment by bonustrack** [comment]
@pareshUD 
- Do you have the "Invalid Date" on the page https://busy.org/drafts too?
- Are these drafts newly created or old ones? Do you have the same issue with new draft?

**Comment by Sekhmet** [comment]
Last drafts section has been deleted and will be rewritten soon. I will close it for now and keep in mind this issue when working on new version.
