### ISSUE TITLE
cannot switch to a different user

### ISSUE THREAD

**Issue by kellyjanderson** [busyorg/busy#1729]
#### Expected behavior

When I log out and then click login, I should be presented with a form to enter the username I want to login as. 

#### Actual behavior

When I log out, then click log in, I am automatically logged in as the user I had previously been logged in as.

#### How to reproduce

Go to busy.org.

If you are logged in, click log out; otherwise login then click log out.

Click login.

You will be logged in without being given the opportunity to specify what user you want to be logged in as.

* Browser: Chrome
* Operating system: Os X

**Comment by Sekhmet** [comment]
There is nothing we can't do on our end because you are still logged in to SteemConnect. To log out you can go there: https://steemconnect.com/dashboard
