### ISSUE TITLE
I wanted to Run this On Server I am Using Npm run dev-server 

### ISSUE THREAD

**Issue by syedmustafa54** [busyorg/busy#1733]
I am using node to run this app on my local machine how should i run this on my server using node

**Comment by Sekhmet** [comment]
There are scripts for everything:
https://github.com/busyorg/busy/blob/8a619872ba12033f931dc6015ff36ba6a6cda13d/package.json#L11-L34

Busy is big project and probably not the best one for you to start learning programming. Please consider starting smaller projects and then start working with something bigger.
