### ISSUE TITLE
The user browser language should be used by default

### ISSUE THREAD

**Issue by bonustrack** [busyorg/busy#1746]
I have my browser in french language. When i open busy.org without cookie or localStorage the page is shown in english while we have french language available. Usally it was in french but not it show directly in english, i'm not sure when this been broken. We should use by default the user browser language.

**Comment by Sekhmet** [comment]
Is French the preferred language in your browser? (you can check by executing `navigator.language` in the console). I have browser in English, but my preferred language is Polish and Busy is displayed in Polish by default.

**Comment by bonustrack** [comment]
Thank you @Sekhmet, indeed my browser was in french but french was not the primary language, i've set french as primary language and busy.org are #1619 is working fine by now. Closing this issue.
