### ISSUE TITLE
Hide reward and like count if it's equal to 0

### ISSUE THREAD

**Issue by bonustrack** [busyorg/busy#1752]
It's not necessary to show rewards or like counter or comment counter for post and comments if it's equal to 0.

Before
![image](https://user-images.githubusercontent.com/16245250/38769739-0620825a-4032-11e8-8cc0-94021a5535a5.png)
After
![image](https://user-images.githubusercontent.com/16245250/38769735-fc172b2e-4031-11e8-9c37-fa251a52a92d.png)

**Comment by garroadran** [comment]
I can take a crack at this, if you'd like!

**Comment by Sekhmet** [comment]
Sure, thanks a lot!

If you have problems take a look at our [contributing guide](https://github.com/busyorg/busy/blob/s-contributing/docs/CONTRIBUTING.md). If you need any help don't hesitate to ask it there or on our [Discrod](https://discord.gg/G95rNZs) (#contributing channel).

**Comment by garroadran** [comment]
Will do! Thanks!
