### ISSUE TITLE
New language selector shows two scroll bars

### ISSUE THREAD

**Issue by jrawsthorne** [busyorg/busy#1773]
#### Expected behavior

All the languages should be shown in a list with one scroll bar on the right

#### Actual behavior

Two scroll bars appear

#### How to reproduce

Visit staging.busy.org while logged out and click the language button in the top navigation

![](https://i.imgur.com/4JTwaKe.png)

* Browser: Opera 52
* Operating system: Windows 10

**Comment by jm90m** [comment]
Thanks for reporting this issue, I can reproduce it

**Comment by jrawsthorne** [comment]
The media queries are also off. The text is centered at < 998px but the mobile menu shows up at 990px
https://streamable.com/us9lw

**Comment by MeQuake** [comment]
The [preview ](https://streamable.com/vd5pl) of above PR.
