### ISSUE TITLE
Busy bot is late to upvote

### ISSUE THREAD

**Issue by bonustrack** [busyorg/busy#1781]
We've set 15min delay for author to get upvote from our bot, but when i check the last upvote, it's always coming much more late than expected, like 1 day see here https://steemd.com/@busy.pay We should analyse what make this behavior happen and how we can fix that.

**Comment by Sekhmet** [comment]
Isn't it because that it upvotes old posts?

**Comment by bonustrack** [comment]
I can't find anyone getting upvote at around 15min after publish. All vote seem to happen way later like 1 or 2 days. When the bot catchup with the blockchain and finish the queue there shouln't be such delay to get upvote isn't it? It seem we never get to that point.

**Comment by Sekhmet** [comment]
What happens I think is that we run on low VP all the time so bots can't really upvote anything. When upvote fails its moved to the end of the queue. It takes long time for VP to regenerate and catch up to the posts that failed before.
