### ISSUE TITLE
Better mention links - suggestion

### ISSUE THREAD

**Issue by tonimese** [busyorg/busy#1783]
#### Expected feature

Transform mentions text into link even if there is no space before and after the mention, like steemit does.
![image](https://user-images.githubusercontent.com/20820467/39088332-61018ac6-45b8-11e8-920b-f7958710284e.png)
https://github.com/steemit/condenser/search?l=JavaScript&q=mention

#### Actual behavior

Mentions don't work if there is no space before and after the mention.
![image](https://user-images.githubusercontent.com/20820467/39088314-0f515e9a-45b8-11e8-8cb0-63c2741f486d.png)

**Comment by emre** [comment]
That looks a feature, not a bug.

**Comment by bonustrack** [comment]
Its fine here
