### ISSUE TITLE
SBD.symbol has changed?

### ISSUE THREAD

**Issue by kirkins** [busyorg/busy#1796]
I'm not sure what has changed in the last 24 hours but this piece here:

https://github.com/busyorg/busy/blob/bd5245616e1bd63eec31960ce5bb1dcd8aa630b7/src/client/wallet/Transfer.js#L291

Seems to be rendering as SBD* instead of just SBD.

![screenshot from 2018-04-28 13-11-04](https://user-images.githubusercontent.com/9503662/39399088-a0d27b24-4ae5-11e8-80f6-dced2b4cc225.png)

This causes a steemconnect error when you try to do a transfer.

![screenshot from 2018-04-28 13-12-34](https://user-images.githubusercontent.com/9503662/39399099-d7880026-4ae5-11e8-9e1f-21ab638c3df3.png)

I can see the `*` in the url `&amount=12 SBD*`.

**Comment by jm90m** [comment]
oh yeah, this had to do with a change in for cryptocompare, ill fix this
