### ISSUE TITLE
Logout on mobile

### ISSUE THREAD

**Issue by tonimese** [busyorg/busy#1798]
#### Expected behavior
On mobile, logout or account switch should be possible without clearing all cookie data.

#### Actual behavior
Logout is not available on Chrome mobile

* Operating system: Android

**Comment by Sekhmet** [comment]
Hey,
do you mean that logout option is not available in user menu?

There:
![image](https://user-images.githubusercontent.com/1968722/39403746-7a67c4d2-4b83-11e8-883f-b4351bb0a334.png)

**Comment by tonimese** [comment]
Yes, we got a message in Discord from mermaidvampire 
"Hi!
Uhm, it's on a mobile phone. We are using Google Chrome to get to busy.org.
For some reason we lost the logout option.
Now, we need to clear cache and cookies to logout everytime."

**Comment by Sekhmet** [comment]
Fixed in #1800.
