### ISSUE TITLE
Not all menu items are visible on mobile device

### ISSUE THREAD

**Issue by espoem** [busyorg/busy#1802]
#### Expected behavior

All items in the drop-down menu should be (visible and) accessible.

#### Actual behavior

Not all menu items are visible and it is not possible to scroll down to see the rest of the menu.

https://streamable.com/58w98

#### How to reproduce

1. Open Busy on a mobile device, ideally with a smaller screen

* Browser: Brave
* Operating system: Android 7.1.2
* Device: Moto G3 2015

**Comment by tonimese** [comment]
This issue may be related to  [#1798](https://github.com/busyorg/busy/issues/1798)

**Comment by Sekhmet** [comment]
It will be fixed in #1800.
