### ISSUE TITLE
Transform busy-img cloudinary non-transparent PNG images to JPG

### ISSUE THREAD

**Issue by bonustrack** [busyorg/busy#1803]
To reduce bandwidth and storage on Cloudinary we should transform non-transparent PNG images to JPG using "lossy" flag.

**Comment by Sekhmet** [comment]
I transformed it already. It resulted in ~15GB saving in storage. I'm not sure if it didn't update yet or that's all we can get by using `lossy`.

**Comment by bonustrack** [comment]
This is solved already by @Sekhmet
