### ISSUE TITLE
Choose database type for Busy-API

### ISSUE THREAD

**Issue by bonustrack** [busyorg/busy#1806]
Can you guys give your opinion on what database we should use based on what we discussed and on documents google drive?

**Comment by Sekhmet** [comment]
What I feel we could do is to create indexer using ORM, sync the database and compare those two and then make a choice based on results. Otherwise we would be mostly guessing what could be better.

**Comment by bonustrack** [comment]
My preference go for SQL databases too because it's well know by developer we don't need to learn SQL, there is more ressources available, maturity and projets that using them and been able to scale successfully. Hard to say between MySQL or PostgreSQL what we should use. My first preference go to MySQL because it's more used by big corporations and there is some tool that we could use like MyRocks by Facebook. On the other side PostgreSQL benefit for me is the possibility of query JSON objects (but i'm not sure if this JSON feature it's something that scale better than doing it the old way and perhaps it's also something already implemented in MySQL https://stackoverflow.com/a/39163928). Also what i like about PostgreSQL is the library `pg-promise` that is backed and used by Lisk blockchain, the lib make easier for example to do "transaction" (broadcast multiple query into a single request).

**Comment by bonustrack** [comment]
@Sekhmet If we do a test we need to fill the database with as much data as the Steem blockchain now, we could use library like `faker` to generate data and insert them in a way it's present on Steem. We can use an ORM for the test but I'm not too fan of using an ORM for the database, it adding a layer of complexity, we need to write schema and learn how to query, i would prefer to type SQL query directly like how its done with `pg-promise` or `mysql`.

**Comment by bonustrack** [comment]
We decided that Postgres is the best suited for the database. Using SQL give us more flexibility, we can easy change to MySQL if we find out it's better or to RockDB with MyRock for scale.
