### ISSUE TITLE
Bug margin in desktop small screen

### ISSUE THREAD

**Issue by bonustrack** [busyorg/busy#1809]
The red space in right should be bigger, same size than in left.
![image](https://user-images.githubusercontent.com/16245250/39478493-ced19858-4d8c-11e8-8231-9be6d74b707e.png)

**Comment by Sekhmet** [comment]
@bonustrack 

We either have:
- jumping Topbar when opening modal and opening pages with content smaller than window height.
- scrollbar displayed at all time.
- this bug with uneven space (which won't be a problem on touch devices, so only small non-touch devices are affected).

What is the call?

**Comment by jrawsthorne** [comment]
I think I have an ugly solution. The modal calculates the scrollbar width to add a padding to the body when you open it. If the same padding is added to the right of the top bar it lines up and doesn't shift.

**Comment by Sekhmet** [comment]
It might be hard to make it work in all browsers and also support modals that can have scrollbars themselves (and that might change dynamically when loading comments etc.).
