### ISSUE TITLE
Blue theme design - easter egg

### ISSUE THREAD

**Issue by tonimese** [busyorg/busy#1818]
@espoem found an interesting theme behavior

Right click on Feed and open the link in new tab to get the old dark blue theme. 

Works on https://staging.busy.org/
https://streamable.com/5yfwn

**Comment by Sekhmet** [comment]
Seems like an issue with Service Worker cache. It only refreshes every 24 hours.

**Comment by hernandev** [comment]
Got this on new browser profile.
![screenshot from 2018-05-16 01-38-50](https://user-images.githubusercontent.com/1143355/40096976-f1805510-58a9-11e8-923b-8bdc4c91b57b.png)
