### ISSUE TITLE
Wallet Power up doesnt show the username

### ISSUE THREAD

**Issue by mynameisek** [busyorg/busy#1820]
#### Expected behavior

In wallet, when power up operation to another account, it should display this other account username
![image](https://user-images.githubusercontent.com/8390894/39542037-b013f350-4e47-11e8-85a8-9fa5319c8641.png)

#### Actual behavior

not displaying username, so it is confusing 
![image](https://user-images.githubusercontent.com/8390894/39541984-9051eb62-4e47-11e8-8737-6a1913060091.png)

**Comment by emre** [comment]
I can work on that. I think adding the .to property to the string like:

> Powered up @emrebeyler 251.000 SP

will do the job. (Only if the to is different than the transaction actor.)

What do you think? (@bonustrack, @Sekhmet)

**Comment by bonustrack** [comment]
Thank you @emre that's what we need :) (but without the `@`)
