### ISSUE TITLE
Where do icons come from?

### ISSUE THREAD

**Issue by lopugit** [busyorg/busy#1826]
Such as icon-busy and all the rest icon-* 

Are they font-awesome or what?

Thanks a lot :) Just looking to change a couple

* Browser: Chrome
* Operating system: Mac OS X high sierra

**Comment by Sekhmet** [comment]
Hey, we use iconfont.cn for fonts and it's included there:
https://github.com/busyorg/busy/blob/30e984feaddfdb5448a3e4840d7be62389cf698c/src/client/styles/fonts.less#L1

I'm not sure if it's possible to make iconfont project public.

**Comment by lopugit** [comment]
@Sekhmet no worries I'll make my own, just wanted to see if it was editable 

thanks so so much for the reply :)

**Comment by Sekhmet** [comment]
No problem.

**Comment by lopugit** [comment]
@Sekhmet would you happen to have a list of all the available icons?

**Comment by Sekhmet** [comment]
You can open the latest iconfont URL and see icon names in this file:
http://at.alicdn.com/t/font_317125_ickrwibx3tmx6r.css

<img width="416" alt="zrzut ekranu 2018-05-06 o 14 02 18" src="https://user-images.githubusercontent.com/1968722/39673080-1e720a4e-5136-11e8-8429-e67ac68389c7.png">

There isn't a easy way to preview them directly. I made a screenshot of all icons from Iconfont:
![iconfont cn_manage_index_spm a313x 7781069 1998910419 11 manage_type myprojects projectid 317125 keyword 1](https://user-images.githubusercontent.com/1968722/39673094-56f20de2-5136-11e8-9e7a-73d5f0e70420.png)
