### ISSUE TITLE
wait for bundle - bundling takes aaaages

### ISSUE THREAD

**Issue by lopugit** [busyorg/busy#1827]
#### Expected behavior

Bundling done after a minute

#### Actual behavior

Bundling done after 5 minutes

#### How to reproduce

clone, yarn dev-server, see for yourself

* Browser: Chrome
* Operating system: Mac OS X high sierra

#### notes

What is the expected build time?

I get about 150+ built bundles.

And hot reloading simply doesn't work at all, it hangs on recompiling and I need to rebuild on every edit..

**Comment by Sekhmet** [comment]
It should be fixed in #1815 
Can you git pull from master, run `yarn` and try again?

There should be lots of built bundles, because they are locale bundles.

**Comment by lopugit** [comment]
@Sekhmet yep totally fixed!!! <3

**Comment by Sekhmet** [comment]
Great!
