### ISSUE TITLE
Social media preview stopped working

### ISSUE THREAD

**Issue by kirkins** [busyorg/busy#1828]
For the last week or so I have been sharing Steemit links instead of Busy.

Reason being the meta-data preview seems to have stopped working. It just shows my profile picture as the preview image on Facebook now.

**Comment by Sekhmet** [comment]
Hey.
Which posts are affected by this? I tried linking your last post and it seems to be working fine:
https://busy.org/@kirkins/beating-viarail-wifi-restrictions

**Comment by kirkins** [comment]
Weird I had a problem with that post and others. But now I try again and it works.

I'll re-open if I figure out a pattern to it.
