### ISSUE TITLE
Comments are cut in this post

### ISSUE THREAD

**Issue by bonustrack** [busyorg/busy#1836]
On this post the comment is being cut:
![image](https://user-images.githubusercontent.com/16245250/39752165-ce00d6b6-52e4-11e8-96c6-ae9c96ec7fe0.png)

https://staging.busy.org/@scipio/learn-python-series-23-handling-regular-expressions-part-1#@nomannomi/re-scipio-learn-python-series-23-handling-regular-expressions-part-1-20180507t190651517z

reported by @espoem

**Comment by Sekhmet** [comment]
There is a problem with `pre` tags. They seem to be too wide.
