### ISSUE TITLE
Uploading an image on wifi

### ISSUE THREAD

**Issue by kirkins** [busyorg/busy#1841]
Hi this is a bug I noticed a while ago but I thought it might be due to my slow wifi.

My brother is also having the issue and I've had it at many different locations.

Could it be related to maximum timeout during large photo uploads?

![Screenshot_20180508-203839.png](https://gateway.ipfs.io/ipfs/QmemPRMpt6UJyV15Gj1opNGtqcDn9RHwaaLzJttJ1Tdy5u)

**Comment by bonustrack** [comment]
Are you still able to reproduce this issue @kirkins ? Do you have an error message?

**Comment by kirkins** [comment]
Ipfs seems to be working fine on wifi now.

**Comment by kirkins** [comment]
@bonustrack this conversation might be relevant to the issue but I'm not sure.

https://busy.org/@anna-mi/coconut-milk-pancakes-with-caramelized-peach#@kirkins/re-anna-mi-coconut-milk-pancakes-with-caramelized-peach-20180520t223517130z

Could it just be a an IPFS issue (maybe not handling large HQ photos)? With Anna-mi I think she is uploading large photos. She said she could see them on her phone but when she looked on her PC they weren't there.

I had something weird like this once too. In my case I could see the photos perfectly on the draft preview, but when I submitted they were broken on the actual post.

I'm guessing something related to IPFS, I don't know much about IPFS now.

**Comment by kirkins** [comment]
In a different case she said the photos didn't appear and then later without updating the post they appeared.

> Recently I already had also. But after a while, and from the computer and from the phone became visible all the images.
