### ISSUE TITLE
Posts are visible twice on my feed

### ISSUE THREAD

**Issue by bonustrack** [busyorg/busy#1843]
![duplicate page](https://user-images.githubusercontent.com/16245250/39828776-769e5346-53e6-11e8-97d7-6301240649b2.gif)

**Comment by Sekhmet** [comment]
Are there particular steps that make it easier to reproduce it? I'm not able to reproduce it right now.

**Comment by bonustrack** [comment]
@Sekhmet perhaps its solved already on staging. Now i'm only able to reproduce it on busy.org when im logged and looking at my feed (people i follow)

**Comment by bonustrack** [comment]
I cant reproduce it anymore, it seem solved, i'm closing it.

**Comment by espoem** [comment]
Saw it today again. Caused most likely by the inaccessibility of Steemit API. Observed on busy.org

https://streamable.com/ac03f
