### ISSUE TITLE
SSR does not log me

### ISSUE THREAD

**Issue by bonustrack** [busyorg/busy#1845]
I should be logged when i open the page https://staging.busy.org/ but actually SSR does not log me even if i have a valid token saved on cookie. The login happen in front end and take few seconds.

![ssr-sc-login](https://user-images.githubusercontent.com/16245250/39858915-3b545958-5462-11e8-9bc5-96c6c89180a7.gif)

**Comment by Sekhmet** [comment]
It's because of PWA, that caches app shell. You won't be logged as you don't make request to the server.

**Comment by Sekhmet** [comment]
What do we want to do about it?

**Comment by bonustrack** [comment]
Can we have cache but also request to server to log user?

**Comment by Sekhmet** [comment]
I don't think so. AppShell is main component of PWAs.
