### ISSUE TITLE
Suggestion: share the rewards

### ISSUE THREAD

**Issue by itharagaian** [busyorg/busy#1848]
#### Expected behavior

Beeing able to share our posts rewards, just like steemwhales.com does.
Problem with steemwhales is we need to enter our private key each time, so hosting it on busy would be much more secure.

Exemple of use : 
-1- I write an article on busy moderators, and I want to share 50% of revenue with @ntony and @espoem  
-2- I want to promote a user, I make a post about him and share 15% of rewards to him
ETC ...

**Comment by Sekhmet** [comment]
Note sure how SteemWhales works. Is this about adding beneficiaries?
If so, we already have an issue for this #1402
