### ISSUE TITLE
Upload image fail half of the time

### ISSUE THREAD

**Issue by bonustrack** [busyorg/busy#1852]
![image](https://user-images.githubusercontent.com/16245250/39966401-61377a2c-56d5-11e8-85f5-fc6105441cb0.png)

**Comment by Sekhmet** [comment]
I tried to upload an image many times but couldn't reproduce. Does this link work after some time (when copied in opened in another tab)?

**Comment by Sekhmet** [comment]
What could potentially happen is that after uploading gateway.ipfs.io didn't retrieve image yet, so it returns broken URL.

**Comment by bonustrack** [comment]
Its this, we probably need to get back to ipfs.busy.org links

**Comment by bonustrack** [comment]
Perhaps (Wiktor idea): we can use ipfs.busy.org only on the preview

**Comment by imtase** [comment]
I have the same problem (windows 10 / chrome) and to solve it the only way I found is:

- save the draft
- close all browsers opened
- run CCleaner to clear all cache
- open new browser and the draft

result: the image appear

mean look like something with cache
