### ISSUE TITLE
Tab/Space in markdown not work when there is blank space (new line) 

### ISSUE THREAD

**Issue by DrSensor** [busyorg/busy#1871]
![u5dujrsy4qm5jajczyhfzlyuabdgoqg](https://user-images.githubusercontent.com/4953069/40178125-c8900eb8-5a0a-11e8-9459-8f0222f085bd.gif)

**Comment by Sekhmet** [comment]
Hey it should be fixed in #1870. It is on staging.busy.org and soon on busy.org
