### ISSUE TITLE
Busy.org Exit Page Cuts of Hashbang URL Path

### ISSUE THREAD

**Issue by CodeBull** [busyorg/busy#1877]
#### Expected behavior

Recently Busy.org implemented exit page which warns users when they are leaving Busy.org platform which has 2 buttons - `Visit this Website` and `Go Back`. Exit page also shows the URL user is about to visit. `Visit the Website` button and link preview should show the correct URL user is trying to visit.

#### Actual behavior

Exit page works fine for almost all websites except `D.Tube`. D.Tube uses hashbang URL paths and Busy.org cuts that off and redirect users to D.Tube's homepage.

#### How to reproduce

1. Go to this link https://staging.busy.org/@jeffandhisguitar/dujsmikg (used as an example).
2. Try clicking `DTube` external link at the bottom of the page.
3. You will be redirected to exit page and then click `Visit the Website` button.

* Browser: Firefox (60.0.1) and Chrome (66.0.3359.181) 
* Operating system: Ubuntu 16.04

![busy-error-2018-05-19_23 15 50](https://user-images.githubusercontent.com/1845497/40271705-d24f88a2-5bc2-11e8-8599-1b36be6a4b63.gif)

**Comment by muksihs** [comment]
THis issue prevents proper redirection to game post URL for leatherdog-games far-horizons games.

https://busy.org/@leatherdog-games/far-horizons-steem-start-of-turn-7-game-1526338556

Attempting to visit "game client" results in the game client not being sent the required hash fragment.
