### ISSUE TITLE
New server side url redirect does not honor "rewrite steemit.com urls to busy.org urls" setting

### ISSUE THREAD

**Issue by muksihs** [busyorg/busy#1879]
#### Expected behavior

when clicking on an embedded steemit.com link you should instead go to the rewritten url at busy.org

#### Actual behavior

clicking on a steemit.com link redirects to steemit.com

#### How to reproduce

open any post with a steemit.com link embedded and click the link

* Browser: Firefox
* Operating system: Mint-Mate 18

**Comment by Sekhmet** [comment]
It has been fixed now.
