### ISSUE TITLE
notifications transaction memo

### ISSUE THREAD

**Issue by tonimese** [busyorg/busy#1890]
Clicking on a notification about a transaction should open the wallet or the activity page to see the memo.
![image](https://user-images.githubusercontent.com/20820467/40365606-97ce5d9e-5ddd-11e8-9d34-cab431c6a69c.png)

Or It could display the memo when hovering over it.
![image](https://user-images.githubusercontent.com/20820467/40365975-aba3a24c-5dde-11e8-9635-d38b7ff2c282.png)

Or have buttons to choose the action.
![image](https://user-images.githubusercontent.com/20820467/40365316-f32496b4-5ddc-11e8-921b-4b0105ff1e75.png)

#### Actual behavior
Now clicking on notification about a transaction opens account profile.

**Comment by Sekhmet** [comment]
Fixed in #1919
