### ISSUE TITLE
Rare re-write bug for steemit.com/market

### ISSUE THREAD

**Issue by kirkins** [busyorg/busy#1900]
I guess there are some rare cases where you don't want a steemit.com link to be re-written to Busy.org.

In a [recent article](https://busy.org/@kirkins/vote-buying-to-become-unprofitable) I wrote I mention Steemit.com/market, problem is the link gets re-written to busy.org/market which doesn't exist.

A rare case but I will report it anyways.

**Comment by Sekhmet** [comment]
I noticed the same thing for other URL (~witnesses). We should limit URL re-writing to only compatible URLs.
