### ISSUE TITLE
Transfer Modal Amount Input is misaligned 

### ISSUE THREAD

**Issue by jm90m** [busyorg/busy#1905]
#### Expected behavior
Steem/SBD Button should be center aligned and the text for input box should be "How much do you want to send"

#### Actual behavior
<img width="622" alt="screen shot 2018-05-24 at 4 12 08 pm" src="https://user-images.githubusercontent.com/5067716/40511347-68448fb2-5f6d-11e8-9a53-2aba55e372a2.png">
<img width="604" alt="screen shot 2018-05-24 at 4 12 13 pm" src="https://user-images.githubusercontent.com/5067716/40511349-68c4c9a2-5f6d-11e8-97dd-2ad47b90dc03.png">

#### How to reproduce

* Browser: Chrome
* Operating system: OSX El Capitan

**Comment by alokpant** [comment]
@jm90m Can I look into this?

**Comment by Sekhmet** [comment]
Sure.

**Comment by Sekhmet** [comment]
Fixed in #1936.
