### ISSUE TITLE
Installing Busy on Ubuntu os 

### ISSUE THREAD

**Issue by yokesh351** [busyorg/busy#1908]
#### Expected behavior

I am installing busy for the first time in ubuntu os - AWS. I tried following the steps:

git clone https://github.com/busyorg/busy.git
cd busy

yarn
yarn start

#### Actual behavior

When i give "yarn start" i get this error below:

ubuntu@ip-172-31-26-9:~/busy$ yarn start
yarn run v1.7.0
$ node ./build/server.js
module.js:549
    throw err;
    ^

Error: Cannot find module '/home/ubuntu/busy/build/server.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

#### How to reproduce

git clone https://github.com/busyorg/busy.git
cd busy

yarn
yarn start

* Browser: 
* Operating system: Ubuntu 16.04.4 LTS (GNU/Linux 4.4.0-1060-aws x86_64)
<img width="572" alt="screenshot at may 26 19-40-12" src="https://user-images.githubusercontent.com/13276642/40577035-a3e5da20-611c-11e8-8d2f-3d7e2fc1ef47.png">

**Comment by Sekhmet** [comment]
If you want to start Busy in development mode you have to run `yarn dev`.
If you want to build and run you have to run `yarn build` and `yarn start`. I will update the docs. Thanks!
