### ISSUE TITLE
Some custom json ops cause empty activity

### ISSUE THREAD

**Issue by emre** [busyorg/busy#1909]
#### Expected behavior

STEEM blockchain lets accounts to push any type of JSON into custom_json operations. Activity page should show the operation's details. 

Since it's impossible to pre-define the structure on this, visualization may be done via tables. (Or as a design decision, busy may ignore the unregistered CustomJSON operations.)

#### Actual behavior

Activity pages show the operation empty, fails to fill the row.

Example:

<img width="523" alt="screen shot 2018-05-26 at 6 44 54 pm" src="https://user-images.githubusercontent.com/72460/40577944-fb2bf1a0-6114-11e8-9919-e32ba3ac455e.png">

See [related transaction](https://steemd.com/tx/f8f28a359f1d8d01eebef1d6f9cd9273df22ceb4). It happens any type pf custom json except follow/unfollow/ignore/reblog.

#### How to reproduce

Push a CustomJSON operation to the blockchain. It shouldn't follow the conventions on known custom jsons. (follow/unfollow, mute, etc.)

You will the see the activity page shows a blank entry.

For the reference, here is a python script to reproduce the issue:

```python
from steem import Steem
from steem.transactionbuilder import TransactionBuilder
from steembase import operations
s = Steem(nodes=["https://rpc.buildteam.io"],
          keys=["active_wif"])
account = "emrebeyler"
ops = [
    operations.CustomJson(**{
        "from": account,
        "id": "custom_id",
        "json": [
            'custom_action',
             {
                "custom_key": "custom_value",
            }
        ],
        "required_auths": [],
        "required_posting_auths": [account, ],
    }),
]
tb = TransactionBuilder()
tb.appendOps(ops)
tb.appendSigner(account, "posting")
tb.sign()
tb.broadcast()
```

* Browser/App version: Chrome Version 66.0.3359.181 (Official Build) (64-bit) on latest stable busy release
* Operating system: OSX Sierra

**Comment by emre** [comment]
I might actually work on a possible fix. My proposed solution is just ignoring unfamiliar custom jsons. What do you think?

**Comment by Sekhmet** [comment]
@bonustrack

**Comment by Sekhmet** [comment]
I think we can ignore unknown operations.

**Comment by emre** [comment]
You can see [@steemmonsters](https://busy.org/@steemmonsters/activity) to see the issue. And all users playing on steemmonsters are affected. 

I will create a PR.

**Comment by bonustrack** [comment]
Instead of ignoring these ops, i would rather display it within a table similar than others unhandled op like this:
![image](https://user-images.githubusercontent.com/16245250/41904949-f08622c2-7963-11e8-8ccd-59638708f323.png)

**Comment by emre** [comment]
Like this:

![screen shot 2018-06-26 at 1 14 08 pm](https://user-images.githubusercontent.com/72460/41905133-ea745794-7942-11e8-8b30-586b73202408.png)

Working on it. Thanks.

**Comment by bonustrack** [comment]
Yes!
