### ISSUE TITLE
Error messages from SC2 are not visible for user anymore

### ISSUE THREAD

**Issue by bonustrack** [busyorg/busy#1918]
We used to have a detail of the error message visible for the user, but now we only get "Unknown error" for any error. This should not be the case, it's confusing for an user and make harder to debug.
![image](https://user-images.githubusercontent.com/16245250/40709100-5db796b4-641f-11e8-9d27-d711d31d24e1.png)

**Comment by gregory-latinier** [comment]
Do we display the error like this ?
![image](https://user-images.githubusercontent.com/13222767/40773270-a823c4d6-64c2-11e8-854d-816ff7f3dea6.png)

**Comment by Sekhmet** [comment]
We use custom messages:
https://github.com/busyorg/busy/blob/385c026bee618ceef7b316fa4592b174cd5456ee/src/common/constants/errors.js#L1-L26
