### ISSUE TITLE
Wrong border on small screen for activity and wallet pages

### ISSUE THREAD

**Issue by bonustrack** [busyorg/busy#1929]
1: On activity and wallet pages there should not be right border on small screen here:
![image](https://user-images.githubusercontent.com/16245250/40793519-d336b55c-6526-11e8-96c0-a21bc961378d.png)
2: The top right corner should not have white background

**Comment by alokpant** [comment]
@bonustrack Can I look at this? Also there is a border-radius, that probably shouldn't be there for small devices too.

**Comment by bonustrack** [comment]
Sure @alokpant you can look on it, and you are right, small screen should not have border radius good catch :)

**Comment by alokpant** [comment]
@bonustrack Is there a bypass authentication with Steemconnect? I do not really use Steemconnect services. So to fix this one issue, I do not want to locked in Steemconnect services as it asks for Phone authentication.

**Comment by alokpant** [comment]
Also would be great to include where to visit in browser after:
```
yarn dev
```
Like visit 'http://localhost:3000' or 
print in console: **App is available at 'http://localhost:3000' or any other port if 3000 is taken.**

**Comment by alokpant** [comment]
My mistake, I should have asked more question before trying to solve the problem. Looks like Wallet and Activity pages are independent of user-login.

**Comment by alokpant** [comment]
+1 for structure of CSS. It is really nice.
