### ISSUE TITLE
Whitelist domains like steemit.com from exit page

### ISSUE THREAD

**Issue by bonustrack** [busyorg/busy#1931]
Now when an user click on external link there will be an exit page to show up for him. There is some websites that doesn't require this exit page, we should create a whitelist for it in a json file. We can start to whitelist these domains:

```
steemit.com
steem.io
d.tube
dlive.io
utopian.io
coinmarketcap.com
youtube.com
```

**Comment by Sekhmet** [comment]
@gregory-latinier 
as you are working on very similar do you want to take this issue as well? #1932
