### ISSUE TITLE
Text edit box resizing has weird acceleration.

### ISSUE THREAD

**Issue by royachiron** [busyorg/busy#1944]
#### Expected behavior

I expect it to follow my mouse cursor without much of a noticeable lag

#### Actual behavior

It lags behind. Like Android notification drawr in a low end device running Android 2.3.4. Github

#### How to reproduce
Resize the text edit box in either post or comment, pre or post posting.
![33](https://user-images.githubusercontent.com/23020420/40881950-171cee96-66dd-11e8-9372-e6b9a9f24741.gif)

Here is the rezising on steemit in glorious 60fps

![32](https://user-images.githubusercontent.com/23020420/40881953-3794f3f8-66dd-11e8-9029-05b9c209df9c.gif)

* Browser:  Firefox 60.0.1
* Operating system: Windows 10

I mentioned it in https://github.com/busyorg/busy/issues/1930
but the main issue was fixed and I'm not sure if there is a task for that part of the code as well.
I'm not sure how much you care about that, to me it's the UI equivalent of nails on board. It behaves as if I'm pulling some heavy curtain, and it weird :)

**Comment by Sekhmet** [comment]
It indeed seems to be an issue on FF. It's not something that happens because of our implementation, but antd behaves this way on FF. I will fill an issue.
