### ISSUE TITLE
Markdown is processed incorrectly

### ISSUE THREAD

**Issue by espoem** [busyorg/busy#1945]
#### Actual behavior

Markdown is not processed as it should be.

![image](https://user-images.githubusercontent.com/16621517/40884782-53fe4886-671a-11e8-89c3-7e7ca5504a26.png)

![image](https://user-images.githubusercontent.com/16621517/40884800-a9577bd6-671a-11e8-80f4-1028222af4da.png)

#### How to reproduce

1. See https://busy.org/@espoem/growing-the-potential-audience-of-video-content or https://busy.org/@lemouth/particle-physics-utopian-implementing-an-lhc-analysis-on-a-computer-the-physics-objects

* Browser: Chrome 66
* Operating system: Windows 10

**Comment by royachiron** [comment]
Hi, It's fine on my end on chrome Version 67.0.3396.62 (Official Build) (64-bit)
![image](https://user-images.githubusercontent.com/23020420/40895938-bd975562-67ba-11e8-9a3d-9a2bd72a07fc.png)

Also in my firefox 60.0.1 
![image](https://user-images.githubusercontent.com/23020420/40895982-074bdc28-67bb-11e8-8ca9-83c23bf62d2c.png)

Does it persist?

**Comment by bonustrack** [comment]
I've revert the change on busy.org but the bug should still be visible on staging.busy.org @royachiron

**Comment by bonustrack** [comment]
Perhaps we can use this https://github.com/commonmark/commonmark.js instead of `markdown-it`, it's recommended by @hernandev

**Comment by bonustrack** [comment]
Actually commonmark does not handle table, so best option is still `markdown-it` for now. We can also take a look at `marked`.

**Comment by Sekhmet** [comment]
We can migrate to `markdown-it`, but it still has this issue #1647.

I will use workaround from @hernandev and try to fix the issue in `markdown-it` directly and submit PR there.
