### ISSUE TITLE
Estimated account value on busy.org is different from steemit.com

### ISSUE THREAD

**Issue by shaphir** [busyorg/busy#1946]
#### Expected Behavior
this is a little confusing, when I open the wallet on busy.org my account's estimated value is shown as below
![IMG_20180604_003503.jpg](https://ipfs.busy.org/ipfs/QmfT4Qi6g8n8RyYnQEPVHxx7urpaK7YvJYt6f9WuuXq4NE)

#### Actual Behavior
Should my account's estimated value is as shown below
![IMG_20180604_003028.jpg](https://ipfs.busy.org/ipfs/QmSKYXPU1xARXcwtwfmqnXBdju4KrhnRGvB13xDYUen8s8)

Though this has no effect on posting and others, but this will confuse users about their account's estimated value.

#### How To Reproduce
* Go to https://busy.org/@shaphir/transfers and see estimated account value
* Then, match with estimated account values in my steemit [here](https://steemit.com/@shaphir/transfers)
* Their numbers are different there
* Browser: Google Chrome: fast & scure version 66.0.3359.158
* Operating system: Oppo a57 android version 6.0.1

#### Recording Of The Bug
https://youtu.be/SsziGclKdNQ

**Comment by itharagaian** [comment]
that is because steemit calculates on a longer period of time, meaning busy is more accurate

**Comment by bonustrack** [comment]
Yes, Busy calculate the estimated account value with current market price. I'm closing this issue as there is not a real issue about it.
