### ISSUE TITLE
Bug : Wrong Steem Dollars Prices On Busy.org

### ISSUE THREAD

**Issue by walid321** [busyorg/busy#1950]
#### Expected behavior

Busy.org should be show  correct stem dollars prices on market price.

#### Actual behavior

Busy.org is showing wrong steem dollars prices.
Which prices are not matched  with current steem dollars market prices.

#### How to reproduce

- Open a browser and go on https://busy.org/

- Log in your steemit account through steemconnect on busy.org

- Then click on **Wallet** 

- You can see it will showing wrong steem dollars prices.

- You can check steem dollars prices from other websites.

#### Recording Of The Bug
https://youtu.be/NAsAyDAZAxw

* Browser:  Google Chrome
Version 67.0.3396.62 (Official Build) beta (32-bit)

* Operating system: Windows 10

**Comment by itharagaian** [comment]
See issue #1948

**Comment by bonustrack** [comment]
Duplicate of #1948 i'm closing this issue

**Comment by walid321** [comment]
@bonustrack it's not a duplicate issue. When I published this issue, I didn't find any similar issue about this topic. you can check publish time then you will understand.

**Comment by bonustrack** [comment]
You been reporting this issue in almost same time than @itharagaian. But as far as i can see there are both exactly the same issues, and #1948 came before #1950.
