### ISSUE TITLE
Don't use image as preview if it appear on bottom of the post

### ISSUE THREAD

**Issue by bonustrack** [busyorg/busy#1967]
There is an issue when you add an image in the bottom of a post (like a signnature image), it should not appear as preview in the feed. We used to calculate where the image appear base on the text lenght and hide it if it appear too late in post. But now every image is candidate for a preview:
![image](https://user-images.githubusercontent.com/16245250/41302502-d1d5edaa-6e94-11e8-82fc-55c95bf93f1b.png) with this post https://busy-master-pr-1962.herokuapp.com/@hellosteem/test-image-in-bottom

**Comment by Sekhmet** [comment]
Image appears because it's in images array in metadata. It's the same behaviour as Steemit has:
![image](https://user-images.githubusercontent.com/1968722/41769529-e1b90e64-760f-11e8-8a47-72c3eb44a4e7.png)

We changed that in #1224 to be compatible with Steemit.
