### ISSUE TITLE
When trying to vote with 1%, system shows unknown error has occured

### ISSUE THREAD

**Issue by mightypanda-x** [busyorg/busy#1977]
#### Expected behavior

Site should show proper error message when there is an error. This will allow user to correct the problem.

#### Actual behavior

If the user has small amount of SP (less than 100), trying to vote with small vote percent throws an Unknown error has occured. Console displayed the error as 
`Unknown error info->abs_rshares > STEEM_VOTE_DUST_THRESHOLD || vote_weight == 0: Voting weight is too small, please accumulate more voting power or steem power.`

#### How to reproduce

- Login with an account with low SP. Mine has 73.
- Go to settings page and enable Voting Power slider.
- Click on the up-vote button on any post. This is show the voting slider.
- Drag the voting slider to 1% and click confirm.
- An `Unknown Error has occured` message is displayed on the screen.
- Open dev console to see actual error.

![image](https://user-images.githubusercontent.com/13856451/41518018-6ffcd164-7274-11e8-84d1-2ba667446818.png)

* Browser: Google Chrome ( 66.0.3359.181 Version)
* Operating system: OSX 10.11.6

**Comment by Sekhmet** [comment]
We should add custom message for this error as it might be pretty common.

**Comment by Sekhmet** [comment]
It was fixed in #1926. I will add tests for this to prevent future bugs.
