### ISSUE TITLE
Bug: Staging.busy.org cuts off Url path after @username

### ISSUE THREAD

**Issue by sourovafrin** [busyorg/busy#1978]
#### Expected behavior

Generally we can see full link of steem based front end links on staging.busy.org and can also click on it.
as like below picture-
![screenshot_24](https://user-images.githubusercontent.com/38147368/41573556-16be5344-739f-11e8-9343-95c70c82bc05.png)
This screenshot is from busy.org

#### Actual behavior

On staging.busy.org it is cutting off the link path after the username of all steem front end. And we can not go to that link by clicking on it.

#### How to reproduce

- Login to staging.busy.org. If you are on busy.org then mark "Use Busy beta" option from setting.

- Now take post link from steemit or busy or any other front end. Or you can test with this link `https://steemit.com/test/@sourovafrin/68hxar-test`

- Now do a post or comment by this link.

- You will see the link is only clickable upto username. The rest path is unclickable.

* Browser version: Chrome Version 67.0.3396.79 (Official Build) (64-bit)

* Operating system: Windows 8.1

#### Recording Of The Bug
![candidagilefirebelliedtoad-size_restricted](https://user-images.githubusercontent.com/38147368/41574663-3a966d16-73a3-11e8-8a63-eef19ef5012f.gif)

if the gif size is small to understand then check it [here](https://gfycat.com/gifs/detail/CandidAgileFirebelliedtoad)

**Comment by Sekhmet** [comment]
Introduced there: #1939
