### ISSUE TITLE
Vote value of 0.01 is not showing up for comments

### ISSUE THREAD

**Issue by mightypanda-x** [busyorg/busy#2018]
#### Expected behavior

Busy and steemit should show same vote values on comments.

#### Actual behavior

Busy is not showing a vote value of 0.01 on the comment but clicking on the number next to like shows the right value in details modal.

#### How to reproduce

- Upvote a comment that has not been up-voted, with 100SP account. (Or similar amount of voting power.)
- Check the comment in steemit.com. It will display .01$ vote value but busy.org will display none.
- Click on the number next to like, this will load a modal which will show .01$ vote value.

#### Example post with issue
https://steemit.com/utopian-io/@mightypanda/steemia-no-login-message-when-upvoting-after-logging-out#@fego/re-mightypanda-steemia-no-login-message-when-upvoting-after-logging-out-20180627t202253520z

https://busy.org/@mightypanda/steemia-no-login-message-when-upvoting-after-logging-out#@fego/re-mightypanda-steemia-no-login-message-when-upvoting-after-logging-out-20180627t202253520z

#### Recording of issue
https://youtu.be/K0dhuzfQ06Y

#### Possible cause
Rounding logic used on the main page is different from the logic used in modal.

* Browser: Google Chrome ( 66.0.3359.181 Version)
* Operating system: OSX 10.11.6

**Comment by itharagaian** [comment]
This is because busy uses a more precise crypto value estimation, but at the end, youĺl have exact same amount in your wallet

**Comment by mightypanda-x** [comment]
I understand its just a display issue but it should be consistent otherwise it will just be confusing.

**Comment by itharagaian** [comment]
I am not the devs, si they will decide, but for me beeing more precise is everything BUT an issue :)
