### ISSUE TITLE
Post with no json_metadata crashes the whole page

### ISSUE THREAD

**Issue by jrawsthorne** [busyorg/busy#2019]
It is usually a safe assumption that a post has some sort of json_metadata but a post is still valid on the blockchain even if it's just an empty string so all assumptions of it in the code should fallback gracefully.

#### Expected behavior

When a post doesn't contain any json_metadata the site should continue to work as normal.

#### Actual behavior

Any piece of code that tries to read a property of the JSON object when it's null will cause an error and the app will crash. 

An example is 

```javascript
if (_.indexOf(postMetaData.app, 'steemit') === 0) {
      canonicalHost = 'https://steemit.com';
    }
```

#### How to reproduce

If you got to a post with no json_metadata like this one https://busy.org/@steemed/dan-cant-censor-with-51pct the whole page crashes. If you go to a user who's reblogged it such as https://busy.org/@berniesanders the page crashes once that post is rendered

![image](https://user-images.githubusercontent.com/777143/42032173-ab642806-7ad0-11e8-918c-8b17a214a260.png)
Empty json_metadata example

**Comment by Sekhmet** [comment]
Fixed on staging. We are releasing on Monday.

https://staging.busy.org/@steemed/dan-cant-censor-with-51pct

**Comment by jrawsthorne** [comment]
Ah my bad

**Comment by Sekhmet** [comment]
No problem. We should release more often.
I will close this issue as it's fixed.

**Comment by Sekhmet** [comment]
Actually it worked on staging, because it didn't deploy latest changes automatically.
