### ISSUE TITLE
Preview Image is displayed even though there is no image in the post

### ISSUE THREAD

**Issue by mightypanda-x** [busyorg/busy#2022]
#### Expected behavior

If there is no image in the post, no preview image should get displayed.

#### Actual behavior

Preview image is displayed even though there is no image in the post.

#### How to reproduce

- Find one of your own post with image in it and click edit. This will take you to post update screen with **Update Post** button.
- Now click on Write Post button on the top right. This will load an empty post.
- Now click on the post link from Last Draft that was saved from step 1. This will load the content of that post with **Post** button instead of **Update Post**.
- Remove all references of image with just text.
- Click on **Post** button to make it live.
- Go to **Discussions** and refresh.
- Notice the image from Post in step 1 being displayed as preview image.

#### Recording of the Issue
https://youtu.be/w0aBR8wKpbM

#### Technical Analysis and Possible fix
Even though the image url was removed, some image reference was left in meta tag 

```html
<meta data-react-helmet="true" property="og:image" content="https://ipfs.busy.org/ipfs/QmaDZEsTsPD5CKyiFzyDNavxTjPY2LyPr7D8uqUoAxnmwb">
...
<meta data-react-helmet="true" property="twitter:image" content="https://ipfs.busy.org/ipfs/QmaDZEsTsPD5CKyiFzyDNavxTjPY2LyPr7D8uqUoAxnmwb">
```
Removing these can possibly fix the issue.

#### Urls
Post with issue: https://busy.org/@fastandcurious/test-post-new
Discussions Page: https://busy.org/@fastandcurious

* Browser: Google Chrome ( 66.0.3359.181 Version)
* Operating system: OSX 10.11.6

**Comment by sourovafrin** [comment]
did u edit and removed the picture?

**Comment by sourovafrin** [comment]
check it on- https://steeditor.app

**Comment by mightypanda-x** [comment]
I never specified an image. I used previous post as template and then edited it to remove with text. Never posted post with image. If you do this in new post directly, it works fine, this just happens if you recycle existing post
