### ISSUE TITLE
(Staging) Server side rendered feeds are reloaded on page load

### ISSUE THREAD

**Issue by jrawsthorne** [busyorg/busy#2030]
#### Expected behavior

Server side rendered feeds should be visible on page load and shouldn't need to refresh the first time.

#### Actual behavior

When the page is loaded the feed is rendered however after a short amount of time it's reloaded unnecessarily.

#### How to reproduce

- Visit a page that is rendered server side like https://staging.busy.org/trending
- The feed content should be visible
- Wait a moment and the feed should refresh

#### Recording
https://streamable.com/7rtjh

**Comment by jrawsthorne** [comment]
Seems like it only happens if you're logged out

**Comment by Sekhmet** [comment]
Fixed in #2042.
