### ISSUE TITLE
include mention in json_meta data similar to Steemit.com

### ISSUE THREAD

**Issue by themarkymark-steem** [busyorg/busy#2045]
#### Expected behavior

When someone writes a post mentioning other users, the mentions are included in the json_meta.

#### Actual behavior

No mention in the json_mention data

#### How to reproduce

For example this post:

https://steemit.com/steemmonsters/@mrgodby/steem-monsters-logo-refresh

This post mentions steemmonsters user, in the json meta data you can find this:

  "users": [
    "steemmonsters"
   ]

The reason this is important is the because tools like Ginabot use this to notify users when they are mentioned.  

* Browser:  N/A
* Operating system: N/A

**Comment by Sekhmet** [comment]
We use [standard format](https://github.com/bonustrackco/steemscript#comment-json_metadata) (the same that Steemit uses) for comment `json_metadata`.Please consider recommending Ginabot and other apps to use standard format.

**Comment by themarkymark-steem** [comment]
The ones we looked at did not have the mentions in the json_metadata, but I checked one of my posts and it did.  Is it possible when users edit a post and add a mention that the comment options are the broadcasted with the mentions?

**Comment by Sekhmet** [comment]
I'm not sure I understand the issue. Is it supposed to have `mention` field in metadata, or the problem is that `users` field is not present.

I created new post with mentions and it added it properly (to `users` field), I edited it to add new user and it worked as well.

Without how to reproduce steps I am afraid that I can't verify that problem.

**Comment by themarkymark-steem** [comment]
The example I gave is a comment, are comments treated differently?
