### ISSUE TITLE
Busy.org shows an inaccurate amount of reputation

### ISSUE THREAD

**Issue by shaphir** [busyorg/busy#2053]
The amount my reputation on busy.org is different from steemit.com and steemd.com

#### Below are some screenshot that show the difference
* busy.org
![screenshot_2018-07-10-15-44-12-09](https://user-images.githubusercontent.com/38022258/42499573-5421c39a-8459-11e8-96b3-ad6548db9756.png)

* steemit.com
![screenshot_2018-07-10-15-53-22-62](https://user-images.githubusercontent.com/38022258/42499630-73db32d4-8459-11e8-81f7-78f03a6d7ffb.png)

* steemd.com
![screenshot_2018-07-10-15-44-37-93](https://user-images.githubusercontent.com/38022258/42499652-877f8a92-8459-11e8-8391-39a2c98530eb.png)

**Comment by Sekhmet** [comment]
We round reputation up.

**Comment by mightypanda-x** [comment]
@Sekhmet I see that you round reputation up, but it should be rounded down.

Reason: When byteball had a airdrop, if someone had a 30 rep, he would get 10$. Busy shows a rep of 30 for 29.51 to 29.99 which will make a user believe that he will get paid but he won't because his rep is not really 30.
