### ISSUE TITLE
Signature Not visible in modal BUG / feature request

### ISSUE THREAD

**Issue by itharagaian** [busyorg/busy#2064]
#### Expected behavior

Opening article in modal should give same result as normal article view

#### How to reproduce : Choose any busy article with userś signature, and open in modal

**Feature Request**:
--->> PLEASE : instead of adding signature in busy plateform, APPEND it at end of article at saving time, so it's visible to ALL platforms. Just think about not appending when article is edited

* Browser: 
* Operating system:

**Comment by Sekhmet** [comment]
Seems to be working:
![obraz](https://user-images.githubusercontent.com/1968722/42766100-d3f4c76a-8919-11e8-9d59-b31972ea8476.png)

Can you provide reproducible demo?
