### ISSUE TITLE
Allow link with custom url schema on editor

### ISSUE THREAD

**Issue by bonustrack** [busyorg/busy#2084]
#### Expected behavior

I would like to create link with custom url schema on the editor. Like `byteball:SDTTLBG347WV2LQJRTKM2E4XM37HBM65`

#### Actual behavior

When i add markdown link, the link is changed with an extra `https://` prefix

#### How to reproduce

- Type `[Test link](byteball:SDTTLBG347WV2LQJRTKM2E4XM37HBM65)` in the editor
- Try to click on the link

**Comment by Sekhmet** [comment]
Is `byteball:XXX` valid URL? If it wants to be valid URL it should be `byteball://XXX`. Not sure if it's a typo.

**Comment by bonustrack** [comment]
`byteball:XXX` is a valid url (if the address is correct), `byteball://XXX` doesn't work (at least for Byteball wallet)
