### ISSUE TITLE
Rewrite links is not working anymore

### ISSUE THREAD

**Issue by bonustrack** [busyorg/busy#2085]
The feature "Rewrite links" does not seem to be working anymore. 

#### Steps to reproduce the issue

- Enable rewrite links on settings page
- Open https://busy.org/@tarmo888/why-didn-t-byteball-use-the-referral-links-from-the-beginning
- Click on the first link
- Here you got redirected to Steemit.com instead of Busy.org

**Comment by Sekhmet** [comment]
Problem is that our whitelist regex doesn't handle `-` in permlinks.

It can be updated there:
https://github.com/busyorg/busy/blob/27dd2383806eda8daf46748cbbbb26739d08ced4/src/client/helpers/regexHelpers.js#L9

Current regex:
![image](https://user-images.githubusercontent.com/1968722/43078098-bc3240b0-8e89-11e8-9cfc-30cf3a0151b7.png)

We should update everything marked as `word`.

I'm not sure what is supported for which part, but I guess we need to add:
- `-` for tags and permlinks
- `-` and `.` (?) for usernames

Valid characters should be checked before, so we don't miss anything.
