### ISSUE TITLE
formatter.vestToSteem is used a lot to set variables called vestsToSP, which doesn't make sense

### ISSUE THREAD

**Issue by lopugit** [busyorg/busy#2099]
#### Expected behavior
That ```formatter.vestToSteem()``` would return a STEEM ammount equal to the fraction of the reward vests to the total vests times the current STEEM vesting fund, which I think it does according to it's definition

```javascript
vestToSteem(vestingShares, totalVestingShares, totalVestingFundSteem) {
      return (
        parseFloat(totalVestingFundSteem) *
        (parseFloat(vestingShares) / parseFloat(totalVestingShares))
      );
    },
```

#### Actual behavior

This function is used nearly solely to generate numbers that represent ```SP``` amounts, but this formula generates an amount of ```STEEM```

#### How to reproduce
go here
https://github.com/busyorg/busy/blob/1bbd8c952e8fc5085b70aca9c65e8ea3256c14ad/src/client/activity/AuthorRewardMessage.js#L23-L32
https://github.com/busyorg/busy/blob/1bbd8c952e8fc5085b70aca9c65e8ea3256c14ad/src/client/activity/UserActionMessage.js#L113-L124
https://github.com/busyorg/busy/blob/1bbd8c952e8fc5085b70aca9c65e8ea3256c14ad/src/client/helpers/steemitFormatter.js#L162-L167

* Browser: Chrome idk what version it doesn't matter
* Operating system: myob

**Comment by Sekhmet** [comment]
What doesn't make sense exactly?

**Comment by lopugit** [comment]
@Sekhmet well it's constantly used to represent an SP value to the user,

like in your wallet overview, it says ```Steem Power                           X.XX SP (+Y.YY SP)```

https://gyazo.com/05572f8577859a174a135608d44a407a

but that number actually represents a steem ammount?

how do you view your actual share/vests count?

**Comment by Sekhmet** [comment]
We display shares in user friendly format (Steem Power). If you need more detailed format you can use steemd.com

**Comment by lopugit** [comment]
@Sekhmet it isn't in the right format though, it is in (Steem), when it should be in (Steem Power).

the ```vestToSteem``` function turns a (Steem Power) value into it's corresponding (Steem) value. But the UI says ```SP: ``` but it's actually (STEEM) ??????
