### ISSUE TITLE
Relative links get prefixed by "https://"

### ISSUE THREAD

**Issue by RagePeanut** [busyorg/busy#2105]
#### Expected behavior

A relative link shouldn't get prefixed and instead bring you to a page on Busy.

#### Actual behavior

Any relative link gets prefixed by "https://", turning it into a dead link (looking like https:///relative).

#### How to reproduce

Write a relative link in the post editor and try clicking on it in the preview.

Here is an example of a relative link turning into a dead one: 
https://busy.org/@timcliff/re-c1udadan0x-re-steemitblog-tracking-smt-development-progress-20180821t154624322z

I believe this bug has been introduced in the commit 22cbd06 related to the issue #2092.

**Comment by economicstudio** [comment]
I made the fix #2144. Hope it will be merged and deployed soon.
