### ISSUE TITLE
Relative link doesn't work well

### ISSUE THREAD

**Issue by bonustrack** [busyorg/busy#2109]
There is an issue on how the relative links are handled, in this article https://busy.org/steem/@timcliff/it-s-time-to-start-paying-attention-to-steem the link `/steem/@timcliff/it-s-time-to-start-paying-attention-to-steem`
points to: https://steem/@timcliff/it-s-time-to-start-paying-attention-to-steem
instead of: https://busy.org/steem/@timcliff/it-s-time-to-start-paying-attention-to-steem

Reported by @timcliff

**Comment by Sekhmet** [comment]
Duplicate of #2105
