### ISSUE TITLE
Unable to upload picture on busy

### ISSUE THREAD

**Issue by sourovafrin** [busyorg/busy#2113]
#### Expected behavior

Busy should able us uploading picture.

#### Actual behavior

User is unable to upload picture.

#### How to reproduce
- Go to busy.org and login with steemconnect.
- Now try to upload any picture
- It will says couldn't upload picture

- Analysis of this issue-
![screenshot from 2018-09-08 23-45-12](https://user-images.githubusercontent.com/38147368/45257059-5fac7d80-b3c1-11e8-9951-ba28b5eca018.png)
There is showing a problem with busy's image hosting server.

* Browser:Chrome Version 69.0.3497.81 (Official Build) (64-bit)
* Operating system: Ubuntu 8.04 Lts

Here is the screencast of this issue
https://youtu.be/Zb0I0V_JlQU

**Comment by Sekhmet** [comment]
Should work for now. I will do some migrating under the hood, so there might be some downtime at some point, but nothing long.
