### ISSUE TITLE
Not receiving any notificaitons

### ISSUE THREAD

**Issue by mightypanda-x** [busyorg/busy#2114]
#### Expected behavior
User should receive notification when someone comments on my post.

#### Actual behavior
User is not receiving any notification since at least last 2 days.

#### How to reproduce
1. Create a new post.
2. Use a second account to comment on the post created in step 1.
3. Log back in into your first account and check notification.

#### Recording of bug
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/13856451/45276925-f3418500-b479-11e8-8720-9c1249dbe5a3.gif)

* **Browser**: Google Chrome ( 69.0.3497.81 Version)
* **Operating system**: OSX 10.11.6

**Comment by Sekhmet** [comment]
Notifications should work again.
