### ISSUE TITLE
Refused to execute script from 'http://localhost:3001/148.bundle.js,etc..' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

### ISSUE THREAD

**Issue by lopugit** [busyorg/busy#2115]
#### Expected behavior

clone the master branch,

run dev script

start dev environment with app accessible at localhost:3000

#### Actual behavior

can't load all the bundles so the styling is f'd up

#### How to reproduce

clone the master branch,

run dev script

* Browser:  Chrome
* Operating system: OSX

**Comment by Sekhmet** [comment]
Just tried and everything seems to be working.

Do you have same problem if you follow those steps?
```bash
git checkout master
git pull origin master
yarn
yarn start
```

What language do you use?

**Comment by lopugit** [comment]
FMGOMFGOFOGMFOMGOFMGOMFOGMOFMGOFMGOFMGOFMOGMFOGMOFMGOMFOGMGFM ITS CAUSE I'M NOT USING YARN MOTHEREHHREHRHEURHEUHRUEWHTOUIWehgeluwhGUWRGP;IHW4engi h34

**Comment by lopugit** [comment]
fml in the ass

**Comment by lopugit** [comment]
@Sekhmet thank you so much for the quick reply.... been absolutely kicking myself................

**Comment by lopugit** [comment]
@Sekhmet I won't forget this

**Comment by lopugit** [comment]
@Sekhmet how come the heroku scripts use npm? maybe it's just the installing of dependancies via npm which breaks it and not actually running the scripts with npm, cause I was using `npm i` too

**Comment by Sekhmet** [comment]
Yarn uses yarn.lock to "pin" to specific package versions, so it will install exact the same versions of packages on every machine. NPM uses package-lock.json for this, but if you have yarn.lock NPM won't use it and generate its own package-lock.json file with probably different packages than those in yarn.lock. Those different versions of packages might cause some problems.

On heroku we use npm to build application (which we probably should change to yarn), but packages are installed using `yarn`, so there is no such problem with dependencies.

**Comment by lopugit** [comment]
@Sekhmet thank god, it's one of the only projects in our codebase that uses yarn so I completely forgot...... nothing against yarn but I've been debugging this for week's tbh

**Comment by lopugit** [comment]
@Sekhmet how do you handle .env ? do you run `source .env` or, I tried using `dotenv` and `dotenv-expand` but `dotenv-expand` doesn't support if statements so, I'm guessing `source .env` before building? I tried adding `source .env` to the dev package.json script but that didn't seem to actually set any environment variables either

**Comment by Sekhmet** [comment]
You don't need to care about `.env` locally. We provide environment variables on Heroku directly for production.

**Comment by lopugit** [comment]
@Sekhmet we don't use Heroku, we're building a different platform called WeYouMe, repo at github.com/weyoume so local environment variables are important

**Comment by Sekhmet** [comment]
We don't provide support for custom deployments.

**Comment by lopugit** [comment]
@Sekhmet that's fine but I'm just asking how you handle .env loading into process.env because it's used a lot? I don't mind I've just removed any if statements or bash scripting from the .env file and used `require('dotenv').config()`
