### ISSUE TITLE
wss://api.busy.org a bit flaky

### ISSUE THREAD

**Issue by lopugit** [busyorg/busy#2116]
#### Expected behavior

No errors on busyjs api calls

#### Actual behavior

occasionally get errors which crash the process until restart and I can't see what's causing the error at all

`
Error: Unexpected server response: 503
0|busyapp-st |     at ClientRequest._req.on (/var/www/nodes/busyapp-steem-prod-alpha/node_modules/ws/lib/websocket.js:645:21)
0|busyapp-st |     at emitOne (events.js:116:13)
0|busyapp-st |     at ClientRequest.emit (events.js:211:7)
0|busyapp-st |     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:543:21)
0|busyapp-st |     at HTTPParser.parserOnHeadersComplete (_http_common.js:112:17)
0|busyapp-st |     at TLSSocket.socketOnData (_http_client.js:440:20)
0|busyapp-st |     at emitOne (events.js:116:13)
0|busyapp-st |     at TLSSocket.emit (events.js:211:7)
0|busyapp-st |     at addChunk (_stream_readable.js:263:12)
0|busyapp-st |     at readableAddChunk (_stream_readable.js:250:11)
`

#### How to reproduce

run a busy process and use it a bit

* Browser: 
* Operating system:

**Comment by lopugit** [comment]
So in the docs you actually say to use `wss://gtg.steem.house:8090` instead of `wss://api.busy.org` lol so I switched to that hopefully it fixes the issues

**Comment by lopugit** [comment]
search results changed though wtf... the search engine api really needs a fix, is that what you guys meant by you changed the autocomplete/search, actually on the api end?

**Comment by Sekhmet** [comment]
Use https://api.steemit.com

**Comment by lopugit** [comment]
@Sekhmet busyjs requires a wss:// url?

**Comment by Sekhmet** [comment]
If it's about busy-js please report it to busy-js repo with reproducible demo.

**Comment by lopugit** [comment]
@Sekhmet sorry I should have been clearer

**Comment by sahidhossen** [comment]
Is this problem solved ? I need a solution for this issue. Can't understand how can I solve this. 
Thanks.

**Comment by lopugit** [comment]
Yes my friend wss://gtg.steem.house:8090 <wss://gtg.steem.house:8090/> works
