### ISSUE TITLE
Notification not loading since last steem crash - 503 error in console

### ISSUE THREAD

**Issue by mightypanda-x** [busyorg/busy#2122]
#### Expected behavior

When i login into busy and click on bell icon, i should see the notifications

#### Actual behavior

After i click on bell icon, i only see a spinner. Looking at the dev console, I see a 503 error for websocket.

#### How to reproduce

1. Login to the busy account.
2. Click on the bell icon on the top right corner.
3. Notice the spinner and error in dev console.

![image](https://user-images.githubusercontent.com/13856451/45865635-02a2b700-bd33-11e8-90fe-21f10ba36178.png)

_(I don't know how useful this below image is since its uglified code)_
![image](https://user-images.githubusercontent.com/13856451/45865677-2239df80-bd33-11e8-8a65-963d3ca8fc78.png)

**Browser**: Google Chrome ( 69.0.3497.100 Version)
**Operating system**: OSX 10.11.6

**Comment by Sekhmet** [comment]
Hey,
Notifications API goes down from time to time, but as of now, it's okay.
For future reference, if this happens again can you let us know on Discord as it's not a bug in Busy codebase, but just a server getting stuck.
Thanks.
