### ISSUE TITLE
Is it possible to --inspect the yarn dev script?

### ISSUE THREAD

**Issue by lopugit** [busyorg/busy#2123]
#### Expected behavior
// package.json
"dev": "node --inspect=9230 ./scripts/dev.js",
// console
yarn dev
yarn run v1.9.4
$ node --inspect=9230 ./scripts/dev.js
Debugger listening on ws://127.0.0.1:9230/aee3010c-921d-405a-8a47-5ed0ee8fb999
For help see https://nodejs.org/en/docs/inspector
✔ success client compiled in 3s 802ms
✔ success server compiled in 3s 229ms

#### Actual behavior
// package.json
"dev": "node --inspect=9230 ./scripts/dev.js",
// console
yarn dev
yarn run v1.9.4
$ node --inspect=9230 ./scripts/dev.js
Debugger listening on ws://127.0.0.1:9230/aee3010c-921d-405a-8a47-5ed0ee8fb999
For help see https://nodejs.org/en/docs/inspector
✔ success client compiled in 2m 44s 482ms
Compiling
● client
● server █████████████████████████ emitting (95%)
Starting inspector on 127.0.0.1:9230 failed: address already in use
♥

#### How to reproduce
just change the `"dev" :  "node ./scripts/dev.js"` to "dev" :  "node --inspect=9230 ./scripts/dev.js" and run yarn dev

* Browser: chrome
* Operating system: osx

**Comment by lopugit** [comment]
Hello?

**Comment by Sekhmet** [comment]
Could not reproduce. You have clearly something already running on this port.
