### ISSUE TITLE
Flatmap-stream

### ISSUE THREAD

**Issue by Kennybll** [busyorg/busy#2127]
#### Expected behavior
Not to have flatmap-stream in node_modules.

#### Actual behavior
I'm not sure, but you might want to check your node_modules.

#### How to reproduce
https://github.com/dominictarr/event-stream/issues/116

* Browser: 
* Operating system:

**Comment by Sekhmet** [comment]
Thanks for a heads-up!

```bash
➜  busy git:(develop) npm ls event-stream flatmap-stream       
busy@2.5.6 /home/sekhmet/Workspace/busy
└─┬ npm-run-all@4.1.2
  └─┬ ps-tree@1.1.0
    └── event-stream@3.3.4
```

Luckily we don't depend on `flatmap-stream`.
