### ISSUE TITLE
incorrect reputation

### ISSUE THREAD

**Issue by economicstudio** [busyorg/busy#2145]
#### Expected behavior

Reputation score should be floored.

For instance, 69.822 should be shown as 69

#### Actual behavior

Reputation score is rounded.

For instance, 69.822 is shown as 70

#### How to reproduce

* Browser: Any
* Operating system: Any

It happens all the time.

![](https://cdn.steemitimages.com/DQmVYTFffRLpYqMZupDb4hCQiimJwdeyw6pHP5dupcsxoED/Screen%20Shot%202018-12-30%20at%203.43.21%20AM.png)
> https://busy.org/@ned Ned looks 70 incorrectly.
![](https://cdn.steemitimages.com/DQmaGzGuQfNFfPFeL9KFZxqArQuMyAGx8H6NARkxKaPgnhy/Screen%20Shot%202018-12-30%20at%203.43.56%20AM.png)
> https://steemit.com/@ned Nop, Ned is not 70 yet.

**Comment by economicstudio** [comment]
Here I made the fix: https://github.com/busyorg/busy/pull/2146

**Comment by Sekhmet** [comment]
Fixed in #2146.
