### ISSUE TITLE
Busy upvote error

### ISSUE THREAD

**Issue by worldfinances** [busyorg/busy#2171]
Usually, busy bot upvoted your post that you wrote on its site during first 20 minutes from publishing. Now it's few hours from when I published mine, and nothing happened. Also, I looked around on other posts with busy tag, published in last day or two, and looks like busy bot just stopped working. Anyone knows anything about that, or if there is a fix in a work? 

Oh, and @busy.pay has 100% voting AND RC mana. So it's surely not working at the moment

**Comment by worldfinances** [comment]
504 Gateway Time-out

**Comment by economicstudio** [comment]
unfortunately it's dead again after a short resurrection.

Either STINC or Busy should better provide followers_mvest by themseleves.

I made a proposal for Hivemind: https://github.com/steemit/hivemind/issues/185

**Comment by worldfinances** [comment]
Now steemDB Offline for Maintenance. You think this will take a long time?

**Comment by economicstudio** [comment]
Well, it depends on jesta :) In the long run, there should be independent db.

**Comment by economicstudio** [comment]
Now it's working and completely independent of steemdb https://github.com/busyorg/busy-bot/commit/325eeb70ba62eabfb06b678f417ec700d63e3246

Thanks a lot @Sekhmet for making this! (Special thanks to jesta for your hard work so far)
