### ISSUE TITLE
Like post randomly turns on

### ISSUE THREAD

**Issue by themarkymark-steem** [busyorg/busy#2186]
#### Expected behavior

Like Post setting save

#### Actual behavior

Like Post turned on without me ever going into settings out of nowhere.  I turn it off, and next post it's on again. 

#### How to reproduce

Make a post, like post will randomly turn on and vote at 0 minutes.  Ideally, this feature should be removed since HF20 as it throws away all curation rewards even if you self vote as votes at 0 minutes get 100% of curation rewards destroyed.

Chrome
Windows 10 Pro

**Comment by economicstudio** [comment]
I strongly agree. This also happened to me so many times. Seems they'll remove the like option: https://github.com/busyorg/busy/pull/2187

**Comment by Sekhmet** [comment]
This option has been removed.
