### ISSUE TITLE
Unable to login on busy.org. Error in console

### ISSUE THREAD

**Issue by mightypanda-x** [busyorg/busy#2200]
#### Expected behavior

When logging in using steemconnect, I should be logged in on busy.org site.

#### Actual behavior

Clicking on login and going through the login process doesn't login a user.

#### How to reproduce

(This seems to be an isolated issue affecting some users)
1. Go to busy.org in a incognito window and click on login.
2. Enter login details on steemconnect login page.
3. After redirect to busy.org, notice that user is still not logged in.

#### Recording of bug
There seems to be console log error in a js file that could be related to this issue.
```js
this.documentBodyInputs = Array.from(document.body.querySelectorAll(this.inputSelector)),
```
![ezgif com-video-to-gif (4)](https://user-images.githubusercontent.com/13856451/54459206-30394d80-4723-11e9-96de-9f021f7ac3c2.gif)

#### Extra details
I tried logging in using my other account in chrome incognito window and that worked fine but logging in with mightypanda isn't working. This seems related to some attribute of an account.

* Browser: Chrome Version 69.0.3497.100 (Official Build) (64-bit)
* Operating system: OSX 10.11.6
* Version: 2.5.6

**Comment by bonustrack** [comment]
@mightypanda-x This is an issue with steemconnect, it should be resolved by now.
