### ISSUE TITLE
[perceived performance] Splash Screen, Application Shell or Server-side Rendering

### ISSUE THREAD

**Issue by yamadapc** [busyorg/busy#26]
Currently we show a blue screen while loading, which may bring bad memories from the dark ages of personal computing to users.

I'd show an application shell directly, through server-side rendering. Then if it's easy enough to make fast queries on the server pre-fetch/pre-render everything before sending the initial payload.

---
### Notes on implementing server-side fetching

To actually implement proper server-side fetching, there needs to be a high-order component or decorator that wraps top-level components and declares the data fetching actions they should execute upon rendering.

The server-rendering path should then read these actions and dispatch them on a per-request store before rendering the response.

On Este.js this is done with a `fetch` decorator:

``` javascript
MyComponent = fetch(fetchUsers)(MyComponent);
```

Which is something like:

``` javascript
function fetch(...actions) {
  return function(WrappedComponent) {
    return class Fetch {
      static fetchActions = actions;
      componentDidMount() {
        actions.forEach(action => this.context.store.dispatch(action))
      }
      render() { /*...*/ }
    }
  }
}
```

**Comment by adcpm** [comment]
Server side rendering i already in place, i'm closing this issue.
