### ISSUE TITLE
Imbalanced Font Size for Locale (kor)

### ISSUE THREAD

**Issue by clayop** [busyorg/busy#299]
Font in Korean is too big (probably needs to be reduced about 20~25%) I will take a screenshot and post soon.

**Comment by clayop** [comment]
![2017-02-02 2](https://cloud.githubusercontent.com/assets/9971632/22543827/18d19c5c-e8e7-11e6-8b03-a973db1aa3ce.png)

**Comment by bonustrack** [comment]
We changed the font, does it look better for you in the new design? @clayop 
![image](https://user-images.githubusercontent.com/16245250/31565883-9af60dc6-b092-11e7-8b33-01a94cb3e032.png)

**Comment by clayop** [comment]
Yep I like the new design.
