### ISSUE TITLE
Direct the logged out users to the login page when they hit Comment

### ISSUE THREAD

**Issue by tibonova** [busyorg/busy#315]
Users can start writing a comment without being logged in, but they cannot submit it, which may cause frustration.

**Comment by p0o** [comment]
@tibonova Is this only happens in case of #339?

**Comment by tibonova** [comment]
It happens in post view. 
I'm logged out. When I hit the comment button, I can start a comment. I cannot send it with Enter, because I'm not logged in, and there are no hint that I should do it.

**Comment by sirrius-a-b** [comment]
This is no longer relevant because the comment textarea and button are not showing up anymore for logged out users. I think this can be closed.

**Comment by Sekhmet** [comment]
Right, also related to #803.
