### ISSUE TITLE
Message Preview not clickable

### ISSUE THREAD

**Issue by kharoof** [busyorg/busy#316]
When scrolling through posts on my phone the message preview text is not clickable. (Marked in black below in a screenshot from my phone)

I think the UX would be more intuitive if this was clickable.

![screenshot_20170203-215410](https://cloud.githubusercontent.com/assets/7195323/22610168/106df8a0-ea5c-11e6-9178-2d505cc9663f.png)

**Comment by bonustrack** [comment]
Closed on new-design here: https://github.com/busyorg/busy/pull/565/commits/0e8f5a90e7f0858917260621cd6ade234b6a0e0a
