### ISSUE TITLE
Need Refresh page after posting a comment to display

### ISSUE THREAD

**Issue by mynameisek** [busyorg/busy#332]
We should see it display directly.
Now i see comment count updated but only after Refresh page F5 we can see it

**Comment by snowflake11** [comment]
This is happening for every new action created on the blockchain. F5 is required to actualize blockchain statut, every posts, likes,comments,posts information,etc..need a page refresh to update. It would be great if all the info could update just by changing pages.

**Comment by adcpm** [comment]
It's not the case anymore, now its automatically updated, i'm closing this ticket.
