### ISSUE TITLE
Posting article from mobile Editor category issue

### ISSUE THREAD

**Issue by mynameisek** [busyorg/busy#333]
There is an issue that allow multiple words on one category on mobile.
You can add a category name 'test 123' (with Space/separate word)

It is due on mobile to the way we're adding a category: it requires push enter Key to validate one category After typing it. It should normally not be possible to have a two word category name so After a Space we can Also validate thé category to avoid this issue

**Comment by bonustrack** [comment]
This has been solved in new design
