### ISSUE TITLE
Article's thumbnail should appear when sharing it on social media

### ISSUE THREAD

**Issue by tibonova** [busyorg/busy#337]
People are text-blind on social media, rarely stop at text+link shares. Also few bloggers would share the Busy link of their content, when they know that other UIs could handle this well.

It's a must, because other social media sites are good for spreading the word and attracting new users, and organic reach doesn't cost money. Shares are also a factor in SEO. Until Busy will be a well-known brand, people must find it somehow.

**Comment by adcpm** [comment]
It's now the case, this issue has been solved here: thehttps://github.com/busyorg/busy/pull/470 i'm closing this ticket.
