### ISSUE TITLE
Add tooltip with the time&date of submission

### ISSUE THREAD

**Issue by tibonova** [busyorg/busy#359]
#### Expected behavior

When I'm hovering the mouse on the time info, I'd like to see the time and date of the post. This is a well-known, widely used method to get that information.
Making a timestamp tooltip for the `X days ago` info could help. 

#### Actual behavior

When I want to know when a post was submitted exactly, I cannot do it on Busy. Hovering the mouse over the time info does nothing.

#### How to reproduce

Hover the mouse on the time info of a post.

* Browser: Firefox 51.0.1
* Operating system: Ubuntu 16.10

**Comment by bonustrack** [comment]
Closed on new-design here: https://github.com/busyorg/busy/commit/46d27e297ae1dfab2a359bab8430909a2658a035
