### ISSUE TITLE
Handling quick comment(er)s

### ISSUE THREAD

**Issue by tibonova** [busyorg/busy#362]
#### Actual behavior

Making two comments quickly (in 10s was tested) is possible seemingly, the second comments will appear in the UI, however, it won't be broadcasted to the blockchain.

#### Expected behavior

Either make available sending comments quickly (preferred), or restrict the comment submission in a short time frame after a comment, and give the user a friendly hint about it. 
If it is not a blockchain restriction, I bet on making available the 2nd comment as quick as possible despite any potential spam attacks (rules could be set against abusers later). 
Users' interaction could be quick in many times, e.g.:
`dunno↵`
`xd↵`

I've tested on Steemit as well, and they solved it with a message (with red letters, which color was a wrong choice IMO):
> You may only comment once every 20 seconds.

#### How to reproduce

1. Make two (or more) comments on the same post quickly  (like 10sec)
2. Refresh the page or check it on Steemd 

* Browser: Firefox 51.0.1
* Operating system: Ubuntu 16.10

**Comment by bonustrack** [comment]
It's a blockchain restriction `STEEMIT_MIN_REPLY_INTERVAL` with 20sec delay between each comment. We are showing an error message now when this happen like this:
![image](https://user-images.githubusercontent.com/16245250/27509360-199245ca-5925-11e7-9191-d0dd1010ae2c.png)
