### ISSUE TITLE
Give notifications for mentions in chat channels

### ISSUE THREAD

**Issue by tibonova** [busyorg/busy#365]
I've asked @adcpm about this in the # busy channel of steemit.chat (haha, there, because channel notifications work there), because I didn't know is this a bug or not. It seems this is not a bug but a **feature request**. 

#### Expected behavior

When someone mentions me in the chat channels, I want to get notifications about it.

#### Actual behavior

There is no notifications in the chat channels.

#### How to reproduce

Mention your B account with your A account and look for notifications in the A account.

* Browser: Firefox 51.0.1
* Operating system: Ubuntu 16.10

**Comment by bonustrack** [comment]
The chat has been depreciated in `new-design` i'm closing this issue.
