### ISSUE TITLE
Payout Details

### ISSUE THREAD

**Issue by kharoof** [busyorg/busy#368]
#### Expected behavior

Show Post Payout on Feed at all times as well as author payout after payouts have been made.
#### Actual behavior

Shows Expected Post payout until payment is received then shows author payout
#### How to reproduce

View Feed
* Browser: Google Chrome
* Operating system: Android on mobile device

**Comment by kharoof** [comment]
For experienced Steem users this is not an issue, but later as more people are attracted to the platform it will increase the risk that they they think there is some kind of scam. It can cause post payouts to change significantly on the feed without explanation.

**Comment by bonustrack** [comment]
This issue has been solved on new-design here https://github.com/busyorg/busy/pull/632
