### ISSUE TITLE
Comments and Parent Discussions Are Not Shown with Comment Link

### ISSUE THREAD

**Issue by clayop** [busyorg/busy#375]
Example: https://busy.org/steem/@clayop/re-abit-re-clayop-re-leesunmoo-re-timcliff-whales-can-the-community-buy-out-a-portion-of-your-influence-20170214t203017914z#@abit/re-clayop-re-abit-re-clayop-re-leesunmoo-re-timcliff-whales-can-the-community-buy-out-a-portion-of-your-influence-20170214t231224930z

Two things are needed:
1) Showing comments on a comment
2) Adding "Show parent discussion" and "Show original post" button.

**Comment by bonustrack** [comment]
This issue has been solved in new-design.
