### ISSUE TITLE
Autolinked URLs don't wrap properly within the bounds of a comment

### ISSUE THREAD

**Issue by pfunks** [busyorg/busy#429]
#### Expected behavior

URLs should wrap within the bounds of a comment

#### Actual behavior

They don't.

#### How to reproduce

* https://busy.org/steem/@pfunk/arguments-for-keeping-the-steem-reward-pool-whole#@mindhunter/re-l0k1-re-pfunk-re-deanliu-re-pfunk-arguments-for-keeping-the-steem-reward-pool-whole-20170323t120803260z
* https://busy.org/steem/@pfunk/arguments-for-keeping-the-steem-reward-pool-whole#@pfunk/re-beanz-re-pfunk-re-cryptoctopus-re-pfunk-arguments-for-keeping-the-steem-reward-pool-whole-20170324t082724425z

Browser: Firefox 52.0.1

**Comment by nkgokul** [comment]
The issue seems to be fixed already.

![screen shot 2017-08-03 at 3 08 49 pm](https://user-images.githubusercontent.com/1375897/28915815-f718d416-785d-11e7-9673-b61ce515adbb.png)

**Comment by bonustrack** [comment]
Closing this issue, it has been solved on this PR https://github.com/busyorg/busy/pull/394
