### ISSUE TITLE
Editing a post edited previously using steemit.com gives a blank post body

### ISSUE THREAD

**Issue by pfunks** [busyorg/busy#430]
#### Expected behavior

After editing via any Steem client, a post's text, code and formatting should be editable and shown when the edit button is pressed.

#### Actual behavior

The post body content box is empty when attempting to edit.

![image](https://cloud.githubusercontent.com/assets/22420130/24288428/513e294e-104b-11e7-8f63-91f37329c7c5.png)

#### How to reproduce

I posted this via busy.org first: https://busy.org/steem/@pfunk/arguments-for-keeping-the-steem-reward-pool-whole

I was not able to use certain formatting features with the busy editor, and also did not like the way Busy formatted spaces between paragraphs. So I edited the post using steemit.com. Attempting to edit it on Busy again reveals the bug.

* Browser: Firefox 52.0.1

**Comment by nil1511** [comment]
Related to https://github.com/adcpm/busy/issues/457

**Comment by bonustrack** [comment]
This issue has been solved in #729 on `new-design` branch
