### ISSUE TITLE
Chat screen is near impossible to click top navigation buttons.

### ISSUE THREAD

**Issue by ausbitbank** [busyorg/busy#437]
#### Expected behavior
When viewing the chat page, I should be able to scroll up and down and continue to navigate using the buttons at the top of the page. Viewport should not be pushed down because of new messages loading.

#### Actual behavior

Once I open the page and scroll up, the backlog loads - this pushes the view down slightly so navigation buttons are off screen. I scroll up to see them, more backlog loads and it gets pushed away - over and over. On a low performance machine its really difficult to scroll and click before the viewport is moved.

#### How to reproduce

View chat page, scroll down, scroll up to the top of the page - https://busy.org/messages/general

* Browser: Firefox 50.1.0
* Operating system: Fedora 23 template inside QubesOS

**Comment by bonustrack** [comment]
The chat has been depreciated in `new-design` i'm closing this issue.
