### ISSUE TITLE
Use default browser scroll on modal instead of div scroll

### ISSUE THREAD

**Issue by bonustrack** [busyorg/busy#456]
#### Actual behavior

Actually when we open a modal there will be a div `BusyModalBackdrop` with fixed position and scroll overflow. This scroll is not properly recognised on Chrome mobile (the address is not hidden on scroll).

#### Expected behavior

There should be a default browser scroll instead.

**Comment by p0o** [comment]
@adcpm may you describe the method or provide an example of how to do this? Many websites that I saw are using div scroll for modal.

**Comment by adcpm** [comment]
When user click for open modal, the interface frame should have a style overflow hidden and a fixed position. While the modal should not have a limited height or fixed position and appear over the interface frame. Facebook have a body scroll for their Note modal. You can test it by creating a long Note or look in Zuckerberg timeline on February 17 he posted a Note openable in a modal:  https://www.facebook.com/notes/mark-zuckerberg/building-global-community/10154544292806634/?pnref=story

**Comment by bonustrack** [comment]
This issue has been solved on `new-design` branch
