### ISSUE TITLE
Editing post, markdown image code is not editable

### ISSUE THREAD

**Issue by pfunks** [busyorg/busy#457]
#### Expected behavior

When editing a post or comment, I expect that the original markdown code would be shown and editable. Specifically I wanted to go back and edit the alt text on this post.

#### Actual behavior

Instead there is a broken image with the trash icon above it.

![image](https://cloud.githubusercontent.com/assets/22420130/24727719/b24ce650-1a1c-11e7-8576-6a65f9ebe7e7.png)

#### How to reproduce

Probably edit a post/comment with a markdown image.

* Browser: Firefox 52.02

**Comment by bonustrack** [comment]
This issue has been solved in #729 on `new-design` branch.
