### ISSUE TITLE
Tips open a Transfer page, should be a closable Modal

### ISSUE THREAD

**Issue by mynameisek** [busyorg/busy#468]
Tips button send user to Transfer page, but it should be a Modal instead, or having a back/close button.
![tips](https://cloud.githubusercontent.com/assets/8390894/25573015/7be03084-2e41-11e7-8130-b2eece8c1a80.gif)

**Comment by bonustrack** [comment]
I'm closing this issue, tip button has been depreciated in favor of transfer modal in new design.
