### ISSUE TITLE
Show alert when clicking on button action: "need to login" to Like/Upvote/Bookmark

### ISSUE THREAD

**Issue by mynameisek** [busyorg/busy#469]
Do same like we did with the Comment button, but with all other actions which require login (Like/Dislike/Bookmark-hide)
![image](https://cloud.githubusercontent.com/assets/8390894/25573099/52e3917a-2e42-11e7-9aa7-b9f5ab5edc12.png)

**Comment by sirrius-a-b** [comment]
This issue seems to be for v1 and it is already referenced for v2 here: #803 . Maybe this issue can be closed.
