### ISSUE TITLE
Wallet need to include Savings

### ISSUE THREAD

**Issue by mynameisek** [busyorg/busy#475]
#### Expected behavior
Show Savings + Total (include savings)

#### Actual behavior
No savings

#### How to reproduce
![image](https://cloud.githubusercontent.com/assets/8390894/25737747/b2959b10-3179-11e7-9850-984ecc1246ba.png)

![image](https://cloud.githubusercontent.com/assets/8390894/25737752/b67c74f6-3179-11e7-8ee8-6b0fba7e47ee.png)

**Comment by jm90m** [comment]
Closing this - New Wallet includes Savings & Est Account Value
