### ISSUE TITLE
Translations don't show up or do so in wrong language

### ISSUE THREAD

**Issue by thomashagg** [busyorg/busy#478]
#### Expected behavior

Clicking on different specific language in "Settings", should change all words into the new language

#### Actual behavior

Each language setting has its own set of issues. For example, in Swedish the "hours" and "minutes" since posted seem to display in Finnish and the "Replies" button still says Replies. 

When switching to German, the "Write", "Drafts" and "Bookmarks" buttons remain in English. The account page is almost entirely untranslated.

#### How to reproduce

Change language via the Settings tab.

* Browser: Google Chrome 57.0.2987.133
* Operating system: Windows 10

**Comment by bonustrack** [comment]
Closing this issue, it's not relevant for busy `new-design`
