### ISSUE TITLE
Paste markdown on Editor has some issues

### ISSUE THREAD

**Issue by mynameisek** [busyorg/busy#488]
#### Expected behavior
I paste my content as Markdown directly in the busy.org Editor, and found some issues or difference with Steemit, element that are not interpreted or dismissed

*** : horizontal line
** for bold ** : bold
[content] (url) : hyperlink on text 
! [] (imageurl) : image in this format (steemit)

#### Actual behavior
misinterpret or missing

#### How to reproduce
Write all cases as markdown in text and copy/paste into the busy.org Editor
![markdown](https://cloud.githubusercontent.com/assets/8390894/25927311/6dbe9f5c-35f5-11e7-8a78-74697b25df7b.gif)

**Comment by bonustrack** [comment]
This issue has been solved on new design
