### ISSUE TITLE
Busy I feel uncomfortable using.

### ISSUE THREAD

**Issue by kopasi** [busyorg/busy#492]
#### Expected behavior

팝업창을 닫는 X 버튼이 상단에만 있어 불편합니다.
이것을 하단에도 설치하거나 스콜바형식으로 처리하면 좋을거 같습니다.

The X button that closes the pop-up window is uncomfortable at the top.
It may be better to install it at the bottom or to process it in the form of a scorch bar.

#### How to reproduce

* Browser: 
* Operating system:

**Comment by mynameisek** [comment]
The User interface and design is being modified (probably for the next release) but right now you can also close the modal (pop-up) window by clicking on left/right side
I must admit this is non very convenient and should be changed. We're working on it thanks

**Comment by sirrius-a-b** [comment]
This might be an old issue and not relevant anymore, maybe we can close it? Or does anyone have some more details about this issue?

**Comment by bonustrack** [comment]
Yes this was an issue for Busy1, it's not relevant anymore i'm closing it.
