### ISSUE TITLE
Donation to Busy show error

### ISSUE THREAD

**Issue by mynameisek** [busyorg/busy#497]
When try to donate/Transfer to busy.org
![image](https://cloud.githubusercontent.com/assets/8390894/26124910/87c9f196-3a80-11e7-9ecd-ccf71787e7f2.png)

reported by @buzzbeergeek using Chrome

**Comment by adcpm** [comment]
I've not been able to reproduce the issue. I need to see the full error from user browser console. I will contact him.

**Comment by bonustrack** [comment]
Now the error show detailed message. This is related to SC2 repo https://github.com/steemit/sc2 i'm closing this issue.
