### ISSUE TITLE
docker file problem

### ISSUE THREAD

**Issue by alexgarciac** [busyorg/busy#502]
docker build runs ok

should run ok.

does not run ok

npm info it worked if it ends with ok
npm info using npm@4.2.0
npm info using node@v7.10.0
npm ERR! Linux 4.9.27-moby
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! path /package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/package.json'
npm ERR! enoent ENOENT: no such file or directory, open '/package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /root/.npm/_logs/2017-05-25T16_59_33_588Z-debug.log

How to reproduce: mac osx sierra 10.12.4 docker 17.03.1-ce-mac12 (17661)

* Browser: 
* Operating system:

**Comment by ficolo** [comment]
+1

**Comment by nil1511** [comment]
Can you check with this [Dockerfile](https://raw.githubusercontent.com/busyorg/busy/92a29a7e0e81f7c3e7f35df3606babf28a8e6ba3/Dockerfile)
