### ISSUE TITLE
profile images url is broken

### ISSUE THREAD

**Issue by imkimchi** [busyorg/busy#553]
#### Actual behavior
![image](https://user-images.githubusercontent.com/13452168/27469537-0f2e2612-582b-11e7-9808-f35eeef71578.png)

As you can see in the screenshot, every single profile pictures' url is broken.

#### How to reproduce

* Browser: Chrome, Safari both
* Operating system: macOS

**Comment by adcpm** [comment]
There was an issue with AWS which was not available on some locations, we've changed the location, it should work now.
