### ISSUE TITLE
Problem in signing up for new account in Steemconnect

### ISSUE THREAD

**Issue by damnthatbanana** [busyorg/busy#572]
#### Actual behavior

Hi, I signed up for a new Steemit account using steemconnect. The new username is theforaginchef . I didn't realise to copy the password before clicking the sign up button. 
The account is linked to my own steemit account username damnthatbanana
Is there any way to get into the account please? 

thanks

Daniel 

#### How to reproduce

* Browser: 
* Operating system:

**Comment by bonustrack** [comment]
Unfortunately it's not possible. You can't recover the new account if you don't have a the password.
