### ISSUE TITLE
Allow user to enable or disable NSFW content with a setting

### ISSUE THREAD

**Issue by kellyjanderson** [busyorg/busy#589]
#### Expected behavior

If a post is tagged NSFW it should not be shown by default. This can be configured by a setting in settings.

#### Actual behavior

Hard core porn is displayed on my work screen. 😮

#### How to reproduce

Go to the photography topic and scroll until your colleagues see hard core porn over your shoulder and report you to HR.

* Browser: Any
* Operating system: Any

**Comment by blueyedgeek** [comment]
@kellyjanderson, your `how to reproduce` section doesn't actually give any information about how this issue can be reproduced. `Go to the photography topic and scroll until my colleagues see hard core porn`?

**Comment by kellyjanderson** [comment]
@blueyedgeek goto https://busy.org/created scroll through the list until you come across a post tagged #nsfw the image from the post will be displayed. 

Post with NSFW content should be hidden by default. Without hiding NSFW content, people cannot use busy.org safely when they are at a coffee shop, at work or in any other environment where displaying nudity and pornography would be inappropriate.

For instance I was just scrolling through the active list in the photography section while waiting for a build to finish at work. I had forgotten about this issue, and up scrolled a naked women with her legs spread wide and her vulva prominently displayed on my screen at work.

Steemit.com has a NSFW presentation for posts tagged NSFW. By default you get a warning and can click to display the content. there is an option to always display NSFW content in the settings.
