### ISSUE TITLE
Settings to update Steemconnect permissions 

### ISSUE THREAD

**Issue by eminogrande** [busyorg/busy#601]
#### Expected behavior

Settings where i can update or remove steem permissions.

#### Actual behavior

I have to log out and log back in again to change my permissions. Also, there is a **bug** when i remove all permissions on login.

#### How to reproduce

1) Login, choose only one permission
2) No way to update permissions
3) Logout from busy.org
4) Login again and choose multiple (or all) permissions

Hint: if i don't select any permission, i get an error and login fails completely.

* Browser: Chrome
* Operating system: OSX

**Comment by Sekhmet** [comment]
This isn't something we can handle. This should be handled by SteemConnect.
