### ISSUE TITLE
Markdown Header titles not translating to target language.

### ISSUE THREAD

**Issue by eastmaels** [busyorg/busy#796]
#### Expected behavior

Should be translated to target language

#### Actual behavior

![image](https://user-images.githubusercontent.com/29425738/31575454-05454cfa-b11a-11e7-8bc2-9db48d7897c8.png)

Heading 1 to 6 not translating to target language. Remains as english.

#### How to reproduce

Change language to any language other than English. Create a post. Then click on The Tt dropdown icon. 

* Browser: Chrome
* Operating system: WIndows 10

**Comment by Sekhmet** [comment]
Hey.
It's already being worked on: https://github.com/busyorg/busy/pull/795

**Comment by eastmaels** [comment]
okay thanks. i'm not sure why it's not displaying in the list of issues.
