### ISSUE TITLE
Block this user should not display in own profile page

### ISSUE THREAD

**Issue by eastmaels** [busyorg/busy#797]
#### Expected behavior

"Block this user" should not display in own profile page.

#### Actual behavior

"Block this user" displays in own profile page.

![image](https://user-images.githubusercontent.com/29425738/31575627-b54a4620-b11d-11e7-9f76-f68ac92358ca.png)

#### How to reproduce

1. Go to profile page (My profile)
2. Click on the more icon (three dots)

* Browser: Chrome
* Operating system: Windows 10

**Comment by mktcode** [comment]
This also applies to "Transfer" (in the dropdown and the left sidebar).

**Comment by mktcode** [comment]
https://github.com/busyorg/busy/pull/852

**Comment by bonustrack** [comment]
This issue has been solved in https://github.com/busyorg/busy/pull/852
