### ISSUE TITLE
Already followed user appears among Interesting People after (re)loading the page

### ISSUE THREAD

**Issue by espoem** [busyorg/busy#810]
![int-people-known](https://user-images.githubusercontent.com/16621517/31609301-d6c523f4-b273-11e7-9d8c-64526a88a561.gif)

#### Expected behavior

Only users that I am not following should appear in *Interesting People* bar.

#### Actual behavior

A user that I am already following may appear in the bar.

#### How to reproduce

1. Go to `/trending` page. You need to load/reaload the page. Clicking the _News_ won't work.
2. Repeat step 1 until you see a user you are following.

* Browser: Chrome 61.0.3163.100
* Operating system: Windows 10

**Comment by ryanbaer** [comment]
Working on a fix for this

**Comment by Sekhmet** [comment]
Solved in #893.
