### ISSUE TITLE
Image upload sends cursor to the end of the draft and adds a blank line

### ISSUE THREAD

**Issue by espoem** [busyorg/busy#811]
![editor-cursor](https://user-images.githubusercontent.com/16621517/31610440-5bb6c550-b278-11e7-9fe1-597b7907a4b0.gif)

#### Expected behavior

Cursor should stay right after the uploaded image.

#### Actual behavior

The cursor jumps to the end of the draft and a blank line is added.

#### How to reproduce

1. Write some text in the editor.
2. Upload image before the text. (not at the end)
3. The cursor jumps to the end and a blank line is added.

* Browser: Chrome 61.0.3163.100
* Operating system: Windows 10

**Comment by ryanbaer** [comment]
I've taken this on, so please assign to me.
