### ISSUE TITLE
News (trending) page not accessible when logged in on mobile

### ISSUE THREAD

**Issue by espoem** [busyorg/busy#814]
![feed-category](https://user-images.githubusercontent.com/16621517/31618650-cf29a560-b292-11e7-80f9-cd578cabc3b1.png)

#### Expected behavior

To have an option to go to the News (trending) page.

#### Actual behavior

User sees only his own feed. He has to manually change the URL.

#### How to reproduce

1. Visit the site on mobile.
2. Log in.
3. You cannot go to the News directly.

* Browser: Brave 1.0.33
* Operating system: Android 7.1.2

**Comment by espoem** [comment]
The sort option is visible when you are in trending (active, ...).

![feed-category-2b](https://user-images.githubusercontent.com/16621517/31622465-c8c07a00-b29c-11e7-85e6-cfe176fd2da6.png)

**Comment by jm90m** [comment]
Looks like this is fixed on https://staging.busy.org

**Comment by bonustrack** [comment]
Closing this issue, it's possible to see trending page on 3 dot menu now.
