### ISSUE TITLE
Post tooltip overflows at top of the page

### ISSUE THREAD

**Issue by espoem** [busyorg/busy#818]
![image](https://user-images.githubusercontent.com/16621517/31626950-d543d808-b2ab-11e7-94c8-d1d2e320f390.png)

![image](https://user-images.githubusercontent.com/16621517/31626958-d9e7fa92-b2ab-11e7-94aa-0bcfde1b70bf.png)

#### Expected behavior

The tooltip should switch to bottom position when near the top of the screen.

#### Actual behavior

The tooltip overflows so some information may not be visible.

#### How to reproduce

1. Go to `/trending`
2. Scroll down so that the line with likes, comments and reward is at the top.
3. Hover over likes count or the reward.

* Browser: Chrome 61.0.3163.100
* Operating system: Windows 10

**Comment by Sekhmet** [comment]
This should work thanks to `autoAdjustOverflow` prop on Tooltip (which is true by default), but for some reason it doesn't work. I will withdraw myself from this issue, as someone might want to take a look at it.
