### ISSUE TITLE
where did the easy link to github go?

### ISSUE THREAD

**Issue by inquiringtimes** [busyorg/busy#820]
it should be big and bold so your testers aren't just taking the upvote and not knowing where to send issues to....
#### How to reproduce

* Browser: 
* Operating system:

**Comment by sirrius-a-b** [comment]
I think that this issue was reported on the wrong repository. This might have been intended for [utopian.io](https://github.com/utopian-io/utopian.io)

**Comment by inquiringtimes** [comment]
No, I mean, I used to find a link to GitHub on your beta site, and I didn't see it last time I used it.  Should be clearly visible on your test site, no?

**Comment by sirrius-a-b** [comment]
This might not be relevant since busy v2 exited private beta. Maybe this can be closed.

**Comment by Sekhmet** [comment]
@bonustrack what's your opinion on that?

**Comment by bonustrack** [comment]
Seem related to utopian i'm closing it.
