### ISSUE TITLE
Comment form should be focused and shown visibly after clicking the comment icon in post

### ISSUE THREAD

**Issue by espoem** [busyorg/busy#821]
![comments-focus](https://user-images.githubusercontent.com/16621517/31629419-dd34e7de-b2b3-11e7-8eed-6df114f1aeab.gif)

#### Expected behavior

Comment form is focused and visible.

#### Actual behavior

Comment form is focused but it may be pushed too far up and hidden.

#### How to reproduce

1. Open a post from `/trending`. (Any post with more comments)
2. Scroll down to comment icon. (Not that far so you won't see comment form.)
3. Click the comment icon.

* Browser: Chrome 61.0.3163.100
* Operating system: Windows 10

**Comment by jkarthionline** [comment]
I am working on this issue
