### ISSUE TITLE
Comments sorting options don't fit the line in some languages

### ISSUE THREAD

**Issue by espoem** [busyorg/busy#822]
![](https://i.imgur.com/Gi9wGim.jpg)
Czech language

![](https://i.imgur.com/Gw0dn3s.jpg)
English for comparison

#### Expected behavior

Comments sorting options don't overflow.

#### Actual behavior

With some languages, the sort options may overflow because the words are too long.

#### Steps to reproduce

1. Set Czech language. (It may occur with others too.)
1. Open a post on a mobile.
1. See comments.

- Browser: Brave
- Operating system: Android 7.1.2

**Comment by pareshUD** [comment]
I think its better to use dropdown for sorting in mobile @Sekhmet

**Comment by Sekhmet** [comment]
This is how I have done it in PR:
![image](https://user-images.githubusercontent.com/1968722/35797726-df893814-0a60-11e8-8ae3-268879bfb4aa.png)
You can test it there: https://busy-master-pr-1459.herokuapp.com/@adsactly/adsactly-spotlight-on-cryptocoins-komodo-kmd-9th-feature-private-coins
Is it okay?
