### ISSUE TITLE
Pages title, meta description, og:

### ISSUE THREAD

**Issue by bonustrack** [busyorg/busy#823]
When sharing a post of Busy `new-design` in Facebook or Discord i would like to see the image preview, a title, description of the post. Actually nothing has been implemented for it. The user profile pages also should show detail of user with avatar, name, about informations. 

Similar than what steemit does:
![image](https://user-images.githubusercontent.com/16245250/31633534-e9a966f2-b2ea-11e7-8c35-c032dd660bbc.png)

Should we enable server side rendering and use react-engine or react-helmet just create routes on express for single post url, profile and homepage and load some data from steem.js without having to make react run on server side.

**Comment by Sekhmet** [comment]
Fixed in #1089
