### ISSUE TITLE
Add space before an image

### ISSUE THREAD

**Issue by espoem** [busyorg/busy#826]
<img src="https://user-images.githubusercontent.com/16621517/31648828-238ac6ca-b310-11e7-94dc-2fc0a6057e19.png" height="240px"/>

#### Expected behavior

There should be a bigger vertical space between the text and the image.

#### Actual behavior

Sometimes the image is placed right after the text that comes before the image whithout any space.

#### How to reproduce

1. Go to `/busy/@busy.org/busy-new-design-and-multilanguage-call-for-translators`
2. Scroll down and see images

* Browser: Chrome
* Operating system: Windows 10

**Comment by bonustrack** [comment]
This issue has been solved
