### ISSUE TITLE
Bookmarks should be sorted by bookmark date from the most recent

### ISSUE THREAD

**Issue by espoem** [busyorg/busy#827]
<img src="https://user-images.githubusercontent.com/16621517/31649499-7a5afdd2-b313-11e7-959e-c288fcb9c4c8.gif" height="280px"/>

#### Expected behavior

Bookmarks should be sorted by the bookmark date from the most recent.

#### Actual behavior

Bookmarks are sorted by the post date. If you bookmark an old post, it doesn't appear at the top.

#### How to reproduce

1. Bookmark any post
2. Bookmark a post that is older than the one from step 1
3. The second bookmark is not at the top in bookmarks

* Browser: Chrome
* Operating system: Windows 10

**Comment by jm90m** [comment]
@bonustrack does API support this? I can't find a param in the posts that has bookmark date.

**Comment by bonustrack** [comment]
This issue has been solved in https://github.com/busyorg/busy/pull/858
