### ISSUE TITLE
Image copy paste from Windows (File) Explorer not working

### ISSUE THREAD

**Issue by espoem** [busyorg/busy#830]
<img src="https://user-images.githubusercontent.com/16621517/31671843-3539004e-b35b-11e7-8839-03cb2fb29577.gif" height="280px"/>

#### Expected behavior

Image should be uploaded in editor via copy paste method.

#### Actual behavior

Image can't be pasted into editor even though it was copied and can be pasted in the Explorer.

#### How to reproduce

1. Open editor
2. Copy an image from Windows Explorer
3. You can't paste it into the editor

* Browser: Chrome
* Operating system: Windows 10

**Comment by Ne3l** [comment]
The code for pasting images seems fine.

If you make a screenshot(Alt+ImprPant) then you can paste the screenshot both from context menu and Ctrl+v. 
The github comment editor seems to have same behaviour.

Any Linux/MacOs user can confirm if they can copy paste a image?

**Comment by bonustrack** [comment]
I can copy paste an image on my MacOs but not been able to reproduce it on Windows using VM. I know 2 people having this issue.

**Comment by ryanbaer** [comment]
Wanted to confirm how to reproduce via BrowserStack (for those who don't have a Windows machine)
Note: BrowserStack doesn't seem to let you right-click (context menu) outside of the browser you're in, so you can't right click on an image in Explorer to select Copy, but they do have a copy button available.

The most notable thing I've found is that this issue may not be confined to Busy. I'm able to produce the same issue with a site called [pasteboard.co](https://pasteboard.co/) which is a good way to test pasting in an image without having to login to Busy from the BrowserStack VM.

**Steps to Reproduce on BrowserStack**
1. Login to BrowserStack
2. Select Chrome 61 on Windows 10
3. Navigate to https://pasteboard.co
4. Download an image from somewhere - i.e. navigate to https://pixabay.com, right click on one of the images, and click Save As
5. When Chrome downloads the image, note that it appears in the Downloads pane at the bottom of the browser
6. Click on the arrow and select "Show in Folder"
![image](https://user-images.githubusercontent.com/11914327/32066846-f431b5fa-ba35-11e7-8fa0-2348b8f91f33.png)
7. Windows Explorer will open. Click on the image you just downloaded
8. At the top of Explorer, click the Home tab, which will contain a Copy button
![image](https://user-images.githubusercontent.com/11914327/32066870-129d6bc4-ba36-11e7-882e-ac3216e83a2d.png)
9. Click the Copy button to copy the image data to the clipboard
10. Return to Chrome
11. To attempt to paste the image into Chrome, either press Ctrl (or Command) + V, or click on the Chrome menu and click their Paste button

![image](https://user-images.githubusercontent.com/11914327/32066937-4492ceee-ba36-11e7-89b9-01e224661a40.png)


12. Notice that the website displays a message indicating that there was no data on the clipboard
![image](https://user-images.githubusercontent.com/11914327/32066954-53a888a6-ba36-11e7-8be6-1d8f32f9065a.png)

**Comment by Sekhmet** [comment]
Is this even supposed to work?
On Linux it copies file path, not file contents (we can't read arbitrary file from user's file system). I guess on Windows it might be familiar.

**Comment by Sekhmet** [comment]
I think it's impossible to implement in web application. We simply can't read every file from user disk.
