### ISSUE TITLE
Left panel (News, Feed, ...) hides when scrolling with Trending Topics expanded

### ISSUE THREAD

**Issue by espoem** [busyorg/busy#832]
<img src="https://user-images.githubusercontent.com/16621517/31686755-77aab7e8-b387-11e7-9b7d-3d8691f3908f.gif" height="280px"/>

#### Expected behavior

Left panel should stay at the spot. User should scroll only within the trending topics.

#### Actual behavior

When trending topics expanded the whole left panel moves. The News, Feed is not accessible when scrolled down.

#### How to reproduce

1. Go to `/trending`
2. Click "View more" at Trending Topics
3. Scroll down
4. News, Feed is going up
5. \* Click View less and View more again and the left panel is immediately moved

* Browser: Chrome
* Operating system: Windows 10

**Comment by karthik-awebon** [comment]
I am working on this issue

**Comment by karthik-awebon** [comment]
@espoem How would you expect it to work? The left panel should scroll when the mouse is over it and the News feed should scroll when the mouse is over it?

**Comment by Sekhmet** [comment]
@bonustrack what's your opinion on that?

**Comment by espoem** [comment]
@Sekhmet I think it is related to https://github.com/busyorg/busy/issues/1379 . It is still present in Busy

**Comment by Sekhmet** [comment]
I don't think that's related. That issue is a bug, but this one is suggestion (it was designed to work like this).

**Comment by espoem** [comment]
I don't really think it works as intended. Or at least it is really inconvenient.

https://streamable.com/mj66s

**Comment by Sekhmet** [comment]
It works as expected, but it has lots of bugs, I created an issue to track those: #1868
