### ISSUE TITLE
Search field for "Trending Topic"

### ISSUE THREAD

**Issue by TAMustafa** [busyorg/busy#837]
#### Expected behavior

There should be a search field that allows users to enter a Topic the user is interested in.

#### Actual behavior

Currently there is no search field available. The user can scroll down to select one of the "most popular topics" but not all topics are listed.

#### How to reproduce

It is not an issue but an improvement suggestion.

* Browser: N/A
* Operating system: N/A

**Comment by Sekhmet** [comment]
Is it something we want to implement?
@bonustrack
