### ISSUE TITLE
Long username pushes Follow button in Interesting People box

### ISSUE THREAD

**Issue by espoem** [busyorg/busy#840]
<img src="https://user-images.githubusercontent.com/16621517/31729557-9e6ccd5a-b42f-11e7-9cd7-cc5ac67560eb.png" height="280px"/>

<img src="https://user-images.githubusercontent.com/16621517/31729580-b1626e38-b42f-11e7-827b-28c2b4101141.jpg" height="280px"/>

#### Expected behavior

Username and the follow button should stay inside the box. Follow buttons should be aligned.

#### Actual behavior

Long username may push the button from its position. Sometimes (language dependent) the button overflows the box.

#### How to reproduce

1. \* Set language that has a long word in follow button.
1. Refresh the Interesting People list.
1. Repeat step 2 until you find a user with long enough name.

* Browser: Chrome
* Operating system: Windows 10

**Comment by jm90m** [comment]
should be fixed in here: https://github.com/busyorg/busy/commit/244f5ab45915b79ebd67388de0e8e58b4f82eeb7
