### ISSUE TITLE
Missing the Replies tab?

### ISSUE THREAD

**Issue by karencarrens** [busyorg/busy#841]
#### Expected behavior
I often go to my replies tab to see who I need to respond to. I can't seem to find it in this version. I only see the comments tab.

#### Actual behavior

![add a replies tab please](https://user-images.githubusercontent.com/32652555/31730456-965f5c0a-b3f7-11e7-89ef-fff6689e7184.JPG)

#### How to reproduce

* Browser: 
* Operating system:

**Comment by espoem** [comment]
Replies are at the top under the three dots for now.

**Comment by bonustrack** [comment]
Closing here we have already an issue for this suggestion https://github.com/busyorg/busy/issues/850
