### ISSUE TITLE
2 issues

### ISSUE THREAD

**Issue by karencarrens** [busyorg/busy#846]
#### Expected behavior

When I was in the replies section, I clicked Discover More People on the right, it showed more people, my replies section should have stayed intact. Instead, it says, Oops... empty feed.

#### Actual behavior
I am in REPLIES section....
![issue 1](https://user-images.githubusercontent.com/32652555/31740333-9d2f1fd8-b416-11e7-8060-414f68e25d4d.JPG)

I  hit the DISCOVER MORE PEOPLE and it changed to...

![issue 1b](https://user-images.githubusercontent.com/32652555/31740359-bb58264e-b416-11e7-9306-f991fea30da7.JPG)

 ## Two Issues

1.) It should have kept my Replies in the middle.

2.) In addition, from her.... after I hit Discover More People one time, and hit it again, it doesn't give me a new list of new people to review. In fact, nothing happens.

#### How to reproduce

* Browser: chrome
* Operating system: win 10

**Comment by espoem** [comment]
"Discover More People" is not implemented yet. Related to #812
