### ISSUE TITLE
Avatar or banner not loading

### ISSUE THREAD

**Issue by espoem** [busyorg/busy#847]
![image](https://user-images.githubusercontent.com/16621517/31740577-11d3adf0-b452-11e7-9b4d-e8f1e460f2aa.png)

![image](https://user-images.githubusercontent.com/16621517/31740584-1713a9f0-b452-11e7-83ab-390f12aace1c.png)

#### Expected behavior

Avatar and banner should load if they are set.

#### Actual behavior

Avatar or banner won't load even though they are set.

#### How to reproduce

1. Go to `/@ewkaw` or `/@papasmurf`
2. See that avatar or banner don't appear
3. Check that they appear on Steemit or Steemkr

* Browser: Chrome
* Operating system: Windows 10

**Comment by tonimese** [comment]
New user tudormese has a similar problem: Images from imgur don't lload on Busy and Steemit.
![image](https://user-images.githubusercontent.com/20820467/31842068-13d29d7e-b5f5-11e7-8bf4-dfafc09bd158.png)

**Comment by tonimese** [comment]
Their link may be pointing to the imgur page instead of a .jpg file

**Comment by bonustrack** [comment]
The profile and cover image of `@tudormese` account lead to a page and not a picture `https://imgur.com/UkxIBpl`, the user should update his account profile with a working image url like `https://imgur.com/UkxIBpl.jpg`. If it's working on Steemit it's probably that they are using an old cache.

**Comment by Sekhmet** [comment]
It's not bug. Users didn't set their avatars properly.
