### ISSUE TITLE
Suggestion: Make SBD default currency for transfers

### ISSUE THREAD

**Issue by espoem** [busyorg/busy#849]
<img src="https://user-images.githubusercontent.com/16621517/31742865-63b2c5f0-b459-11e7-98ae-9f215bd3c1a5.png" height="280px"/>

#### Expected behavior

SBD is default currency for transfers because most users send this instead of STEEM.

#### Actual behavior

STEEM is default currency for transfers.

**Comment by Sekhmet** [comment]
It doesn't seem to be popular idea. I guess that current default satisfies most users.
