### ISSUE TITLE
3 dots menu should be fixed under the header

### ISSUE THREAD

**Issue by adrianbucks** [busyorg/busy#853]
#### Menu from the right should stay fixed with the header under the 3 dots and should disappear after clicking on an option

The 3 dots menu should relate to the header and should stay fixed under the 3 dots button from the header.
It should also hide after choosing an option from the list
The same thing goes for the notifications

#### Actual behavior

Now if I click the 3 dots to bring up the menu and then decide to scroll the page before I chose one of the options that menu scrolls up with the page.
Secondly, if I bring up the menu by clicking on the 3 dots and then selecting an option the page updates the content but the menu remains visible until I click outside it
Here's a screenshot
![busy](https://user-images.githubusercontent.com/5214088/31761446-c83e7ff4-b4af-11e7-91d2-788f78714627.png)

#### How to reproduce
I'm browsing with Chrome on Windows 10 and noticed the behaviour on the homepage but I reckon it relates to all the other pages too

* Browser: Chrome
* Operating system: Windows 10

**Comment by 4leem** [comment]
Is this issue still relevant? I guess the UI has been changed now and the sidebar is different. @bonustrack Can you please validate ?

**Comment by espoem** [comment]
![menu](https://user-images.githubusercontent.com/16621517/32059938-cb4d2ef2-ba6d-11e7-977d-4b0aac321095.gif)

**Comment by 4leem** [comment]
@espoem Thanks for the screen. I can do the fix but I need to locate the appropriate JS/JSX file. I'll raise a PR once this is fixed.

**Comment by sirrius-a-b** [comment]
I thought that this is a quick fix if I change the trigger from `click` to `hover`. Then I saw that on small screens this raises a bug where you hover and the menu appears on the bottom, and when you try to reach the bottom menu, it will vanish :)

It would be useful if we could set the trigger to `hover` on screens >767px and to `click` otherwise.
Maybe this could help https://www.npmjs.com/package/redux-responsive ?

**Comment by Sekhmet** [comment]
@sirrius-a-b we have responsive reducer but it's not used and needs updating (breakpoints are different):
`src/vendor/responsive.js`
