### ISSUE TITLE
Suggestion: layout change for arabic language

### ISSUE THREAD

**Issue by sweever** [busyorg/busy#854]
#### Expected behavior

layout change for arabic language 

#### Actual behavior

all layouts are in left , it should be on right cus in arabic we read from right to left not like others languages

#### How to reproduce

look at facebook ;
*
![2017-10-19_123953](https://user-images.githubusercontent.com/18384831/31773472-cdc6e288-b4da-11e7-94a0-f898191264be.png)
*
![2017-10-19_124055](https://user-images.githubusercontent.com/18384831/31773474-ce12b5e6-b4da-11e7-9a98-e81c70987164.png)

**Comment by Sekhmet** [comment]
Fixed in #1316
