### ISSUE TITLE
Show language selection for unlogged users

### ISSUE THREAD

**Issue by espoem** [busyorg/busy#859]
#### Expected behavior

There should be an option to select a language for users that are not logged in. It should be placed next to "Sign Up | Log in" at the top.

#### Actual behavior

User can't select a language if they aren't logged in.

**Comment by bonustrack** [comment]
The way i see it there will be a dropdown in the right of the top nav next to signup and signin:
![language](https://user-images.githubusercontent.com/16245250/34454052-fa0e58d8-ed94-11e7-92a2-ab979ad02aff.gif)
We can show the full name of the locale example "English ▾" without the flag.
We should use localStorage to store selected language of the user. 

@pareshUD can you make a mockup for it using our current design?

**Comment by Sekhmet** [comment]
Topnav is already pretty crowded on mobile:
![image](https://user-images.githubusercontent.com/1968722/34454879-7c596f42-ed74-11e7-9efe-8272ce5eb16c.png)

btw. I think it would make sense to use classic `select` instead of antd one. The one that comes from antd is not based on native select and it doesn't work to well on mobile (while native `select` shows on full-screen which is way easier to use for user).

**Comment by bonustrack** [comment]
Hum we don't have much flexibility to customize style if we use `select`. AFAIK antd dropdown are working well on mobile.

**Comment by pareshUD** [comment]
![change language hover](https://user-images.githubusercontent.com/8911074/34828207-d1704e78-f702-11e7-9de1-95eec4b4ea23.png)
![change language mobile](https://user-images.githubusercontent.com/8911074/34828210-d1b8d1ac-f702-11e7-9631-51a6eba53e65.png)
![change language](https://user-images.githubusercontent.com/8911074/34828212-d1f65b4e-f702-11e7-8f8f-168d87dfd5d6.png)

Check this out

**Comment by bonustrack** [comment]
@pareshUD do you have it for unlogged? How it look if we have 20 languages?

**Comment by pareshUD** [comment]
![change language hover](https://user-images.githubusercontent.com/8911074/34937670-a8bf5152-fa0b-11e7-9046-52d274e9219c.png)

**Comment by jm90m** [comment]
Latest design from @pareshUD looks fine, but I think we would need all those flags supplied to us in SVG for each one specifically.

**Comment by pareshUD** [comment]
@jm90m No worries I will get you the flags for all language.

**Comment by bonustrack** [comment]
I'm not too fan of using a flag for a language. A language doesn't have flag. Facebook twitter or others dont use flag aswell on languages.

**Comment by jm90m** [comment]
so should we just display the text? 'English' or abbrev 'EN'

**Comment by pareshUD** [comment]
![change language](https://user-images.githubusercontent.com/8911074/35613668-c6881eb0-0692-11e8-96dc-ddd0f7eb2e15.png)
