### ISSUE TITLE
bug: post layout issue steemit vs. busy

### ISSUE THREAD

**Issue by irikefee** [busyorg/busy#860]
#### Expected behavior

There should not be any difference in visualization of the same post in between the two platforms when using the same laptop, the same browser and with the same zoom settings.

#### Actual behavior

The post visualised in busy vs. the one in steemit (where was originally created) was not readable. The layout was lloking great in steemit, even if the entire post was written in <sup> code to reduce space and for a better reading experience.

#### How to reproduce

Here below I'll paste the original post source code to be analized by some expert:

Ciao Steemiani,
oggi vi propongo un post dove spiego come usare l'exchange Etherdelta.
E' un po macchinoso, e le prime volta che lo vorrete usare esperimenterete un po' di dificoltà; ma non è poi così difficile. Inoltre aspettatevi una lentezza straziante nelle transazioni...ma purtroppo alcuni token, specialmente in fase di lancio, vengono listati solo qui e volenti o nolenti bisogna imparare ad usarlo.

<div class="pull-right"><img src="https://steemitimages.com/950x950/https://steemitimages.com/DQmXUDxDwxQNc83gTVND1qNYPdGdFkLhWfwsuAvEYEexYtr/Screen%20Shot%202017-10-14%20at%2001.50.41.png" /></div>
<sup>Dovrete associare un wallet per poter operare sulla piattaforma. Potrete farlo in due modi differenti:
<ol>
<li>utilizzare un ERC20 wallet creato anticipatamente, per esempio Myetherwallet, di cui disponete la chiave privata.
Cliccare <code><sup>Select account</sup></code> in alto a destra dello schermo, quindi <code><sup>Import account</sup></code> dal menu a tendina</li>
<li>Oppure creare un nuovo ERC20 wallet direttamente su Etherdelta cliccando <code><sup>New account</sup></code> dal menu a tendina. Se sciegliete di creare un wallet con questa opzione, assicuratevi di salvare la vostra chiava privata.</li>
</sup>
</ol>

<div class="pull-right"><img src="https://steemitimages.com/950x950/https://steemitimages.com/DQmaerwM1ZxaX86uPRcqoj9GqBF44DA26ESJAhHNMq4oHxr/Screen%20Shot%202017-10-14%20at%2001.51.44.png" /></div>

Se avete deciso di utilizzare la prima opzione, vi apparirà una finestra pop-up dove dovrete inserire l'indirizzo del vostro ERC20 wallet e la chiave privata corrispondente. A questo punto cliccate <code><sup>Import account</sup></code> per caricare i dati del vostro wallet nella cache.
NOTA:
La chiave privata è un dato sensibile del vostro wallet. Essa non deve essere scambiata con NESSUNO e deve essere conosciuta SOLO dal proprietario. Quando per vari motivi, tipo svuotamento cache oppure riavvio del browser in un determinato sito vi viene richiesto l'inserimento della vostra chiave privata, controllate che l'indirizzo nella barra indirizzo del vostro browser non sia cambiato e corrisponde con il sito da voi visitato. L'utilizzo consapevole della chiave privata è responsabità dell'utente. Maneggiare con cautela.
</sup>
</p>

<div class="pull-right"><img src="https://steemitimages.com/950x950/https://steemitimages.com/DQmQVLvpEz2E61H6PYEiFNosw7UKKDXEZyxUNz5S11aXWUX/Screen%20Shot%202017-10-14%20at%2001.53.11.png" /></div>

Dovrete ora selezionare il token che desiderate comprare o vendere, supponiamo sia il token <code>ELITE</code>. Questa operazione puó essere effettuata indifferentemente in due modi:
1. Cliccate sul simbolo del token in alto a sinistra dello schermo; in questo caso <code>ELITE</code> token, selezionando dal menu a tendina il simbolo (nome) del token
2. Cliccate sulla coppia <code>ELITE/ETH</code> sciegliendola dalla lista dei volumi registrati sulla piattaforma Etherdelta

<div class="pull-right"><img src="https://steemitimages.com/950x950/https://steemitimages.com/DQmcKU4sMmaR4RBuhEeuRve5xU1aKitjTUFio7eATxJFTdG/Screen%20Shot%202017-10-14%20at%2001.53.37.png" /></div>

A questo punto Etherdelta controllerà se sul vostro wallet avete il token selezionato e in caso positivo aggiornerà il bilancio con la quantità corrispondente sotto la colonna WALLET nella sezione BALANCE.
Come potete notare la posizione di default è impostata nella scheda DEPOSIT e inoltre troverete sempre i bilanci del token selezionato e di Ethereum in quanto la piattaforma è basata su di esso e tutte le quotazioni sono espresse in riferimento a questa cryptovaluta. 
NOTA:
I token dovranno essere trasferiti dal vostro ERC20 wallet alla piattaforma Etherdelta per poter effettuare qualsiasi operazione. Questo significa che dovrete avere un minimo di bilancio in ETH sul vostro wallet in modo da poter pagare il GAS necessario per effettuare il trasferimento.

<div class="pull-right"><img src="https://steemitimages.com/950x950/https://steemitimages.com/DQmTkLokCBcL6Naj4G58YqVi3dhJMZLNwkJYuHmv4dmCRmh/Screen%20Shot%202017-10-14%20at%2001.53.37.png" /></div>

Per effettuare il trasferimento dei vostri token sulla piattaforma Etherdelta procedete come segue:
1. Cliccate sulla casella <code>Amount</code> e inserite un valore numerico. Questa sarà la quantità di token che verrà trasferita al completamento della transazione.
2. Cliccate ora sul pulsante di conferma <code>Deposit</code> per avviare la transazione.

NOTA: Evitate di cliccare ripetutamente e aspettate qualche secondo prima di giudicare se la transazione sia avvenuta o meno. La piattaforma è molto lenta ma i click vengono registrati quindi rischierete di pagare due volte il GAS per la stessa transazione.

<div class="pull-right"><img src="https://steemitimages.com/950x950/https://steemitimages.com/DQmcrYm6it6YKJGAmLU5RBNyzfWSFNnhNEmwk8twxKvCWC1/Screen%20Shot%202017-10-14%20at%2002.09.10.png" /></div>

Se la transazione è stata registrata, la piattaforma vi segnalerà con un messaggio pop-up la sua avvenuta e vi indicherà i dettagli della transazione che potrete utilizzare per rintracciarla sulla rete della blockchain.

<br>
<br>

<div class="pull-right"><img src="https://steemitimages.com/950x950/https://steemitimages.com/DQmfUTxKMC4rXjkFZ8p2qef1iDNKEZFNhHPCZKRboy7k6o7/Screen%20Shot%202017-10-14%20at%2002.11.32.png" /></div>

Se il trasferimento è stato registrato con successo sulla piattaforma Etherdelta dovreste trovarvi nella sezione MY TRANSACTION sulla scheda TRADES la transazione allo stato di PENDING. Questo significa che il trasferimento è in viaggio nella blockchain e dopo vari blocchi di verificazione verrà approvato e i token trasferiti dal vostro wallet alla piattaforma Etherdelta. Il tempo di attesa di questa operazione dipende da alcuni fattori come: impostazione del GAS, congestionamento della blockchain e della piattaforma Etherdelta.
A questo punto non dovrete far altro che attendere.

<div class="pull-right"><img src="https://steemitimages.com/950x950/https://steemitimages.com/DQmQPqUW8C5N13bNxFEF2ZcUfFSXFLVF7s2SDgT3pxY8MJr/Screen%20Shot%202017-10-16%20at%2008.39.54.png" /></div>

Dopo aver atteso pazientemente per l'approvazione della vostra transazione, la quale puó richiedere anche parecchie ore, dovreste essere in grado di visualizzare nella sezione BALANCE alla scheda DEPOSIT sotto la colonna ETHERDELTA il bilancio degli <code>ELITE</code> token che avete trasferito dal vostro ERC20 wallet sulla piattaforma.
<br>

Come potete notare il bilancio degli <code>ETH</code> nel vostro wallet diminuirà in funzione del GAS pagato per poter effettuare la transazione.
<br>
<br>

Ora che i vostri token sono sulla piattaforma Etherdelta potete venderli. Per farlo ci sono due modi:

<div class="pull-right"><img src="https://steemitimages.com/300x300/https://steemitimages.com/DQmUgXnkvfykcFCf8xM5zC9oF1x9L1UNCpKgka5Dc7xQ2Xa/Screen%20Shot%202017-10-16%20at%2010.06.50.png" /></div>
<div class="pull-right"><img src="https://steemitimages.com/950x950/https://steemitimages.com/DQmPUWcK9NUakk52h9Zoq2LPRvuRKFmZmVCk8JbDpx5pA7s/Screen%20Shot%202017-10-16%20at%2009.35.03.png" /></div>

1. Nella sezione ORDER BOOK troverete il registro degli ordini che altri utenti hanno già inviato sulla piattaforma; in rosso vedrete listati gli ordini di vendita e in verde gli ordini di acquisto. Se volete vendere, selezionate un ordine di acquisto con il prezzo a cui siete disposti vendere e assicuratevi che la quantità cui il compratore sia disposto comprare sia piú alta di quella che voi volete vendere. Vi apparirà una finestra pop-up con i dettagli della transazione, dove, se volete, potrete modificare la quantità cliccando sulla tabella <code>Amount to sell</code> e quindi confermare l'operazione cliccando su <code>Sell</code>.

<div class="pull-right"><img src="https://steemitimages.com/950x950/https://steemitimages.com/DQmebJgrfyjWCFVVeVaHFpJbrZLVQGbG28nL1DsgPfNrX9b/Screen%20Shot%202017-10-16%20at%2009.36.07.png" /></div>

<br>

2. Un altro metodo è quello di inserire i parametri della transazione manualmente. Nella sezione NEW ORDER cliccate sulla scheda <code>Sell</code>, quindi impostate la quantità di <code>ELITE</code> token e il prezzo di <code>ELITE/ETH</code> a cui volete venderli.
Potete impostare il tempo di scadenza <code>Expires</code> cliccandoci sopra e inserendo un valore. Il valore standard di 10000 blocchi corrisponde a circa 24 ore.
A questo punto confermate la transazione cliccando su <code>Sell</code>.
<br>

Le FEES verranno calcolate in automatico e saranno pagate con parte dei token che state vendendo.

<div class="pull-right"><img src="https://steemitimages.com/950x950/https://steemitimages.com/DQmc1hBmJwkpCo9FRGvr2zmkZaF4NqiY6dC98WQBVk5FJRq/Screen%20Shot%202017-10-16%20at%2010.39.17.png" /></div>

Se la transazione è stata registrata, la piattaforma vi segnalerà con un messaggio pop-up la sua avvenuta e vi indicherà i dettagli della transazione che potrete utilizzare per rintracciarla sulla rete della blockchain.
Nella sezione MY TRANSACTION visualizzarete quindi una transazione in PENDING fino a che non verrà confermata sulla blockchain. 

<div class="pull-right"><img src="https://steemitimages.com/950x950/https://steemitimages.com/DQmdgztBJ2fFMfy19JWGfaq6E3wWLtR2mCvVmYjrLmUj24n/Screen%20Shot%202017-10-16%20at%2010.45.11.png" /></div>

<br>

Ad avvenuta conferma della transazione noterete che nella scheda MY TRANSACTION la transazione che fin ora era in stato di PENDING ha aggiornato i dati, mostrando tutti i dettagli dell'operazione.
<br>

<div class="pull-right"><img src="https://steemitimages.com/950x950/![Screen Shot 2017-10-16 at 10.44.57.png](https://steemitimages.com/DQmbcFBfmFcUAC5BWzY9E4h9ekWVdYnvM31PPht2mGgsgmX/Screen%20Shot%202017-10-16%20at%2010.44.57.png)" /></div>

Potrete ora confermare che nella sezione BALANCE alla scheda DEPOSIT la quantità corrispondente degli <code>ELITE</code> token in <code>ETH</code> è stata depositata sotto la colonna ETHERDELTA.
<br>

Ora volendo potrete prelevare i vostri <code>ETH</code> dalla piattaforma Etherdelta e trasferirli sul vostro ERC20 wallet.
Per fare questo, andate nella sezione BALANCE alla scheda WITHDRAW e operate in modo simile a come descritto piú in alto per i token, ma questa volta cliccate sulla riga corrispondente agli Ethereum.
<br>

Spero che questa guida vi sia stata di aiuto e vi ringrazio per aver letto!

<br>

https://steemitimages.com/0x0/https://s4.postimg.org/i1209fve5/DQmc_GTg_E9zt_Q7_Qm_WESy_E7u_Vq_Lr_Uqfb_Aa1fs_TCod6dms_FYj_P.gif

**Comment by irikefee** [comment]
you can find the origina post on steemit with the correct layout here:
https://steemit.com/cryptocurrency/@irikefee/come-utilizzare-etherdelta-exchange-ita

**Comment by sirrius-a-b** [comment]
#### This bug might be irrelevant.

Upon looking at the example post's html code, it seems that the post's HTML does not follow the standard HTML/DOM specifications.

https://steemit.com/cryptocurrency/@irikefee/come-utilizzare-etherdelta-exchange-ita

In the article there are `ol` `li` `div` and `img` tags inside `sup`. This is not correct HTML.

![sup-html-issues-small](https://user-images.githubusercontent.com/32915194/32331943-7b94ff4e-bfe4-11e7-9b3e-1850d982feda.png)

The `sup` element is not meant to be used like that.

Here are the specifications for the `sup` tag: https://www.w3.org/TR/html5/text-level-semantics.html#the-sub-and-sup-elements

At 'Content Model' it is pointed to 'Phrasing content': https://www.w3.org/TR/html5/dom.html#phrasing-content-1
Which lists the tags that `sup` supports: `a abbr area (if it is a descendant of a map element) audio b bdi bdo br button canvas cite code data datalist del dfn em embed i iframe img input ins kbd keygen label map mark math meter noscript object output progress q ruby s samp script select small span strong sub sup svg template textarea time u var video wbr text`

Of course, even if this is not correct HTML, the browser will still try to render it, and with CSS tweaks it can be made to look decent.

It's just that this is not supported and you cannot be sure that different browsers/devices will render it in the same way.

That is why I think that this bug might be irrelevant, and if it were to be actually be "fixed", it will come and haunt the future devs :)

**Comment by Sekhmet** [comment]
Problem with using hacks like the one in this post is that they might work in some clients, but won't in others. We can't support every hack someone comes up with.
We recommend using standard features and in a way that is semantically correct, otherwise things might now work the way author intended.
