### ISSUE TITLE
Add post reading time

### ISSUE THREAD

**Issue by espoem** [busyorg/busy#862]
#### Expected behavior

User can see an estimated time to read the post.

<img src="https://user-images.githubusercontent.com/16621517/31811768-12e1109a-b581-11e7-8901-baeec62482fe.png" height="280px"/>

**Comment by jm90m** [comment]
As I posted in #1094, I'm not sure if this is useful at all.. It would be more useful if it was on the article itself or on the article preview.

See like in medium:

![screen shot 2017-11-21 at 8 45 06 am](https://user-images.githubusercontent.com/5067716/33075668-3fc8e4f4-ce98-11e7-82e8-831e279fd137.png)
![screen shot 2017-11-21 at 8 45 09 am](https://user-images.githubusercontent.com/5067716/33075669-3ff36d96-ce98-11e7-8377-cd84a88bd3da.png)
