### ISSUE TITLE
Busy Editor Issue: Can't stop blockquote after using a bulleted blockquote.

### ISSUE THREAD

**Issue by codename-littleboy** [busyorg/busy#863]
#### Actual behavior

I recently wrote a feature request article via utopian.io [[Link](https://nd.busy.org/utopian-io/@littleboy/busy-org-feature-request-see-first)]. After I used markdown blockquote ">" on a bulleted text " - ", I couldn't stop the blockquote. Everything I wrote afterwards were blockquoted.

#### Expected behavior

The text written after the blockquote should not be included in the blockquote.

#### How to reproduce

Write to following in the editor to reproduce:

> - This is a test line
Some text here

< / br >

![image.png]
 (https://res.cloudinary.com/hpiynhbhq/image/upload/v1508490073/uju545rit7nx2thwpsrp.png)

[Note: Remove the spaces when writing in the editor.]

**Comment by espoem** [comment]
This happens because of `</br>` in the post. When removed it behaves as it should. The correct tag is `<br/>`. See the slash.

https://steemd.com/utopian-io/@littleboy/busy-org-feature-request-see-first

**Comment by bonustrack** [comment]
@codename-littleboy can you tell more how to reproduce the issue? I'm not able to reproduce it see: ![image](https://user-images.githubusercontent.com/16245250/31830382-3a97eb0e-b5ea-11e7-8268-a03a80ebe90e.png)

**Comment by codename-littleboy** [comment]
Yes, it was happening because of the </br> tag.
