### ISSUE TITLE
clicking on the comment button without login breaks it

### ISSUE THREAD

**Issue by bobinson** [busyorg/busy#864]
![2017-10-20_18-05-10](https://user-images.githubusercontent.com/18070249/31821159-c73ab1be-b5c1-11e7-83e9-32db559113e5.png)

**#### Expected behavior**

 The message should appear only once

**#### Actual behavior**

the message appears too many times in a stack form. Refer screen shot above.

**#### How to reproduce**

1. Go to busy.org in a Firefox container in firefox 57 beta
2. Click on the comment button on any of the posts.
3. Alwasy reproducable
4. Tried disabling uBlock Origin, Privacy Badget and Ghostery and the result remained same

* Browser:  57.0b9 (64-bit)
* Operating system:  macOS

**Comment by bonustrack** [comment]
Do you still experience this issue? I'm not able to reproduce it.

**Comment by 4leem** [comment]
This is still reproducible. Even in the chrome browser.

**Comment by sirrius-a-b** [comment]
The comment textarea doesn't show up anymore when not logged in. Maybe this can be closed.

Here is how it looks on the post page comment section when not logged in:
![not-logged-in-no-comment](https://user-images.githubusercontent.com/32915194/32910044-7ecf833a-cb08-11e7-9a75-daba663cb20b.png)

**Comment by Sekhmet** [comment]
This issue is related to Busy v1 will is no longer supported.
