### ISSUE TITLE
Be able to click on voted Users

### ISSUE THREAD

**Issue by sweever** [busyorg/busy#869]
#### Expected behavior

Be able to click on voted Users

#### Actual behavior

cannot click and check users who has voted on a post

#### How to reproduce

![2017-10-20_153346](https://user-images.githubusercontent.com/18384831/31826133-232718c0-b5ac-11e7-8a0d-7a568e6d3702.png)

**Comment by bonustrack** [comment]
This issue has been solved here https://github.com/busyorg/busy/pull/884
