### ISSUE TITLE
Busy doesn't load content on Opera Mini if data savings enabled

### ISSUE THREAD

**Issue by espoem** [busyorg/busy#887]
#### Expected behavior

Busy should load the content on Opera Mini even if the data savings option is enabled.

<img src="https://user-images.githubusercontent.com/16621517/31884263-d700578e-b7ec-11e7-8ea4-4ed272937e08.gif" height="280px"/>

#### Actual behavior

Busy loads content on Opera Mini only if the data savings option is disabled. If "high data savings" is enabled, the site loads but user cannot see any content. If "extreme data savings" is enabled, the site doesn't load at all.

- Data Savings __High__

<img src="https://user-images.githubusercontent.com/16621517/31884373-263c24ae-b7ed-11e7-8597-442b5f50a9ba.gif" height="280px"/>

- Data Savings __Extreme__

<img src="https://user-images.githubusercontent.com/16621517/31884403-3996a95c-b7ed-11e7-85e1-175521c5b370.gif" height="280px"/>

#### How to reproduce

1. Open busy on Opera Mini
2. Enable Data Savings
3. \* Reload the page

* Browser: Opera Mini 30
* Operating system: Android 7.1.2
* Phone: Moto G3 2015

**Comment by Sekhmet** [comment]
Busy relies heavily on web-technology. It got better thanks to SSR, but we can't guarantee same experience when using incompatible browsers (that are limiting some functionality by design).
