### ISSUE TITLE
Feed story loading: remove borders left, right and radius on small screen

### ISSUE THREAD

**Issue by bonustrack** [busyorg/busy#888]
When loading a feed there will be a container loader for the story. This container on small screen have border right and left and border-radius:
![image](https://user-images.githubusercontent.com/16245250/31890309-d8fdb9a6-b82c-11e7-8962-97d3be23027f.png)
We should remove these border and the border radius in small screen similar than what @mktcode did in #876

**Comment by mktcode** [comment]
I'll take care of that. :)
