### ISSUE TITLE
There may be double vertical space between an image and a paragraph

### ISSUE THREAD

**Issue by espoem** [busyorg/busy#892]
#### Expected behavior

Ideally, the space between an image and a preceding text should be consistent.

#### Actual behavior

There is double vertical space if the text and the image are each in their own paragraphs.

<img src="https://user-images.githubusercontent.com/16621517/31910163-f2b7b5d0-b83c-11e7-9110-d80aaa82dc19.png"/>

#### How to reproduce

1. Go to `/travel/@rosatravels/travel-gem-27-take-you-back-in-time-water-taxi-across-dubai-creek`
2. Compare with `/busy/@busy.org/busy-new-design-and-multilanguage-call-for-translators`

* Browser: Chrome
* Operating system: Windows 10

This is related to #826 and #882  

This post `/children/@breezin/what-s-a-mother-to-do` can be a test case. There are a lot of images in different locations.

**Comment by eastmaels** [comment]
Will look into it. This is due to `<p></p>` already adding a `margin-bottom` . An image inside another `<p></p>` will cause this issue to happen.

**Comment by espoem** [comment]
There are cases when an image is placed right after a header. I think we should keep the space between the header and the image. You can see an example here `/children/@breezin/what-s-a-mother-to-do`
