### ISSUE TITLE
My panoramic pictures were cut off when loaded onto my post. 

### ISSUE THREAD

**Issue by dreamingirwin** [busyorg/busy#897]
#### Expected behavior

I've loaded this type of picture on the steemit platform.   Usually it'll load the entire picture and just shrink it slightly so the entire thing is visible on the post. 

#### Actual behavior
When the picture loaded it was zoomed into the center.   I thought maybe it would change once posted,  but it posted just add displayed. 

![20171023_183054.jpg](https://steemitimages.com/DQmPYBp3woMpB8XW743BKZqBHibyFQ7Ygc4wo8axUsm7QyS/20171023_183054.jpg)

https://www.imageupload.co.uk/images/2017/10/25/Screenshot_2017-10-25-07-32-21.png That's what I thought they would look like

#### How to reproduce

* Browser: chrome
* Operating system: 
Samsung galaxy mini 4

**Comment by dreamingirwin** [comment]
![20171023_183224.jpg](https://steemitimages.com/DQmYhR8BFSyG7kbDWrpuymyWYW9Bc6chGqMKD6QsRuU5BN9/20171023_183224.jpg)

![20171023_182846.jpg](https://steemitimages.com/DQmcqb8HAeZSy2G6FGusqJBZJ5L53UxQzed4c4PUTyHCjam/20171023_182846.jpg)

![20171023_203412.jpg](https://steemitimages.com/DQmfAbBCLMPLdkGm2BoUXKtJU5i1sEf9ctSw6VNq4FY9irH/20171023_203412.jpg)

**Comment by dreamingirwin** [comment]
They all loaded cut off

**Comment by espoem** [comment]
Can you add a link to the post?

**Comment by karencarrens** [comment]
espoem, i saw you needed the link to dreamingirwin's post. 
 Here it is... https://steemit.com/life/@dreamingirwin/jump-off-in-stratford-ct-is-a-cool-place-to-bring-the-kids

**Comment by dreamingirwin** [comment]
Sorry guys.   I edited my post using steemit and reposted it with the updated pictures.   I only left one of the original pictures,  That were loaded through busy on the post.  Most of them loaded indirectly,  and the post couldn't stay that way.  Sorry for not seeing the comment.

**Comment by dreamingirwin** [comment]
Incorrectly

**Comment by Sekhmet** [comment]
@dreamingirwin hey, I posted those images from Busy and I think they are displayed properly:
https://busy.org/test/@hellosteem/test-post-897

**Comment by Sekhmet** [comment]
I can't see any bug on our side. I will close it due to inactivity.
