### ISSUE TITLE
Interesting people appear empty for unlogged

### ISSUE THREAD

**Issue by bonustrack** [busyorg/busy#904]
![image](https://user-images.githubusercontent.com/16245250/32075434-0221b00c-bac7-11e7-9f9b-5c0cb967281d.png)

#### Expected behavior

I expect to not see Interesting People box when unlogged

#### Actual behavior

I see Interesting People box empty

#### How to reproduce

Try nd busy unlogged

**Comment by jm90m** [comment]
Fixed in: https://github.com/busyorg/busy/pull/857
