### ISSUE TITLE
[Proposal] Consolidate Editor Components

### ISSUE THREAD

**Issue by ryanbaer** [busyorg/busy#913]
The codebase currently contains 3 separate, but very similar, Editor components:
- `components/Editor/Editor.js`
- `components/Comments/EmbeddedCommentForm.js`
- `components/Comments/CommentForm.js`

All three of these components are rather long, in particular the Editor itself.

I think we should discuss a way of extracting common functionality. For example, the `insertImage` function between the three files is very similar, and is identical between CommentForm and EmbeddedCommentForm.

Two approaches that spring to mind:
1. Extract common functions like `insertImage` to helper methods, converting any values assumed to be on `this` into additional parameters.
or
2. Create a base class component (`BaseEditor`, but maybe with a better name), which contains the core functionality of an editor, and then all 3 implemented editors extend the base class, getting the benefit of common functionality implemented while being able to override / expand upon functionality.

Approach 1 is likely quicker. Approach 2 is likely more proper, but should probably only be done if there's enough overlap between the functions in the 3 components.

Curious to hear everyone's thoughts.

P.S. Please label this `pr: Discuss`.

**Comment by bonustrack** [comment]
@Sekhmet notes on Trello
> Editor, CommentForm, EmbeddedCommentForm share similiar logic and should be unified in some way. `onImageInserted` should use standard callback structure or even Promises
