### ISSUE TITLE
Single post, interesting people block should not appear

### ISSUE THREAD

**Issue by bonustrack** [busyorg/busy#915]
The block "Interesting people" on right sidebar should not appear on single post when logged:
![image](https://user-images.githubusercontent.com/16245250/32127235-7f8cb6a8-bb9f-11e7-90bf-8f6cfb55267d.png)
Also there should be a bottom margin on sidebar right blocks

**Comment by ryanbaer** [comment]
Yes, was going to report this. Thanks for fixing it. Also noticed: on Recommended Posts, there's no context menu (i.e. I can't right-click), nor Cmd + Click to open in a new tab. I don't always want to navigate away from the page I'm on right away.

I can file into another issue if you'd like.

**Comment by jm90m** [comment]
@ryanbaer yeah probably should put it in another issue

**Comment by ryanbaer** [comment]
Couldn't assign you, so here you go: https://github.com/busyorg/busy/issues/917

**Comment by jm90m** [comment]
@ryanbaer thanks!

**Comment by bonustrack** [comment]
Fixed in #916
