### ISSUE TITLE
Position of Material Icons in Navbar

### ISSUE THREAD

**Issue by Tanvir-rahman** [busyorg/busy#920]
#### Expected behavior

The Material Icons should be in middle with label in Navbar

#### Actual behavior

Starting from same position. So it's looking like text is holding upper position from icon.

![capture](https://user-images.githubusercontent.com/15964566/32136770-ae82fde6-bc35-11e7-93b7-213b3e83afde.PNG)

#### How to reproduce

Go to https://busy.org/ and observe navbar

* Browser: Firefox, Chrome
* Operating system: Windows 10

**Comment by cron9** [comment]
Aligning working well. It is just icon problem. We could separately style "Hot" icon, if it is needed.

**Comment by Tanvir-rahman** [comment]
Yeah. As a user i shared my thought.....  🙂

**Comment by jm90m** [comment]
With our new design this issue is no longer relevant. So I'll be closing this. Thanks for opening this up though and bringing it to our attention 😄
