### ISSUE TITLE
Pasting Data into Tags Puts Draft into Unrecoverable State

### ISSUE THREAD

**Issue by ryanbaer** [busyorg/busy#924]
#### Expected behavior
The Tag Editor should strongly validate what can be inputted, and should not `PUT` to `/me` if the client-side validation fails

#### Actual behavior
1. Pasting a large enough string of data puts the draft into an unrecoverable state
1. Validation Errors on the client-side display an error but still `PUT` data to `/me

![oct-28-2017 12-59-21](https://user-images.githubusercontent.com/11914327/32138011-070048f8-bbe0-11e7-9742-8e7f3ecb055c.gif)

#### How to reproduce
1. Create a new draft
1. Enter a title
1. Enter some article content so the draft is saved (i.e. `PUT` to `/me` occurs)
1. Get a large string of text. A good example is the entire Markdown of another article
1. Click in the Tags input and press Ctrl or Cmd +V to paste in your clipboard data
1. Note that you get a validation errror, the tags box remains blank, and you can no longer interact with it
1. Note that you cannot publish your draft
1. If watching Network Requests, note that `jsonMetadata.tags` for your draft is now a very large array - in my case, it looks as follows:
![image](https://user-images.githubusercontent.com/11914327/32137913-e0619870-bbdd-11e7-9967-057b395eb538.png)

I've already started looking into this one, so feel free to assign to me.

* Browser: Chrome 61
* Operating system: macOS 10.12.6

**Comment by ryanbaer** [comment]
This issue can now be closed

**Comment by Sekhmet** [comment]
Fixed in #945.
