### ISSUE TITLE
User can't see the whole history in wallet

### ISSUE THREAD

**Issue by espoem** [busyorg/busy#928]
#### Expected behavior

User should be able to see whole history of his transactions.

![image](https://user-images.githubusercontent.com/16621517/32141725-8deaa352-bc87-11e7-9f62-ff88b09fb967.png)

#### Actual behavior

Wallet shows a lot of records but they are not all.

![image](https://user-images.githubusercontent.com/16621517/32141728-92a669c6-bc87-11e7-9d93-73121c1388ff.png)

#### How to reproduce

1. Go to wallet.
2. Scroll to the end. It won't fetch other records.
3. Compare with Steemit.

* Browser: Chrome
* Operating system: Windows 10

**Comment by jm90m** [comment]
Fixed in https://github.com/busyorg/busy/pull/976. Closing this but If you re-test this issue, and there is a bug, you can re-open or create a new one.
