### ISSUE TITLE
The sidebar in profile disappears when wallet is shown and page reloaded

### ISSUE THREAD

**Issue by espoem** [busyorg/busy#930]
#### Expected behavior

The sidebar should be visible at all times or it should dissapear without the need to reload the page.

#### Actual behavior

When you go to your profile, you see the discussion and the sidebar. If you click on the wallet tab the sidebar stays. If you reload the page, it disappears.

![image](https://steemitimages.com/0x0/https://res.cloudinary.com/hpiynhbhq/image/upload/v1509260952/rtuarf2pewc0i6vwpb5q.gif)

#### How to reproduce

1. Go to your profile
2. Click wallet tab
3. Reload the page

* Browser: Chrome
* Operating system: Windows 10

**Comment by jm90m** [comment]
@bonustrack do you think we should show the `SteemTrendingCharts` component sidebar here for the wallet page? or keep it `InterestingPeople`

**Comment by mktcode** [comment]
I advocate the charts.

**Comment by jm90m** [comment]
Resolved in https://github.com/busyorg/busy/pull/949
