### ISSUE TITLE
[Feature Proposal] Image Gallery Captions

### ISSUE THREAD

**Issue by ryanbaer** [busyorg/busy#942]
![image](https://user-images.githubusercontent.com/11914327/32146789-4b66798a-bc9a-11e7-9d28-5daa43870a62.png)

One feature I think is particularly great about Busy v2 is the gallery feature for posts - how you can click on an image in the post and thumb through the images easily. This alone makes Busy feel more modern alongside major social networking sites, etc.

However, I also think an enhancement could be made that would provide a unique experience to those using Busy, while not impacting other Steem consumer apps: image captions.

The idea, if it isn't already apparent, is to allow authors to optionally specify a caption to be displayed alongside their image in the gallery.

#### Implementation Details

This feature should be implemented in a way that:
- **Doesn't impact post experience on other platforms:** i.e. no pseudo-protocol clutter like `busyv2imgcaption:"This is a picture of my dog LOL!!!"`)
- **Avoids false positives:** Simply having text immediately following the image shouldn't get pulled into the caption
- **Gracefully handles caption text limit to preserve UX:** A simple truncation with ellipses for anything over the limit. Perhaps a limit of a few hundred characters - enough to be reasonable but not so long that it provides an unpleasant experience on mobile.

#### Some initial brainstorming:
- Something clean and simple, like using a Markdown feature with a keyword (that should have i18n) which still looks normal if you're using another platform:
```
![img](https://steemitimages.com/0x0/https://steemitimages.com/DQmNquXAUt8xbxetcREafiiNMXvAz
4QJJUzZP6Hw8QEhBQ3/image.png)
> caption: Feeling the heat of the jet exhaust as this jet makes its way past the crowd.
```
- Or making use of the alt text via Markdown itself (perhaps less user-friendly without an additional UI component to prompt users for the caption):
```
![Feeling the heat of the jet exhaust as this jet makes its way past the crowd.](https://steem
itimages.com/0x0/https://steemitimages.com/DQmNquXAUt8xbxetcREafiiNMXvAz4QJJUzZP6Hw8QEhBQ3
/image.png)
```
- Or a header tag itself, as the author of the example post used - but this perhaps forces some unpleasant styling on people due to how the headers are rendered:
```
## Feeling the heat of the jet exhaust as this jet makes its way past the crowd.
![img](https://steemitimages.com/0x0/https://steemitimages.com/DQmNquXAUt8xbxetcREafiiNMXvAz
4QJJUzZP6Hw8QEhBQ3/image.png)
```

*Post Source: [Getting the shot and feeling the heat](https://nd.busy.org/planes/@ngos/getting-the-shot-and-feeling-the-heat)*

**Comment by Sekhmet** [comment]
I don't think we should extend Markdown in any way. If we do, we will have some posts that use non-standard format, posts won't display properly in other clients.

We could use `alt` but it's not very often used and if it is, it's not meant to be an caption.

**Comment by Sekhmet** [comment]
@bonustrack what's your opinion on that?
