### ISSUE TITLE
Can't run dev server

### ISSUE THREAD

**Issue by mktcode** [busyorg/busy#943]
When I run `npm run dev-server` I get this error:

![busy-install-issue](https://user-images.githubusercontent.com/6792578/32148704-4015177e-bcfb-11e7-806d-ffa074ea79cc.png)

When I fix [webpack-dev-server.js](https://github.com/busyorg/busy/blob/new-design/webpack/webpack-dev-server.js#L24) by removing the commas, ESLint complains about the missing trailing commas.

![busy-install-issue2](https://user-images.githubusercontent.com/6792578/32148722-657bbb8a-bcfb-11e7-917e-96cdf770ec99.png)

What shall I do? Submit PR with removed commas or not?

Node 6.11.5

**Comment by bonustrack** [comment]
Which version of Node are you using @mktcode ?

**Comment by mktcode** [comment]
Oh sry I forgot... 7.x Not at my computer right now. I will add the exact version numbers later.

**Comment by mktcode** [comment]
It's 6.11.5 not 7...

**Comment by Sekhmet** [comment]
We target node `7.10.1+` and npm `5.3.0+`. Can you verify that you have this issue with supported version of node and npm?
https://github.com/busyorg/busy/blob/new-design/package.json#L4-L7

**Comment by Kennybll** [comment]
https://github.com/busyorg/busy/pull/1003

**Comment by Kennybll** [comment]
So I see in version 8.9.0 this is not a problem. But in older versions the commas not deleted crash the dev-server. I also tested on version 8.9.0 without commas, and it still works.

**Comment by Sekhmet** [comment]
As it turns out trailing comma in function arguments is supported since node 8.
Should we disable rule for `comma-dangle` in functions or support node 8+ (as `8.9.0` is current LTS version)?

cc: @bonustrack @jm90m

**Comment by jm90m** [comment]
@Sekhmet I am fine with disabling comma-dangle in functions, I ran into this issue as well. But it also might be good to upgrade node versions. What are the benefits of upgrading Node versions? I'm not a node expert / haven't looked too much into it.

On a side note, we should disable arrow-parents eslint as well :)

**Comment by Sekhmet** [comment]
I'm not sure what's wrong with `arrow-parens`, do they cause some inconveniences?

**Comment by jm90m** [comment]
oh no its just prettier removes it automatically

**Comment by Sekhmet** [comment]
@jm90m 
Do you mean that it changes `(args1, args2) => ...` to `args1, args2 => ...`?
Not sure I understand what do you mean, can you give an example?

**Comment by jm90m** [comment]
![screen shot 2017-11-04 at 9 55 39 am](https://user-images.githubusercontent.com/5067716/32405991-54f76742-c146-11e7-83ba-cb16215e4cf2.png)

Go to a file like `busy/src/helpers/apiHelpers.js` and run prettier, it removes the `()` for functions with single parameters

**Comment by Sekhmet** [comment]
Not big fan of changing (or actually removing part of) code style, because some tools people might use might cause inconveniences.
Both VSCode and Atom has prettier integration that respects eslint rules. I guess you are using prettier CLI in WebStorm. It can be configured to work with eslint as well (https://github.com/prettier/prettier#eslint), but it won't work out of the box.

**Comment by Sekhmet** [comment]
This is not a problem on node 8 (which is new LTS version). Please consider upgrading to node 8.
