### ISSUE TITLE
Potentially Incorrect Usage of onChange with antd's Form

### ISSUE THREAD

**Issue by ryanbaer** [busyorg/busy#946]
Upon reading AntDesign's documentation for using `Form`, I found the following note:
> After wrapped by getFieldDecorator, value(or other property defined by valuePropName) onChange(or other property defined by trigger) props will be added to form controls，the flow of form data will be handled by Form which will cause:
> 1. **You shouldn't use onChange to collect data**, but you still can listen to onChange(and so on) events.

Just to clarify, our usage of `Form`:
- Uses `getFieldDecorator`
- Uses `onChange` to collect data

I don't know the full history of this comment in `Editor.js`:
> // NOTE: antd doesn't update field value on Select before firing onChange
    // so we have to get value from event.

So I'm not clear if the author was aware of the note in the documentation or not. If this function was implemented with the knowledge of that documentation, then feel free to close the issue.

However, for the sake of this issue I'm going to operate under the assumption that it wasn't. If that's the case, it would explain why we had issues with collecting data from `onChange`.

In fact, in my fix for #924, I found that validators aren't invoked until *after* `onChange` has run, and when I triggered the validators from within `onChange`, I found that they were running against the previous data - i.e. I had just entered 6 tags, and the validator ran on the previous input which contained 5 tags, hence it did not fail.

So going with the assumption that we shouldn't be using `onChange` in this way, we should switch from using `onChange` to using their recommended function `onFieldsChange`. In theory, this should free us from our workaround functions like `onUpdate` and `getValues`.

If I'm completely wrong about this issue, please let me know what the story is and why we should in fact be using `onChange`.

**Comment by Sekhmet** [comment]
Hey, Thanks a lot for taking a look at this problem.
I wasn't aware of existence of `mapPropsToFields`, `onFieldsChange`, `onValuesChange`. I was looking for some handler that fires when value actually changes inside `this.props.form`, but didn't expect it to have those handlers inside `Form` wrapper.
I think we can make code a lot cleaner thanks to them. We could use both `mapPropsToFields` and `onFieldsChange` and it should remove a lot of boilerplate.

Do you want to take on this issue?

**Comment by Sekhmet** [comment]
`Form.createFormField` is not present in our current version of antd so we can't handle this that way right now. We have to upgrade antd first, which might cause some things to stop working.
I will take a look at this after we do that.

**Comment by Sekhmet** [comment]
We made changes to our editor in #1458. It's not using `Form.createFormField` as it's not available in version of antd we are using, but we might consider using it when we upgrade.
