### ISSUE TITLE
Tooltip to unvote show "Dislike" instead of "Unlike"

### ISSUE THREAD

**Issue by bonustrack** [busyorg/busy#948]
When i vote for a post and then bring my mouse over the like icon there will be a tooltip "Dislike":
![image](https://user-images.githubusercontent.com/16245250/32167238-ecb812c0-bd9a-11e7-8b1b-4f11f85250f7.png)
This is wrong, there should be a tooltip "Unlike" instead, "Dislike" should be used for downvote only.

**Comment by jm90m** [comment]
Fixed in: https://github.com/busyorg/busy/pull/952
