### ISSUE TITLE
Add scrolling option to see all upvoter

### ISSUE THREAD

**Issue by Tanvir-rahman** [busyorg/busy#951]
A scrolling option to see all up voter will be a very good addition. Is it possible to add this feature?

![2](https://user-images.githubusercontent.com/15964566/32180203-8707d78c-bdbb-11e7-93ba-2971b1bcca09.png)

**Comment by bonustrack** [comment]
You can click on the like counter and get the full list if you want. I think a scrolling in the tooltip doesnt fit well.

**Comment by Tanvir-rahman** [comment]
In mobile screen, it's taking full device screen. I was thinking, here only post should get priority. Ex: "Steemit More Info" plugin. By the way it's complete a suggestion from a user.

**Comment by sirrius-a-b** [comment]
I think it is normal behavior for a modal to take the full screen on small devices. I would say that this can be closed.

**Comment by bonustrack** [comment]
This is not considered as a real issue i'm closing it.
