### ISSUE TITLE
Add Images with Underscore in Busy.org

### ISSUE THREAD

**Issue by codingdefined** [busyorg/busy#956]
When I upload Images in Steemit it creates a path which includes steemitimages.com and then the whole path.

For Example : https://steemitimages.com/ +  DQmaYauBqmx5z8GiwJTKPpinTQ6ebxetwhJKqakruLEwDQJ/IMG_20170302_105004917.jpg

Now if you have an Image which has underscore ("_") in it, busy.org remove that underscore from the URL.So, when you try to copy the URL to busy.org, it looks something like below where the underscore is missing.

![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1509423844/oq6uypcopegt9fooxpx9.png)

<br /><hr/><em>Open Source Contribution posted via <a href="https://utopian.io/utopian-io/@codingdefined/add-images-from-steemit-to-busy-org">Utopian.io</a></em><hr/>

**Comment by espoem** [comment]
This issue is considering Busy 1.

**Comment by Sekhmet** [comment]
Hey, thanks for reporting
This bug is related to Busy v1 which is about to retire on 1st of the November. Because of that only security bugs are in our scope. You should really use Busy v2 (which now live here: https://busy.org).
