### ISSUE TITLE
'NaN' is visible while loading the wallet

### ISSUE THREAD

**Issue by bonustrack** [busyorg/busy#959]
On the wallet for the balance of SP, `NaN` should never be visible for the user, there should be a loading instead:
![image](https://user-images.githubusercontent.com/16245250/32229238-efa79e86-be82-11e7-8b65-bb2bbab94175.png)

### Steps to reproduce
Go to https://nd.busy.org/@fabien click on "Wallet", then you should see 'NaN' when balance is loading.

**Comment by jm90m** [comment]
Fixed in https://github.com/busyorg/busy/pull/960
