### ISSUE TITLE
High Five improvement suggestions for New Busy Interface #1

### ISSUE THREAD

**Issue by lykkejay** [busyorg/busy#966]
## Five improvement suggestions for New Busy Interface
Here I have included five things that I saw can be enriched by enhancing the functionality of the features. New buys interface has brought many appreciative features which I really liked and few things where the improvements are needed, so here's the  **High Five.** suggestions I have for @busy.

### 1. 100% power up posts are not clearly noticeable.
 ![](https://steemitimages.com/DQmQbewYbqNCU82Syt1c9Gzpko3kktMWVMQtnN3YBkGwLEw/image.png)
I believe that 100% Power Up posts should be given more priority and should be easily distinguishable. As you can see that 100% Power Up sign is greyed out which can be easily missed out. In my opinion, supporting 100% Power Up posts can help the platform in the long run since the Author is posting with the intention to stay for the long haul. Please add some bright color to it or make the sign little bigger. Please add some bright color to it or make the sign little bigger. We may add few three signs instead of one.We may add few three signs instead of one.

### 2. Profile pictures on the posts are not loading properly.
![](https://steemitimages.com/DQmW6S3eNq7WJWkzi1xCXwcCNSnSmtcS7N76KvQYtD3exyd/image.png)</center>
As you can see in the above screenshot, profile picture on the page is not loading properly. I reloaded the page as well, but still, that didn't resolve the issue. 
![](https://steemitimages.com/DQmPKnosS7gdDRSbfXx6VUFfwoTNbM2HNnKpcsErDMLPMUT/image.png)</center>
Here's the other issue of not displaying the post properly. Even on the profile, it didn't display the image on the right corner of the profile pic. 
![](https://steemitimages.com/DQmaxthkV4FRYsvxrGu5ur1ssu8bhtpXJQFRx36D1VQrod8/image.png)
It is constantly bringing many similar errors shown in the above image. 

### 3. Ability to display the people who liked the post( Popup to display "and <additional-number-of-likes> more" users.)
![image1](https://steemitimages.com/DQmYZ6w6VA3viLXa84JS7BTqanDya83AUAaL7NxMNrujgMp/image.png)
As shown in the above image, you can see that few users are listed visible and 19 more were hidden. Since you can see the list of few users who liked your post and rest are hidden in the "and <additional-number-of-likes> more" and when you click on it, It's non-responsive. I am not sure, it's the intention to do keep it that way or not, but I would highly suggest giving the ability to the users to view the rest of the users who liked the post. 

### 4. "Discover more people" feature not reacting as per the functionality. 
![](https://steemitimages.com/DQmZRsWvwmQpPcD1tpfTNMoM5K47YDj2NZWu3JzEtFWyWvi/image.png)
"Discover more people" feature is redirecting the users to "https://nd.busy.org/latest-comments" url, but is not showing effects on the posts which are already on the wall. It is simply changing the URL, but posts displayed already( eg. trending) are not responding to the action.  

### 5. Plankton, Minnow, Orca ????
![](https://steemitimages.com/DQmWZG6KrQQUP8LZ5cdmcyTEds4E73VpJpgnFM8nKYXdzxk/image.png)
I saw Plankton, Minnow, and Orca in the accounts, but wasn't sure what they are and how it gets classified. I would love to see users being informed about the features and system that's built for the platform. Please display some information when user mouse hover on the name(eg. Plankton)

**Thank you !!** 

<center> 
**Click [![utopian.io](https://utopian.io/img/utopian-logo-120x120.png)](https://utopian.io)  to Contribute**
Yours @lykkejay 
</center><br /><hr/><em>Open Source Contribution posted via <a href="https://utopian.io/utopian-io/@lykkejay/high-fives-improvement-suggestions-for-new-busy-interface-1">Utopian.io</a></em><hr/>

**Comment by jm90m** [comment]
I updated your comment, your images weren't showing up with `<center>` tags around them, so had to remove them to display images.

**Comment by lykkejay** [comment]
Thank you!

**Comment by Sekhmet** [comment]
1. It's this way by our current design. Design is subject to change soon so it might not be relevant anymore.
2. 3. 4. Are already fixed.
5. Those are just ranks that we display. We don't have any good explanation for them. If we were to put information about how it's determined it would become cumbersome.
