### ISSUE TITLE
Market showing wrong rates for STEEM and SBD

### ISSUE THREAD

**Issue by bonustrack** [busyorg/busy#967]
On the market widget i can see this rates currently:
![image](https://user-images.githubusercontent.com/16245250/32275578-5adc15cc-bf3e-11e7-8d71-b3665af30147.png)
When i check on https://coinmarketcap.com/ i will get a very different rate:
![image](https://user-images.githubusercontent.com/16245250/32275596-6d9712b6-bf3e-11e7-885e-9167560aa8a1.png)
![image](https://user-images.githubusercontent.com/16245250/32275592-6770a622-bf3e-11e7-833a-ef3709450f11.png)
Price we are showing not see reliable, there should be a similar rate on both sites.

**Comment by jm90m** [comment]
Should be fixed now, closing this. Fixed in https://github.com/busyorg/busy/pull/968
