### ISSUE TITLE
Busy mobile device optimization is not properly allowing the tag search. #3

### ISSUE THREAD

**Issue by lykkejay** [busyorg/busy#971]
## <center> Hello!! </center>

This is the Busy mobile test that’s being performed with Safari Browser in IOS 11.0.2 As I was looking into features that’s available on the mobile view. I noticed that tag searches are not available.
 ![image](https://img.esteem.ws/kekw6hz4dx.jpg)
I went inside the post and figured there were the tags which can be searched.
 ![image](https://img.esteem.ws/1k6wgeknc9.jpg)
It will search the tags like the image below, but the problem is you won’t be able to search for another tag after removing the existing one.
 ![image](https://img.esteem.ws/lnprkb124u.jpg)
Thank you
@lykkejay

**Comment by bonustrack** [comment]
This should be fixed by now, @lykkejay are you able to see the search now?
