### ISSUE TITLE
Missing translation of "Page Requires Authentication"

### ISSUE THREAD

**Issue by espoem** [busyorg/busy#974]
Busy has been translated into many languages. But Busy needs to keep updating the new strings so they can be translated.

![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1509572242/ui3gihgl5ezgtcbqj5wx.png)

This page appears if you need to be logged in for some action. I tried to see the wallet page. You can see that there are two languages mixed with each other.

## Expected Behaviour

All the English strings should be translatable and shown in the set language.

## Steps to reproduce

1. Stay logged out
2. Have browser set in a language different from English (mine is Czech)
2. Go to https://busy.org/wallet<br /><hr/><em>Open Source Contribution posted via <a href="https://utopian.io/utopian-io/@espoem/missing-translation-of-page-requires-authentication">Utopian.io</a></em><hr/>

**Comment by eastmaels** [comment]
I checked the Czech's locale file (`cs.json`?) and saw that there are no entries yet for the two text items.

English (en.json):
![image](https://user-images.githubusercontent.com/29425738/32439443-c02de06a-c329-11e7-8335-376537e73d4c.png)

Czech (it only has until `market`:
![image](https://user-images.githubusercontent.com/29425738/32439472-e08676a6-c329-11e7-822e-39ddf2c1d247.png)

**Comment by espoem** [comment]
That's because the strings haven't been synced/updated with Crowdin yet. https://crowdin.com/project/busy

I do not add new Czech translations directly into the json files. The Crowdin is used by others too. If Crowdin is not preffered method for addition of new translations, I can add them manually into the json files.

**Comment by eastmaels** [comment]
Okay, i'm not familiar of how string are added to json. so these string keys are added to crowdin first, and then pushed to github. copy that. thanks.

**Comment by jm90m** [comment]
Does this issue still exist @espoem I believe we updated translations recently?

**Comment by espoem** [comment]
It was resolved. The strings were updated.
