### ISSUE TITLE
Change the way search features works in Busy beta.

### ISSUE THREAD

**Issue by ruahtheking** [busyorg/busy#975]
Lately, while browsing using @busy.org I try to search, some artworks post of others. 
But after using the search features it brings me to google instead of giving me the list of artwork in the feed. 

![](https://im3.ezgif.com/tmp/ezgif-3-960b7719e0.gif)

I suggest that instead of bringing users to google when using the search features in busy why don't use the feed to give what the users want to search?

Here is the example of what I want to happen. 
In Utopian when you search for a project it will give you a project list.
When you search for an Idea of Busy it will give you those Idea. 
![](https://im3.ezgif.com/tmp/ezgif-3-78610cefd5.gif)

# Here's Another Example!
I tried to search about the bug of busy in utopian.io. 
![](https://im3.ezgif.com/tmp/ezgif-3-8b33c0754d.gif)

Again I'm Suggesting for Busy to make the search features of Busy to make easier to use. Show the result on the feed instead of bringing user in Google. <br /><hr/><em>Open Source Contribution posted via <a href="https://utopian.io/utopian-io/@ruah/change-the-way-search-features-works-in-busy-beta">Utopian.io</a></em><hr/>

**Comment by bobinson** [comment]
more details are here #1070 

also it tests in new firefox versions.

**Comment by Kennybll** [comment]
@bonustrack Do you think we should use site:busy.org on the google search for the TopNav, instead of site:steemit.com? Also I was looking at asksteem.com's api. We could possibly use that, though you can only go to page 10. https://github.com/Hoxly/asksteem-docs/wiki

**Comment by bonustrack** [comment]
This issue has been fixed here #1183
