### ISSUE TITLE
“Write Post” option indicator is non-responsive. #2

### ISSUE THREAD

**Issue by lykkejay** [busyorg/busy#977]
## <center> Hello!! </center>

This is the Busy mobile test that’s being performed with Safari Browser in IOS 11.0.2 version. While performing this test, I found non-responsive option that’s given to the user. It might have been intentionally kept that way, but implementing addiction action feature is possible and can make the feature better.

 ![image](https://img.esteem.ws/r1gocxzll5.jpg)

As soon on the above image, “Write Post” is shown while clicking at it for the first time, but when you click on the “Write Post”, it’s not responding. It’s only linking it to the editor page after clicking on the “Write Post” icon. 

 ![image](https://img.esteem.ws/1vpx5wriup.jpg)

When the user gets redirected to the editor page, “Write Post” is still showing above. This message should hide since the action has been already taken. It does hides, but only when user clicks on the editor to write.

### **Expected solution/Suggestion:**

 ![image](https://img.esteem.ws/5kafzdac9f.jpg)

It will be proper to hide the “Write Post” indicator after being redirected to the editor page. User should get redirected to editor page and “Write Post” message should disappear when user clicks to write message. Hiding message and Redirecting to editor page should happen same time while taking the action to Write Post.

 ![image](https://img.esteem.ws/txxr2gbuzh.jpg)

Feature to link the user to the editor page can be enabled on the “Write Post” indicator as well. There should be hyperlink which should direct the user to the editor page.

** Thank You!!**

@lykkejay
<br /><hr/><em>Open Source Contribution posted via <a href="https://utopian.io/utopian-io/@lykkejay/write-post-option-indicator-is-non-responsive-2">Utopian.io</a></em>

**Comment by Sekhmet** [comment]
It's minor antd issue, that we cannot fix ourselves.
