### ISSUE TITLE
Migrate from `ReduxInfiniteScroll` to `ReactInfiniteScroll` (required for React Fiber)

### ISSUE THREAD

**Issue by jm90m** [busyorg/busy#985]
Instead of using a different library like ReactInfiniteScroll, (https://github.com/CassetteRocks/react-infinite-scroller). My proposal is, we should instead just fork the ReduxInfiniteScroll library, and we should just update it ourselves specifically for us. After trying to use both ReactInfiniteScroll and ReduxInfiniteScroll for the Wallet page, I feel that ReduxInfiniteScroll is a lot better and has more features such as the loader, that we currently use.

I looked into the src code for ReduxInfiniteScroll, and it's not that bad to understand, I think we are better off in the long run just adopting it into our project and updating it when necessary. We can either fork the repo or just create the `ReduxInfiniteScroll` common component within our project directory.

@Sekhmet @bonustrack let me know your thoughts on this.

**Comment by Sekhmet** [comment]
AFAIK `react-infinite-scroller` has loader as well (`loader` prop).
I think that it's better to rely on maintained project instead of forking dead library.
If it would be hard to achieve the same look and feel as we have currently if `react-infinite-scroller` or any other library I think we can fork, but I don't it should be our 1st option.
If we do fork, we should is it everywhere (we currently have two libraries for scrolling).

**Comment by Ne3l** [comment]
Also think we should use a mantained project, it will save us time in the future.

My proposal would be The [infinite loader](https://bvaughn.github.io/react-virtualized/#/components/InfiniteLoader) from [React-virtualized](https://github.com/bvaughn/react-virtualized). It is a well know library in react ecosistem with more activity that the other options.

**Comment by jm90m** [comment]
The problem with the `react-virtualized` infinite loader, is that it doesn't support dynamic heights on rows out of the box. You can try to implement it and see if it works, I tried doing it just now for the activity page but it looks like there might be a lot more work involved with it.

**Comment by Ne3l** [comment]
Truly, is gonna be more verbose and complex than the drop-in `react-infinite-scroller`.

The pros of using `react-virtualized` is that it only renders the elements visible on-screen making it more efficient on large list but i'm not sure the overhead gonna be worth in our case scenearios.
