### ISSUE TITLE
Have "save button" in settings translatable

### ISSUE THREAD

**Issue by espoem** [busyorg/busy#987]
#### Expected behavior

The text of Save button should be in the set language.

#### Actual behavior

The text in the button always says **Save**.

![image](https://user-images.githubusercontent.com/16621517/32364644-4faa2714-c076-11e7-962a-a86fba023cba.png)

#### How to reproduce

1. Go to the settings
2. Change the language to other than English and save
3. Button shows Save

* Browser: Chrome
* Operating system: Windows 10

**Comment by Sekhmet** [comment]
Fixed in #994.
