### ISSUE TITLE
Replies are not accessible on mobile device anymore

### ISSUE THREAD

**Issue by espoem** [busyorg/busy#991]
The replies have been moved from the drop menu at the right top to the left navigation on the main page.

Replies are not accessible on mobile after this change.

### Before the change

![Screenshot_20171016-164849.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1509712623/hvzxzvf6fgh29dz9f6g9.png)

### After the change

![](https://i.imgur.com/rcm3BCf.png)

* Browser: Brave
* OS: Android 7.1.2

**Comment by jm90m** [comment]
Yeah looks like a lot of the current user's side menu items are not able to be seen in mobile. Maybe for all screen sizes under 998px, we can add all navigation links to the top right user sidebar. @bonustrack what are your thoughts?

**Comment by pareshUD** [comment]
Not sure why Replie's isnt available in to the menu.. You can bring it back I guess @jm90m

**Comment by jm90m** [comment]
I'll add it back to menu, what order should they go in @pareshUD
