### ISSUE TITLE
Add hero for not logged in user

### ISSUE THREAD

**Issue by Sekhmet** [busyorg/busy#999]
If user isn't logged in we should have hero that will show up for him. I think user should be able to dismiss hero by clicking x icon, and it won't show up for them anymore (should be saved to local storage).

**Comment by Sekhmet** [comment]
@bonustrack where should be this hero displayed? Will it be visible everywhere or on specific pages only?
What content should it consist of?
```
+--------------------------------------------------------+
|                                                      x |
|        Ensure compensation for creator of value        |
|                                                        |
|                                                        |
|                                                        |
|                +---------+  +--------+                 |
|                | Sign up |  | Log in |                 |
|                +---------+  +--------+                 |
|                                                        |
+--------------------------------------------------------+

```

**Comment by bonustrack** [comment]
@Sekhmet the title `Ensure compensation..` and buttons should be left aligned. The hero should only appear in the homepage when unlogged.
